### ISSUE TITLE
Resolve Pitest Issues - CommonUtil

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#10052]
Child Issue of #7797

**Comment by romani** [comment]
All violation should be tried to covered by functional tests, not a UTs. Coverage  by pure UTs is absolute last resort.

**Comment by shashwatj07** [comment]
I don't think we can do much about this one.
https://github.com/checkstyle/checkstyle/blob/578a97541eb50f27db3f5d8f4d9b16d09d8618c6/.ci/pitest.sh#L171-L172
Since we have a URL object
https://github.com/checkstyle/checkstyle/blob/6cbc1dc3c01385426b8bcfd9988e92acdc9390a9/src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java#L448
which is assigned to by
https://github.com/checkstyle/checkstyle/blob/6cbc1dc3c01385426b8bcfd9988e92acdc9390a9/src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java#L449-L454
which gives URLs that are [RFC 2396](https://www.ietf.org/rfc/rfc2396.txt) + [RFC 2732](https://www.ietf.org/rfc/rfc2732.txt) compliant, which is exactly what URI expects.
So an exception occurring here is a non-existent scenario.
https://github.com/checkstyle/checkstyle/blob/6cbc1dc3c01385426b8bcfd9988e92acdc9390a9/src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java#L460-L466
since URL anyway is a subset or URI.

**Comment by timurt** [comment]
@shashwatj07 agree, lets skip it for now
@romani fyi

**Comment by timurt** [comment]
I will close this issue

**Comment by shashwatj07** [comment]
Should I add a comment in ```pitest.sh``` referencing https://github.com/checkstyle/checkstyle/issues/10052#issuecomment-851569300?
It will prevent people from spending time on it in future.
@timurt

**Comment by timurt** [comment]
I think it is not necessary, maybe someone else would find approach how to do this

**Comment by romani** [comment]
Lets move this to the end, but we need to resolve this, I can guide later on .

**Comment by romani** [comment]
if we have no way to kill mutatation by functional test we can do this by pure UT with not business logic coverga goal, but simply to make pitest 100% covered, as in this case easier to find problems.

**Comment by pbludov** [comment]
Fixed by #10932
