### ISSUE TITLE
Resolve Pitest Issues - TagParser.java

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#10068]
Child Issue of #7797

Try to resolve these suppressions

```
  "TagParser.java.html:<td class='covered'><pre><span  class='survived'>                while (column &#60; currentLine.length()</span></pre></td></tr>"
```

I am not sure we can do smth about `beginJavadocTree` and `finishJavadocTree`, try :)

**Comment by shashwatj07** [comment]
For
https://github.com/checkstyle/checkstyle/blob/b1d2ebf2f801d14e5c3a5da8b0e26e624db9c161/.ci/pitest.sh#L152
the mutation is surviving on negating 
https://github.com/checkstyle/checkstyle/blob/b1d2ebf2f801d14e5c3a5da8b0e26e624db9c161/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/TagParser.java#L268
The sole purpose of this loop is to skip beginning Javadoc spaces and asterisk like 
```
   /**
    * some Javadoc here
    * some more
```
and return the position of the next Javadoc Character.
However, it is a private method and is used just as a helper function within the ```TagParser``` class. Looking at the invocations, it is never invoked in a place where we are specifically looking for asterisk or whitespaces.

https://github.com/checkstyle/checkstyle/blob/b1d2ebf2f801d14e5c3a5da8b0e26e624db9c161/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/TagParser.java#L268-L278
This can be safely removed as the function can be made to return the next position irrespective of leading whitespace/asterisk since they are being accounted for wherever the function is called.

**Comment by Vyom-Yadav** [comment]
@romani @nick-mancuso Can we close this, this has been addressed.

**Comment by Vyom-Yadav** [comment]
```
$ cat pitest-javadoc-suppressions.xml | grep "while (column &lt; currentLine.length()"

```

**Comment by romani** [comment]
will be handled at https://github.com/checkstyle/checkstyle/issues/13672
