### ISSUE TITLE
ParenPad check can't be configured to allow spaces only around method parameters

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1058]
Follow-up to the user question: http://stackoverflow.com/questions/30053174/whitespace-after-opening-and-before-closing-bracket-of-method-constructor-declar/30057579?noredirect=1#comment48277567_30057579

TL;DR - ParenPad check can't be configured allow spaces only around method/constructor parameters and disallow spaces in method calls, constructor calls and calls of super:

My idea is to achieve that by the following configuration:
 
    <module name="ParenPad">
        <property name="option" value="space"/>
        <property name="tokens" value="LPAREN,RPAREN"/>
    </module>
    <module name="ParenPad">
        <property name="option" value="nospace"/>
        <property name="tokens" value="CTOR_CALL,METHOD_CALL,SUPER_CTOR_CALL"/>
    </module>

but it doesn't work for method calls:

    void methodDefinition( int a ) { // OK
        methodCall(a); // ')' is not preceded with whitespace
    }

In this example `(` is `METHOD_CALL` token, but `)` is just `RPAREN`, so this configuration would enforce something strange:

    void methodDefinition( int a ) {
        methodCall(a );
    }

The solution would be to treat `RPAREN` with `METHOD_CALL` as a parent in the same way as `METHOD_CALL`. Similar thing is already done for `RPAREN` with `TYPECAST` as a parent: https://github.com/checkstyle/checkstyle/blob/1bd30555eac039d0486dffb3fc43b7a34117909b/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java#L92-L93

@romani, what do you think? Can I proceed with implementation?

**Comment by ubuntudroid** [comment]
Same applies to control structure conditions as in `if ( a > 7 )` and annotations like `@Annotation( "bla" )`.

**Comment by romani** [comment]
@mkordas , you proposal is not very good, as by configuration, that you provided, it is looks like two configured Check instances will conflict with each other: first will require space at all parentheses, second will demand no space at CTOR_CALL,METHOD_CALL,SUPER_CTOR_CALL but parentheses are indispensable part of that tokens so conflict will happen.

User should look at configuration and options and understand a logic without reading any documentation.

The more I look at that Check, the more I understand that it is broken by design and to support a requested use case we need to brake that Check even more. Even code of this Check is weird.

1) we need to remove from targets LPAREN,RPAREN at all, as user nee to configure exact targets of interests CTOR_CALL,METHOD_CALL,SUPER_CTOR_CALL, ANNOTATION,LITERAL_IF, .....all tokens that have in there child parentheses ... 
2) Check will find a LPAREN,RPAREN by manual traversing and do simple validation.

@mkordas , @ubuntudroid  does it make sense ? am I miss smth ?

**Comment by ubuntudroid** [comment]
Sounds exactly like what we need. :) Can't comment on the code changes
though as I don't know anything about the implementation.

Roman Ivanov <notifications@github.com> schrieb am Di., 2. Juni 2015 07:58:

**Comment by mkordas** [comment]
@romani, I really like your proposition. It should not be that hard to implement and will make this check really configurable (right now it isn't at all).

**Comment by romani** [comment]
@mkordas , please close that issue and create new one with clear description (without any misleading design suggestion) and link will be used in Release Notes and users need clearly understand what happen.

**Comment by mkordas** [comment]
Let's continue in #1189.
