### ISSUE TITLE
Add support for default IntelliJ IDEA formatting

### ISSUE THREAD

**Issue by ygots** [checkstyle/checkstyle#10941]
In particular, I have to change java import order performed by IDEA by default to overcome Checkstyle's error `Wrong order for `. See the issue #525 closed without addressing.

**Comment by rnveach** [comment]
@ygots Please provide the necessary information in the template or else the issue may be closed. We need to see what you are using now and how it doesn't match intellij's formatting.

**Comment by romani** [comment]
https://checkstyle.org/config_imports.html#CustomImportOrder

search for `To configure the check so that it matches default IntelliJ IDEA formatter configuration (tested on v14)`

https://checkstyle.org/config_imports.html#ImportOrder

search for `To configure the check so that it matches default IntelliJ IDEA formatter configuration (tested on v2018.2)`

----

if you need to use IDEA default, as whole team is using IDEA, disable checkstyle Check for import order, and use IDEA.
Checkstyle Check required only if your team using multiple IDEs. In single IDE environment the Check simply duplicates what IDE does automatically, no reason.

**Comment by romani** [comment]
> See the issue #525 closed without addressing.

here is comment https://github.com/checkstyle/checkstyle/issues/525#issuecomment-616154215
