### ISSUE TITLE
ThrowCountCheck should have option to skip private methods

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1136]
Assigned to : @Vladlis 

base on discussion at https://github.com/checkstyle/checkstyle/pull/1083

and report generated over openjdk, springframework, ........ . Nobody follow that rule of "one throw".

Even user decided to reach that target - it is will be reasonable to spit work and skip private methods as they do not cause problems for other classes and Class can decide itself on what inner level/method to do wrapping to non-checked exception to satisfy 1 throws rule.

New boolean option "ignorePrivateMethods", default value is TRUE.

Attention: reason of option should be explained in xdoc/javadoc to user.

**Comment by Vladlis** [comment]
The option has suppressed 283 violation while running the Check on openjdk7 and spring.framework with default properties (from 3733 to 3450).

**Comment by romani** [comment]
merged.

**Comment by mkordas** [comment]
What about the case when the user would like to have throws limit on public and protected methods set to 1, but on private and package-private set to e.g. 5?
This might be quite typical use case. First strict limit because of api cleanness, while second to prevent code that is unreadable and polluted.

**Comment by romani** [comment]
in next releases we could extend that Check as much as reasonable. I am ok with new option that you described.
