### ISSUE TITLE
Improvemets to Checkstyle 6.7 release notes

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1151]
In https://github.com/checkstyle/checkstyle/commit/034c2fa27fb47f1f8498d2d6c3c943dd23b19b27 I see a couple of things that could be improved:
* Move _Breaking backward compatibility_ section below _New_ and _Bug fixes_ as it doesn't matter for normal user
* Throw**s**Count, not ThrowCount
* Instead of using names like _NewlineAtEndOfFileCheck_ IMO it's better to write _NewlineAtEndOfFile check_ - name without _Check_ is easier to google and it is what users use in configs
* Provide the links to the modified checks, to quickly check their (possibly changed) docs
* For new features provide better information what exactly was added - as a quick guide for users what they can change in configs
* There are unnecessary spaces before dot at a few places like in `removing abandoned test input files . Author:  Ivan Sopov` or `Make coverage 100% for all classes at package com.puppycrawl.tools.checkstyle.checks.sizes  . Author:  MEZk`

##### Sample:
Current:

> New option value for NewlineAtEndOfFileCheck, LineSeparatorOption.LF_CR_CRLF. Author:  Martin Steiger #1045

Proposed:

>New "crlf" option for _lineSeparator_ property in [NewlineAtEndOfFile](http://checkstyle.sourceforge.net/config_misc.html#NewlineAtEndOfFile) check. Author: Martin Steiger #1045

**Comment by romani** [comment]
> Move Breaking backward compatibility section below New and Bug fixes as it doesn't matter for normal user

New items will not brake anything in users config, but "bracking items" will do Exceptions on first launch.

> ThrowsCount, not ThrowCount
Instead of using names like NewlineAtEndOfFileCheck IMO it's better to write NewlineAtEndOfFile check - name without Check is easier to google and it is what users use in configs

please provide PR for that changes

> Provide the links to the modified checks, to quickly check their (possibly changed) docs

not a manual task , should be done by tool that generate release notes, please put that request to corresponding issue.

> For new features provide better information what exactly was added - as a quick guide for users what they can change in configs

Please provide PR, release will happen on Sunday.

>There are unnecessary spaces before dot at a few places like 

please provide PR.

**Comment by romani** [comment]
merged
