### ISSUE TITLE
releasenotes script generated empty commit

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11782]
https://github.com/checkstyle/checkstyle/commit/b8d8466aa4db10128990a64384a88450d3b2e498

```
$ git show
commit b8d8466aa4db10128990a64384a88450d3b2e498
Author: Roman Ivanov <ivanov-jr@mail.ru>
Date:   Mon Jun 27 06:43:04 2022 -0700

    doc: release notes 10.3.1-SNAPSHOT

```

**Comment by Rahulkhinchi03** [comment]
@romani  @rnveach  @strkkk I am not sure enough but it seems like `PublishXdocsWithPush` can only commit with the commit message but not the content.

What I am thinking:
1. Creating a function in the release notes script that can commit and change the content.

**Comment by strkkk** [comment]
can you just amend previous commit?

**Comment by rnveach** [comment]
> but not the content.

**Comment by Rahulkhinchi03** [comment]
> can you just amend previous commit?

@strkkk  Are you talking about: https://github.com/checkstyle/checkstyle/commit/f80a6372739582941e8c73a255373646971ec63b?



> Why no content?

I believe it is because the `PublishWithXdocsPush` checks `xdocs.xml` which is in `.ci-temp.`

**Comment by rnveach** [comment]
Issue is at https://github.com/checkstyle/contribution/blob/9c8b6a478bb833d7c06e25d75bb312f632fb0775/releasenotes-builder/src/main/java/com/github/checkstyle/publishers/XdocPublisher.java#L45 .

Starting slash of pre-defined location is causing issues for adding files to commit. Removing starting slash is first thing that needs to be done. Local repo path added needs to ensure it has an ending `/` otherwise things get confused and it thinks the working directory and the first nested directory is all one path.

We need to find a way to confirm with JGit that files are being added to the commit we are making. We should also add a junit to verify the commit making is working correctly to avoid future issues.

We should also look into exception handling. When I don't have the ending `/` on the local path, I get an exception but it doesn't provide any stack trace for further debugging. It is just the exception message by itself.
Ex: `java.nio.file.NoSuchFileException: M:\checkstyleWorkspace\checkstylesrc\xdocs\releasenotes.xml`.

All the issues appear to be in `releasenotes-builder`.

**Comment by romani** [comment]
I think it will be more reliable to allow git commit and push to be done by terminal tools.
There are more reliable and we can not avoid using shell wrappers, so it would be easier to do this outside of java process.

@Rahulkhinchi03 , please update script to avoid push by java. and please confirm by testing that it works.

**Comment by rnveach** [comment]
> it would be easier to do this outside of java process

So we are good to remove this process from the Java files once shells do them? As shown above, the code is broken and there is no to reason to keep it if it won't be used.

**Comment by romani** [comment]
Yes.

**Comment by romani** [comment]
Remove code for PublishXdocWithPush, update script to do commit by shell commands.

Script has to work
