### ISSUE TITLE
prepare-settings.sh fails to create settings.xml

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11783]
```
✔ ~/java/github/checkstyle/checkstyle [master|✔] 
$ ./.ci/prepare-settings.sh 
cp: cannot create regular file '~/.m2/settings.xml': No such file or directory

```

**Comment by Rahulkhinchi03** [comment]
@romani This occurred because when you changed the `PATH` to `ENVIRONMENT VARIABLE`, it is pointing to the `$SETTING` whereas we are creating a backup file if we find out a difference. So when we find a difference, we are changing the file name but the env variable is still pointing to the previous name file.

**Comment by romani** [comment]
Fix is merged
