### ISSUE TITLE
Checkstyle suppressions are ignored in Gradle 7.5 and beyond

### ISSUE THREAD

**Issue by HEdingfield** [checkstyle/checkstyle#12043]
When updating my project to Gradle 7.5.1, my Checkstyle suppressions were suddenly ignored. Per [this issue](https://github.com/gradle/gradle/issues/21409), it's a result of Checkstyle moving to the Worker API. 

I had to manually modify `google_checks.xml` with the suggested fix in that issue, overriding what's currently in the repo [here](https://github.com/checkstyle/checkstyle/blob/0678fc609ec1889e3534940aa9d094887a4af2f3/src/main/resources/google_checks.xml) in order to get it working.

I think we should either change this in the Checkstyle repo if appropriate, or at least add warning comments nearby. This should probably also apply to the `SuppressionXpathFilter` entry as well, and changes should probably be made in `sun_checks.xml` too.

**Comment by rnveach** [comment]
> 

Please see https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F how to report an issue with our library.

**Comment by rnveach** [comment]
From what I have looked at and understand thus far.

The issue is the defined suppressions are not working when run through Gradle plugin.

It looks like gradle plugin is using our Ant task to run Checkstyle.
See https://github.com/gradle/gradle/blob/34405b3476984f51e39d374f255af638f7a19321/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CheckstyleInvoker.groovy#L67

Checkstyle uses our own Ant task for our own configuration runs, and those runs do include suppressions. We have no issue with our set up of suppressions. I have removed excess suppressions before in the file and we routinely use it for multi-PR updates.
https://github.com/checkstyle/checkstyle/blob/master/config/ant-phase-verify.xml#L11

Original report had:
> With gradle 7.4.2 build work fine and i have upgrade to last version of checkstyle 10.3.2

Checkstyle has no 7.4.2 version and user is using latest version of Checkstyle. Issue only presents itself when they change gradle's plugin version, which is what I believe the 7.4.2 is.

All this just leads me to believe this is a gradle plugin issue and not a checkstyle issue, unless a full example can be provided that shows otherwise like a run using Checkstyle directly outside gradle.

To me since Checkstyle is still running and printing violations, it seems to me that the suppression file is possibly configured as optional and is thus hiding the file not being found as optional will not throw an exception. I would possibly list it as NOT optional with nothing else changed and see if it fails and where it is expecting the file to be located. I think somehow the gradle plugin is telling Checkstyle the file is in one place and it is not there, possibly due to the CWD the process is run in.
https://checkstyle.org/config_filters.html#SuppressionFilter_Properties

Users have mentioned google_checks and using `${config_loc}/checkstyle-suppressions.xml` instead. Our google checks has the file property set to `${org.checkstyle.google.suppressionfilter.config}`.
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L34

Since this uses a property expansion, you can always provide this through system properties (`-D` in Java) and override it that way instead of duplicating the entire file manually.
https://checkstyle.org/config.html#Properties
https://checkstyle.org/config_system_properties.html#Property_chaining_support
https://checkstyle.org/cmdline.html#Command_line_usage

I am not sure how you would do this in the Gradle plugin, but I would hope the plugin developers would have implemented a way to access this feature.

**Comment by HEdingfield** [comment]
Appreciate you looking into this, thank you! Followed up in the Gradle repo to see if we can get traction on it there.

**Comment by romani** [comment]
No feedback on details, and it is clearly not an issue in our library, might be some Gradle defect.
