### ISSUE TITLE
UnusedImports doc: add limitation regarding same-name imports

### ISSUE THREAD

**Issue by DmitryNeverovich** [checkstyle/checkstyle#12224]
I have read check documentation: https://checkstyle.sourceforge.io/config_imports.html#UnusedImports
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac -classpath commons-collections4-4.4.jar ExampleClass2.java
```
Success
```
/var/tmp $ cat config.xml
```
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="UnusedImports">
      <property name="processJavadoc" value="false"/>
    </module>
  </module>
</module>
```
```
/var/tmp $ type ExampleClass2.java
package com.example.demo;
```
```
import java.util.Set;

import static org.apache.commons.collections4.SetUtils.emptyIfNull;
import static org.apache.commons.collections4.CollectionUtils.emptyIfNull;

public final class ExampleClass2 {

    /**
     * test.
     */
    public void test() {
        System.out.println(emptyIfNull(Set.of("1", "2")));
        System.out.println(emptyIfNull(Set.of("1", "2")));
    }
}
```
```
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java -jar checkstyle-10.3.3-all.jar -c config.xml ExampleClass2.java
```
Starting audit...
Audit done.

--------------------------------------------
Additional information
--------------------------------------------
Import static check does not work in one case.

**Rule:** UnusedImports - https://checkstyle.sourceforge.io/config_imports.html#UnusedImports
**Version:** 10.3.3
**checkstyle config:**  https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/sun_checks.xml

Case:
When we have two static methods with similar inputs imports(in this case collection/set). Checkstyle does not detect unused import it.

```
import static org.apache.commons.collections4.SetUtils.emptyIfNull;
import static org.apache.commons.collections4.CollectionUtils.emptyIfNull; // <-- unused import
```

![image](https://user-images.githubusercontent.com/7703560/191772842-fbe47be7-3ab9-4dd0-bca1-dcf4cf37e069.png)

Example project: https://github.com/DmitryNeverovich/checkstule-issue.git

**Comment by nrmancuso** [comment]
Please follow issue template

**Comment by DmitryNeverovich** [comment]
> Please follow issue template

changed

**Comment by stoyanK7** [comment]
On it.

**Comment by stoyanK7** [comment]
I thought about this problem for a while and it is not possible to know which of both imports is unused. Maybe at best know how many of those same-named imports are unused but not which ones in particular.

Problem is that we can not extract any other information (such asmethod signature) from just an import statement. We only have `printFileAst` identifier in AST tree.
```java
...

import static com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printFileAst;
import static com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.printFileAst;
```
![Screenshot from 2022-09-30 13-59-44](https://user-images.githubusercontent.com/23459549/193268052-7a97008d-b60b-408b-88d4-2f4717a8e254.png)


Later on in file, when method is being called, we can figure out method signature by looking at `ELIST` and find types of parameters. But this is pointless since we do not have imported method signature to compare to.
```java
printFileAst(file);
printFileAst(file, JavaParser.Options.WITH_COMMENTS);
```
![Screenshot from 2022-09-30 14-07-29](https://user-images.githubusercontent.com/23459549/193268115-189b7bbc-b782-4b56-9293-d7c7e5d0add9.png)


Maybe I am missing something?

**Comment by rnveach** [comment]
We have import statement which has method name on the end. Is there a reason we cannot look for a method call using that method name in the Java file? Is it possibly to have false positives doing this?

**Comment by stoyanK7** [comment]
>  We have an import statement which has the method name on the end.

Correct, we save that name in a `Set`-`imports` to later check if it is used in the file.
https://github.com/checkstyle/checkstyle/blob/3b91c5631e4625697150910cdcce8f81b421cbb5/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java#L286-L296

> Is there a reason we cannot look for a method call using that method name in the Java file? If we find a method with that method name being called, why is this not enough to not report it as unused?

No reason not to. It is how this check works. The problem comes **when we have two or more imported methods that have the same name** . You cannot make a reliable choice of which is called and which is not. Both would be used in the eyes of the check since it only knows about the name of the method - `emptyIfNull`.

> Also is it possibly to have false positives by doing this method?

I think no, rather the opposite. You have false negatives(imports that are not being used flagged as used in the eyes of the check since it cannot know which import is used).

**Comment by rnveach** [comment]
> The problem comes when we have two or more imported methods that have the same name . 

Yes, this is a limitation of going by the source but is also an issue for compilers.

I checked a compiler and it knew which method was being used that had different parameter types. But when the signatures where the same, the compiler complained the method being called was "ambiguous".

It is better to no report a false violation, so probably in this case it is ok if both methods are seen as being used and we make it documented that this is a limitation.

**Comment by stoyanK7** [comment]
> Yes, this is a limitation of going by the source but is also an issue for compilers.

Exactly, this is a job for compilers. They can realize what is used and what is not.

> It is better to not report a false violation, so probably in this case it is ok if both methods are seen as being used and we make it documented that this is a limitation.

Agree, the current behavior is good for not having false positives. I will make a PR about this limitation.

**Comment by romani** [comment]
is it possible to just violate situation that there is static import for same method from different classes?
so one of them is definitely extra, and user will decide.

**Comment by stoyanK7** [comment]
@romani I think that should be possible, yes.

**Comment by rnveach** [comment]
@romani The issue I found during my own testing is we can't determine if all methods are used, only 1, or none. It is possible that both methods can be used even though they have the same name.

Example that compiles on Eclipse:
````
package test;

import static test.Test2.method;
import static test.Test3.method;

public class Test {
	public void myTest() {
		method("");
		method(1);
	}
}

package test;

public class Test2 {
	public static void method(String arg) {
	}
}

package test;

public class Test3 {
	public static void method(int arg) {
	}
}
````

Please note that even though the methods have the same name they accept drastically different arguments. If you take away one of the static imports, the code fails to compile because you can't send a String to an int and vice versa.

**Comment by romani** [comment]
@rnveach , thanks a lot for investigation. I though it is not possible :).

@stoyanK7, please confirm rnveach example, if this is true, we can not support it. So we will close issue.

**Comment by stoyanK7** [comment]
@rnveach In the example you gave specifically, we can determine that two different `method()` are used by looking at parameter `ELIST`. One is using `STRING_LITERAL`, other is using `NUM_INT`. We cannot tell which imports is which but we know 2/2 imports are used.
![Screenshot from 2022-10-13 17-57-55](https://user-images.githubusercontent.com/23459549/195647366-e629ad92-cac9-431b-b9d1-0ceff2c18c33.png)

However, if those passed parameters were variables(`IDENT`s), then it would become hard since we have to chase their type through the file. And what happens if those are constants imported from other files, we have to traverse them to find the type.

**Comment by rnveach** [comment]
@stoyanK7 Yes this is a limitation of Checkstyle, but we should update the documentation to show this and this is why we cannot determine which is used/unused in this circumstance.

**Comment by rnveach** [comment]
Documentation update was merged
