### ISSUE TITLE
Push 'all' jar action is not working and not failing execution

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12694]
https://github.com/checkstyle/checkstyle/actions/runs/4054967613/jobs/6977468997#step:5:207

`RELEASE_ID=$(curl -s -X GET -H "Authorization: token $GITHUB_TOKEN" \` somthing like this is required
we need to echo variables and add auth token to curl.

lets recheck all curls that we use in actions to have token

**Comment by romani** [comment]
@stoyanK7 , please help to resovle this issue

**Comment by stoyanK7** [comment]
On it.

**Comment by stoyanK7** [comment]
I am not sure if the auth token has been an issue here. Sure, I will add it, but I can make that same call from my machine without providing a token and get the result.

```
 ~/Open Source/checkstyle  on issue/12694  ✔  at 16:45:01 
╰─ curl -s -X GET \
  https://api.github.com/repos/checkstyle/checkstyle/releases/tags/checkstyle-10.7.0           
{
  "url": "https://api.github.com/repos/checkstyle/checkstyle/releases/90836372",
  "assets_url": "https://api.github.com/repos/checkstyle/checkstyle/releases/90836372/assets",
  "upload_url": "https://uploads.github.com/repos/checkstyle/checkstyle/releases/90836372/assets{?name,label}",
...
```

The [official documentation](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-a-release-by-tag-name) does not state that `403` can be returned.

---
We got `404` which means the release does not exist or it has not been tagged. I am investigating further right now,

---
The job did not fail due to missing `--fail-with-body` option that we do not have due to https://github.com/checkstyle/checkstyle/issues/12451.

**Comment by stoyanK7** [comment]
@romani I suspect you mixed up the order of the deployment steps? Looking back at logs today it seems that you attempt to upload the `jar` before updating the github page. The job updating the github page [sets the tag of the release](https://github.com/checkstyle/checkstyle/actions/runs/4055066548/jobs/6977701523#step:3:185). The job uploading the jar finds the release by tag name and that is why we got `404`.

https://github.com/checkstyle/checkstyle/blob/3420f670ab01248ee54c8504c16fd25a3ffba492/.ci/upload-all-jar.sh#L26

| Action | Timestamp |
| :---:   | :---: |
| [Upload '-all' jar](https://github.com/checkstyle/checkstyle/actions/runs/4054967613/jobs/6977468997#step:5:207) | Tue, 31 Jan 2023 14:16:19 GMT   |
| [Update github page](https://github.com/checkstyle/checkstyle/actions/runs/4055066548/jobs/6977701523#step:3:188) | Tue, 31 Jan 2023 14:26:32 GMT   |

Can you confirm?
