### ISSUE TITLE
Kill survivng mutation in DefaultComesLastCheck.java

### ISSUE THREAD

**Issue by shubh220922** [checkstyle/checkstyle#12889]
Kill mutation:

https://github.com/checkstyle/checkstyle/blob/54df97c85d5fae09e38cda3c83781ac83b857930/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L30-L37

**Comment by shubh220922** [comment]
please approve

**Comment by shubh220922** [comment]
I'm on it.

**Comment by jxr98** [comment]
I will work on this issue.

**Comment by jxr98** [comment]
https://github.com/checkstyle/checkstyle/blob/2e99aca61f0537aa20ee52200c034dca35f33c8e/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheck.java#L215-L228
The pitest will fail after timeout or out of memory if the code((Line 223) is changed to `node = node;`. I think this suppressed mutation cannot be removed because it is kind of the halting problem to add code to check if the loop is infinite or not. Additionally, can't kill this mutation without redundant code. I don't think it is worth to add one more condition to `while` only for one mutation test.

**Comment by romani** [comment]
Pitest catching infinite loops and out of memory, this tool is well aware of damages it might do.
We need to kill mutation.

**Comment by nrmancuso** [comment]
> the code((Line 223) is changed to node = node;.

@jxr98 please explain how you concluded that this is what the code is mutated to. According to the [documentation](https://pitest.org/quickstart/mutators/#NON_VOID_METHOD_CALLS) for this mutator, it should be mutated to `node = null`; however this is an unstable mutator so we could be getting different results. If the code is mutated to `node = null`, then it looks like all the tests we have only cause us to loop one time in the code snippet you shared. Try to find a case where we must loop more than once.

**Comment by jxr98** [comment]
I thought this mutator just removed `getNextSibling`. Thanks for pointing this out.

**Comment by rnveach** [comment]
Fix was merged
