### ISSUE TITLE
Implement examples macro and xdoc template parser

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13134]
All xdoc examples are being moved to real java tests in https://github.com/checkstyle/checkstyle/issues/13100

The purpose of this issue is to gather requirements on how this parser should work and then implement it after an agreement is achieved.

- There is a proposal at https://github.com/checkstyle/checkstyle/issues/12155#issuecomment-1573143997 to use real XML configs.
- [ We should remove "package" in HTML version of this snippet.](https://github.com/checkstyle/checkstyle/pull/13112#discussion_r1211662594)

---
Edit: It was decided to use [Doxia Macros](https://maven.apache.org/doxia/macros/index.html) for that. Doxia already comes with a built in [`SnippetMacro`](https://maven.apache.org/doxia/macros/index.html#snippet-macro) that works in a similar way to what we want - use delimiter comments inside the target file. We will just build a similar one that fits our needs. Doxia documentation already explains how to make our own macro - https://maven.apache.org/doxia/developers/macros.html. Source code of snippet macro - https://github.com/apache/maven-doxia/blob/master/doxia-core/src/main/java/org/apache/maven/doxia/macro/snippet/SnippetMacro.java

Since we want to keep the xdoc files in the repository, a custom parser needs to be created to just execute the macros and keep the rest of the xdoc the same. This parser will work very similarly to the default xdoc one - https://github.com/apache/maven-doxia/blob/master/doxia-modules/doxia-module-xdoc/src/main/java/org/apache/maven/doxia/module/xdoc/XdocParser.java
Doxia documentation on how to build a custom macro - https://maven.apache.org/doxia/developers/modules.html.

**Comment by nrmancuso** [comment]
My vision would be to have some custom check and listener (comment aware of course) that does the following:
1. Grabs config comment and extracts xml
2. Transforms the AST based on some properties defined within our generation system
3. Ties into listener that grabs data we need

Listener would provide data we need into some object, maybe with a name like `JavaExample` (since we will have others).

Check properties can be like:
1. `preserveImports` - whether to keep imports in final AST
2. `preservePackageDeclaration` - whether to preserve package declaration in final AST
3. `outerAST` - takes an XPath expression, for edge cases where we want to show an example that is more focused than just the outer type, i.e. method level.

**Comment by romani** [comment]
in my mind:

run our parser(or maybe even simple line reader) to get line for outter type location - it is all after last import.
run line based reader of file to get XML content (I think we already do line based reader for Inputs).

AST based reader of Example file might be too slow, we do not need AST based detailization of file content. Examples are strict files by structure, freedom is not required.

But it is ok to user slow parser if we move this execution to "site" phase of mvn build. 

Even we see AST parser convenient, we will should use from it start-end lines and after that cut raw file by lines.
