### ISSUE TITLE
google_checks.xml file is not working giving Execution failed for task ':checkstyleMain'.

### ISSUE THREAD

**Issue by sheetalj2205** [checkstyle/checkstyle#13388]
**Describe what you expect in detail.**
I am using google_checks.xml file for my project, File is in config folder and the toolVersion of checkstyle build.gradle file is 8.32. 
<img width="1701" alt="Screen Shot 2023-07-11 at 6 00 55 PM" src="https://github.com/checkstyle/checkstyle/assets/64475191/94b1f81b-44ec-4184-b5b8-b535af14f143">

I need help with this, why this task is failing, I have also added suppressions.xml file in config folder.

**Comment by rnveach** [comment]
https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

If bug does not present itself in CLI, then the issue lies with gradle and how you are using it there. We do not maintain gradle plugin and have very limited knowledge of its workings.

The most I can do is ask that you provide us the full stack trace of the error and maybe we can point you in the right direction.

**Comment by nrmancuso** [comment]
We do not support gradle plugin, without details we cannot help. Let's close this issue.
