### ISSUE TITLE
New check to enable camelcase configure in the checkstyle.

### ISSUE THREAD

**Issue by AayushSaini101** [checkstyle/checkstyle#13894]
Currently, there is no check and property that enables camelcase configuration, and camelCase is widely used in the dev org while writing the identifiers, etc. 

The variable *iSstaticfinal* is not in the camel case, but the check style cannot handle it.
 ```
 final DetailAST modifiersAST =
            ast.findFirstToken(TokenTypes.MODIFIERS);
        final boolean iSstaticfinal =
            modifiersAST.findFirstToken(TokenTypes.LITERAL_STATIC) != null
                && modifiersAST.findFirstToken(TokenTypes.FINAL) != null
            || ScopeUtil.isInAnnotationBlock(ast)
            || ScopeUtil.isInInterfaceBlock(ast);
```

Output: 
<img width="2056" alt="Screenshot 2023-10-15 at 9 28 02 PM" src="https://github.com/checkstyle/checkstyle/assets/60972989/c32f1f50-cac8-43ba-a177-c3c55cdfe6ac">

**Comment by rnveach** [comment]
@AayushSaini101 https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

Your issue currently doesn't make any sense to me as nearly all our naming checks ( https://checkstyle.org/checks/naming/index.html ) allow you to configure using a custom regular expression, including camel case.

> iSstaticfinal 

If your issue is that it doesn't take into account the actual words to control casing on, then this becomes a complex issue, as now you have to take into account dictionaries which can be large, need to encompass many languages, and can quickly become out of date.

We have a GSoC idea for spellchecking at https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2023-Project-Ideas#project-name-spellcheck-of-identifiers-by-english-dictionary , and I would say this type of check would fall under it as you would be spellchecking on the words created from the camel casing.

**Comment by rnveach** [comment]
This is not an issue in our repo as we do have a spellchecker, and the area mentioned in the first post is spelled correctly.
https://github.com/checkstyle/checkstyle/blob/b1b25109068ae4aec1d7042ceb9756bc02118c42/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheck.java#L104

**Comment by AayushSaini101** [comment]
> @AayushSaini101 https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F
> 
> Your issue currently doesn't make any sense to me as nearly all our naming checks ( https://checkstyle.org/checks/naming/index.html ) allow you to configure using a custom regular expression, including camel case.
> 
> > iSstaticfinal
> 
> If your issue is that it doesn't take into account the actual words to control casing on, then this becomes a complex issue, as now you have to take into account dictionaries which can be large, need to encompass many languages, and can quickly become out of date.
> 
> We have a GSoC idea for spellchecking at https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2023-Project-Ideas#project-name-spellcheck-of-identifiers-by-english-dictionary , and I would say this type of check would fall under it as you would be spellchecking on the words created from the camel casing.

Thanks @rnveach @romani , I would like to start on this GSOC Project. I will first start with the spellcheck for the variables. Do I need to wait for the next year for GSOC? or can I start from onwards?

**Comment by romani** [comment]
Better to wait, and meanwhile fix several defects in Checks and finally try to implement some new Check.
To make sure you be ready for very complicated Check implementation, and you aware of how to do this and test it and how pass review.
