### ISSUE TITLE
Since version is determined incorrectly by property macros at returncount.xml.template

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13934]
Detected at https://github.com/checkstyle/checkstyle/pull/13932/files#r1368105661

Expected since is from setter, value should be 3.4.

Same problem is at https://github.com/checkstyle/checkstyle/pull/13971/files#r1385112133
For AtclauseOrder

**Comment by Rohanraj123** [comment]
I have made the changes regarding this issue. Should I make PR on this issue? @romani Sir

**Comment by relentless-pursuit** [comment]
When i changed the `@since` of the `format` propertyNmae to something random like `5.0`, but it was still drawing `@since` from the check i.e. `3.2`
```
    /**
     * Setter to specify method names to ignore.
     *
     * @param pattern a pattern.
     * @since 5.0
     */
    public void setFormat(Pattern pattern) {
        this.format = pattern;
    }
```

Some logs to set the context:
```
propertyName inside else-if: format
sinceVersion inside else-if: 3.2
```
And, the reason why the `@since 3.2` is tied to the propertyName which is `format` here is because of the following piece of code of `getSinceVersion` in `SiteUtil.java`:
```
 else if (SUPER_CLASS_PROPERTIES_JAVADOCS.containsKey(propertyName)
                || TOKENS.equals(propertyName)
                || JAVADOC_TOKENS.equals(propertyName)) {
                ....
}
```

And, the propertyName inside matches with propertyName of ReturnCountCheck.java i.e. format. 
Contents of SUPER_CLASS_PROPERTIES_JAVADOCS:
```
Key: charset
Key: AbstractHeaderCheck
Key: AbstractAccessControlNameCheck
Key: AbstractJavadocCheck
Key: applyToPackage
Key: violateExecutionOnNonTightHtml
**Key: format**
Key: javadocTokens
Key: applyToPublic
Key: tabWidth
Key: fileContents
Key: applyToPrivate
Key: AbstractNameCheck
Key: AbstractFileSetCheck
Key: fileExtensions
Key: headerFile
Key: AbstractParenPadCheck
Key: header
Key: applyToProtected
Key: option
```

Maybe, this requires some additional logic to detach `@since` of setter with `@since `of the check.

**Comment by Rohanraj123** [comment]
@relentless-pursuit Even in the getSinceVersion method in SiteUtil.java file returning the sinceversion it takes from javadoc that has been created. So why do not just change the value of since in returncount.xml and returncount.xml.template. Please letme know if i am wrong or i have wrong understanding. Looking for constructive feedbacks.

**Comment by relentless-pursuit** [comment]
@Rohanraj123 , 
If you change the version of setFromat in the below code:
 ```
   /**
     * Setter to specify method names to ignore.
     *
     * @param pattern a pattern.
     * @since 3.4
     */
    public void setFormat(Pattern pattern) {
        this.format = pattern;
    }
```
    
And, re-run the test cases, it will draw version `3.2` which is the version of the check. 

If you read the original issue attached above, while migrating, the version of the format changed from `3.4` (original) to `3.2`. The current issue to me is to revert back to original i.e. 3.4. And, not changing the version of the check itself.

**Comment by Rohanraj123** [comment]
> @Rohanraj123 , If you change the version of setFromat in the below code:
> 
> ```
>   /**
>     * Setter to specify method names to ignore.
>     *
>     * @param pattern a pattern.
>     * @since 3.4
>     */
>    public void setFormat(Pattern pattern) {
>        this.format = pattern;
>    }
> ```
> 
> And, re-run the test cases, it will draw version `3.2` which is the version of the check.
> 
> If you read the original issue attached above, while migrating, the version of the format changed from `3.4` (original) to `3.2`. The current issue to me is to revert back to original i.e. `3.4`. And, not changing the version of the check itself.

Ok thanks to give me better clearance @relentless-pursuit Sir

**Comment by romani** [comment]
We need to update code at https://github.com/checkstyle/checkstyle/blob/0322ba1be8489d1df373013efc9078de4d209eb4/src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java#L702

To keep this collection to be checked by class first, and then by property name to make sure we can find "format" only in specific Checks.

ReturnCount does not have parent class that has some specific properties
https://github.com/checkstyle/checkstyle/blob/0322ba1be8489d1df373013efc9078de4d209eb4/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheck.java#L101

**Comment by rnveach** [comment]
> We need to update code at SUPER_CLASS_PROPERTIES_JAVADOCS

This does not seem like a good "override", as not all properties will match the module's `since` version.

It sort of made sense to do this manually for tokens since the automated process I used to create these versions could not identify when there was customizable tokens or not. Since this is being automated, this will cause a wrong version to be displayed if a non-customizable token is now converted to be customizable.

**Comment by rnveach** [comment]
> else if (SUPER_CLASS_PROPERTIES_JAVADOCS.containsKey(propertyName) 

This code is wrong and needs to be fixed.

One of the values in the map is `EmptyForIteratorPadCheck` and `option`. `option` however, already has a javadoc with a `@since` so it is wrong that we are pulling the `@since` version from the class. It should be pulled from the setter.

https://github.com/checkstyle/checkstyle/blob/cf508bc96e87bf051094b1e7c787ccd10e420c54/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheck.java#L92

**Comment by romani** [comment]
issue is resolved
