### ISSUE TITLE
CustomImportOrder property 'customImportOrderRules' should be String[]

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#14216]
I have read check documentation: https://checkstyle.sourceforge.io/checks/imports/customimportorder.html#CustomImportOrder
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

Current check configuration uses `###` delimiter between import types. 
Example:
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="CustomImportOrder">
      <property name="customImportOrderRules"
        value="STATIC###STANDARD_JAVA_PACKAGE###THIRD_PARTY_PACKAGE"/>
    </module>
  </module>
</module>
```

This is not intuitive. The check should use a comma separated list ([String[]](https://checkstyle.sourceforge.io/property_types.html#String.5B.5D)) instead.
Example:
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="CustomImportOrder">
      <property name="customImportOrderRules"
        value="STATIC, STANDARD_JAVA_PACKAGE, THIRD_PARTY_PACKAGE"/>
    </module>
  </module>
</module>
```

We can initially make this a non-breaking change by simply overloading the `CustomImportOrderCheck#setCustomImportOrderRules` method like so: `public final void setCustomImportOrderRules(String ...s)` and deprecating the old method.

**Comment by rnveach** [comment]
Seeing it is the setter on the check used for our properties and is set via reflection via bean properties, I wouldn't think this would be a breaking change.

Also, I am not sure how bean properties behaves if we have 2 setter methods for one properties that is so similar. I think one would always take priority over the other. In this case it may be the alone `String` since it is the default with no extra conversion needed.

I am liking this route more than the custom override and special javadoc tag.

**Comment by nrmancuso** [comment]
@rnveach good thinking, we can take advantage of varargs parameter to make backwards compatible permanent change and just do something like:
```java
    public final void setCustomImportOrderRules(String... rules) {
        if (rules.length == 1 && !DEFAULT_CUSTOM_IMPORT_ORDER_RULES.equals(rules[0])) {
            for (String currentState : GROUP_SEPARATOR_PATTERN.split(rules[0])) {
                addRulesToList(currentState);
            }
            customOrderRules.add(NON_GROUP_RULE_GROUP);
        } else {
            Arrays.stream(rules).forEach(this::addRulesToList);
            customOrderRules.add(NON_GROUP_RULE_GROUP);
        }
    }

```

**Comment by romani** [comment]
Please keep in mind of https://checkstyle.sourceforge.io/checks/imports/customimportorder.html#Example12-config
`value="STATIC###SAME_PACKAGE(3)###THIRD_PARTY_PACKAGE###STANDARD_JAVA_PACKAGE"/>`

I hope it still can be a list. I don't remember what forced us to avoid list usage as a type. Most likely to allow future extensions to reuse `,` in `()` to define list of packages inside or whatever is required.

Now I do not see big future of this Check, but unfortunately this Check is part of Google style, breaking changes in it will be big pain for many users.
https://github.com/checkstyle/checkstyle/blob/13090c515ec207c88f41c8e8646460ff7de76f7f/src/main/resources/google_checks.xml#L275

Are we sure to expose this pain or migration/updates to public? Instead of eating it in our internal web site generation class.

**Comment by nrmancuso** [comment]
This issue has nothing to do with website generation. `###` delimited string is weird, and not consistent with other properties. There is no reason that I can find that we should not just have a comma separated list of rules. See https://github.com/checkstyle/checkstyle/issues/14216#issuecomment-1874207692 for a fully backwards compatible way to fix this.

**Comment by rnveach** [comment]
> Now I do not see big future of this Check, but unfortunately this Check is part of Google style, breaking changes in it will be big pain for many users.

IMO, either the check is part of our repo or its not. If we don't want this check, or think it is not worth examining things or doing proper fixes, then we should just remove it and be done with it. Otherwise, we should do our best to move it forward in a positive manner and ensure we don't make our user experience worse for it either with bugs or such. I am fine with breaking backwards compatibility to fix past mistakes as long as we don't make it a constant habit.

===

As for web site generation, other issue has atleast 2-3 other alternatives for moving that forward.

**Comment by romani** [comment]
>and ensure we don't make our user experience worse for it either with bugs or such.

Check works fine, but update to commas with require all all people in wold who use Google style or style based on it to update configuration.

**Comment by nrmancuso** [comment]
> > and ensure we don't make our user experience worse for it either with bugs or such.
> 
> Check works fine, but update to commas with require all all people in wold who use Google style or style based on it to update configuration.

No, this is not correct.

**Comment by rnveach** [comment]
@nrmancuso 's solution is backwards compatible, as seen by him not updating existing tests.

**Comment by rnveach** [comment]
I see no problems with this issue right now.

**Comment by romani** [comment]
I am ok too but how we will document this? Whole word configs are `###` based. People need abilities to modify what they see. Or ?

**Comment by rnveach** [comment]
Change is backwards compatible. Our whole repo is comma separated. We can just add some verbiage to documentation we also still support deprecated `###` comma-style separation.

**Comment by romani** [comment]
@nrmancuso, issue is approved please update doc somehow to let people knows what to do is they have `###`. But we can advocate to have list by default in all/most examples and in google_style.xml .
