### ISSUE TITLE
Add Check Support for Java 21 Pattern Matching for Switch Syntax: Indentation

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#14971]
child of #14961 
I have read check documentation: https://checkstyle.org/checks/misc/indentation.html#Indentation
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
PS D:\CS\test> cat src/Test.java                                                 
record Point(int x, int y) { }
record square(Point upperLeft, Point lowerRight) { }

public class Test {
    public void test() {
        Point p = new Point(1, 2);
        switch (p) {
            case Point(int x, int y)
            when x > 0 && y > 0 -> System.out.println(x + y); // violation
            case Point(int x, int y) -> System.out.println("error");
        }
    }
}
PS D:\CS\test> cat config.xml                                                    
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
 <module name="TreeWalker">
    <module name="Indentation">
    </module>
 </module>
</module>
PS D:\CS\test> java  -jar checkstyle-10.14.2-all.jar -c config.xml  src/Test.java
Starting audit...
[ERROR] D:\CS\test\src\Test.java:9:13: 'case' child has incorrect indentation level 12, expected level should be 16. [Indentation]
Audit done.
Checkstyle ends with 1 errors.
```
---

**Describe what you expect in detail.**

I consider this a false positive. I want no violation on `when`

---

**Comment by mahfouz72** [comment]
@nrmancuso @rnveach 
I consider the JEP to be a reliable source when it comes to this code's indentation. Do you know of any other resources that could help determine whether or not this indentation is appropriate?

Example from JEP

```
With this approach, we can rewrite the above code using guards:

// As of Java 21
static void testStringNew(String response) {
    switch (response) {
        case null -> { }
        case String s
        when s.equalsIgnoreCase("YES") -> {
            System.out.println("You got it");
        }
        case String s
        when s.equalsIgnoreCase("NO") -> {
            System.out.println("Shame");
        }
        case String s -> {
            System.out.println("Sorry?");
        }
    }
}
```

**Comment by rnveach** [comment]
Normally when we review indentation issues, we look at how Eclipse and IntelliJ handles autoformatting them.

> I consider this a false positive. I want no violation on when

To me, this violation looks valid but I am new to all this syntax.

> Do you know of any other resources that could help determine whether or not this indentation is appropriate?

Indentation is a complex check. It is also probably the most "broken" in our repo. You can see all indentation issues with https://github.com/checkstyle/checkstyle/issues?q=is%3Aopen+is%3Aissue+label%3Aindentation .

Step 1: all tokens need to be validated. We don't have to print violations on every line, but every line should have a required indentation which should be checked against. If a token isn't validated, then it's indentation isn't enforced and it is allowed to be anywhere. Example: https://github.com/checkstyle/checkstyle/issues/3133

One way to check this is to put every token on its own line, at the very oddest position (maybe more than one), and enable `forceStrictCondition`. This property says the line must be indented exactly to a specific position. Without it set, a line is allowed to be indented beyond it's position we say it should start at. Basically you can only verify Indentation by giving it really bizarre and incorrectly formatted inputs, unless you know the check well.

Some tokens can be validated already because we support line wrapping. `sealed` is seen like a modifier and I would think the `class` handler checks each modifier as part of a line wrap.

Step 2: Indentation should be consistent and make sense. Users don't like validation which is wrong or can't be satisfied. Example: https://github.com/checkstyle/checkstyle/issues/6166

What looks makes sense is subjective. This is why we look at current IDEs, and your analysis on best practices should try to come up with this.  We can support multiple "correct" positions for different people's behavior. So for example, 12 and 16 could be added as acceptable positions in this scenario if we decide.

**Comment by mahfouz72** [comment]
Intelliji autoformatting reformates `when` to be on col 20 so according to IntelliJ this is a valid violation

**Comment by nrmancuso** [comment]
`when` is line wrapping and should be indented further. I will approve this issue for test input, and if we discover something unusual there, then we can change this to bug.
