### ISSUE TITLE
Rethink algorithm on how we mark violations in Input files

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15643]
confusion is detected at https://github.com/checkstyle/checkstyle/pull/15327#issuecomment-2336704893

We need proposal on what should be improved.

**Comment by rnveach** [comment]
Please refrain from pinging me via PM or GH to ask for my opinion only to disregard it or potentially ignore our rule requiring two admin approvals for merging, especially when another admin has disapproved of the PR.

> We need proposal on what should be improved

I suggest starting with a review of project management practices. I have lost confidence in the process here. I find it distasteful that you block and stop progress on things when you disagree with them, but you are fine going over others disagreements as long it is what you want.

Due to these issues, I have stopped contributing changes to this project for some time now and will continue to do so. My involvement now is limited to trying to prevent the project’s code from declining, but I’m unsure how long that will be feasible.

======

I am closing this issue. If you believe this is a valid concern (as it wasn’t considered an issue when merging the PR), please open a new issue with your own perspective. Kindly do not use my previous comments, as they seem to have been undervalued.

**Comment by romani** [comment]
I tried to move bigger discussion outside of essential fixes.

For now I do not know how to improve matching code. There are definitely rooms to improve and we can do this now if somebody see a way to improve or we can do it when we run into problem and ti will be very clear there is gap.
