### ISSUE TITLE
JavadocParagraph: validation with comment inside P tag

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15732]
after merge of https://github.com/checkstyle/checkstyle/pull/15710#discussion_r1785971383

recheck that 
```
/**
 * Some Summary.
 *
 * <p><!-- comment is required --> extra space in paragraph after comment is violation</p>
 */
public class Test {
}
```

will be violation.
Add input like this

**Comment by Zopsss** [comment]
Tried fixing this issue at: https://github.com/checkstyle/checkstyle/pull/15686

commit in which fix was pushed: https://github.com/checkstyle/checkstyle/compare/88c23c4e17b959575de5fccbe349c1e7d06b312d..1042402e60a306559e7a2f263389b8ec7d91ddaa

Didn't send a new PR for this because the example you gave in the issue description was based on open-closed tag

**Comment by romani** [comment]
@Zopsss ,
we need to be sure it will also work in same way for code without closing P tag.

**Comment by Zopsss** [comment]
done https://github.com/checkstyle/checkstyle/compare/215e43d51d5c445be189b05f3be149573de5f993..973b2bf27158a066f6c6a73d3e6c9a8d524098e0

**Comment by romani** [comment]
Fixed by https://github.com/checkstyle/checkstyle/pull/15686
