### ISSUE TITLE
Make coverage 100% for all classes at package com.puppycrawl.tools.checkstyle.doclets

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2126]
There only one file to cover by UTs.

following line https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L872 should be removed.

**Comment by Vladlis** [comment]
I need help with this issue. The problem is that I cannot make method [start](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDoclet.java#L58) work on a correct input, such as [TokenTypes](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java).
Here is my [attempt](https://github.com/Vladlis/checkstyle/commit/e49cede838b323a84a1394e6d67780945812b9dc#diff-c96508ecf9888bd5c3590a913a858ebfR122) which fails due to [IllegalArgumentException](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDoclet.java#L72) because ```field.firstSentenceTags().length``` is always ```0```.
Please help me.
@os97673, it would be so kind, if you could take a look.

**Comment by romani** [comment]
@Vladlis , that doclet works fine on TokenTypes class when it is lauched by ANT, please find me in onlin for voice discussion.

**Comment by Vladlis** [comment]
Well, after the conversation with @romani I guess I will be able to tackle the issue :)

**Comment by romani** [comment]
Merged.
