### ISSUE TITLE
Exception message not informative enough for users on incorrect parent

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2186]
When running Checkstyle with the following config:    

``` xml
    <module name="Checker">
        <module name="TreeWalker">
            <module name="RegexpMultiline"/>
        </module>
    </module>
```

I get not very informative message:

```
cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of RegexpMultiline
```

I'd expect information that RegexpMultiline has parent `TreeWalker`, but should have `Checker` as parent.
##

**Comment by romani** [comment]
this issue might be related #898 .

**Comment by rnveach** [comment]
@romani Should new message be:
`cannot initialize module TreeWalker - TreeWalker is not allowed as a parent for RegexpMultiline and must have Checker as a parent`
If so, what should message be if parent is unknown because user used some custom class we don't recognize? Should it just default to the current message?

**Comment by romani** [comment]
Message is ok.

Yes, if unknown parent, lets use default message

**Comment by rnveach** [comment]
Message cannot be fully changed in [AutomaticBean](https://github.com/checkstyle/checkstyle/blob/292ad0ebf2d18e1d8131127d60b3fde99aa0adf0/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java#L264-L270) because to identify parent we need to know the child's type and to know the type we need an instance to work with.
If we want to continue with this change there, `AutomaticBean.setupChild` would have to be changed to try to instantiate the child first. If we are going this far, maybe we should instantiate the child before we even call `setupChild` and pass the instance along as all beans need to do this. To do this would require a new issue as it is an API change and would require CS 8.
`Checker` and `TreeWalker` messages can still be changed now.

**Comment by romani** [comment]
@rnveach ,

no, we do not need complication for such simple issue.
Is we can not goo message for user, we should stay with what we have and extend general wording:

`cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of RegexpMultiline. Please review 'Parent Module' section for this Check in web documentation if Checks is standard.`

**Comment by romani** [comment]
pre-assigned https://groups.google.com/forum/#!topic/checkstyle-devel/zFiXoW7k9Co

**Comment by nikshinde1996** [comment]
I am on it

**Comment by subkrish** [comment]
@rnveach Since @nikshinde1996 did not continue to work on this, I would like to take this issue over. I am on it.

**Comment by romani** [comment]
Fix is merged
