### ISSUE TITLE
IT : Google Style naming convention

### ISSUE THREAD

**Issue by altair2010** [checkstyle/checkstyle#2187]
Google use lower Camel case for varaible and member names (see 5.2.5 Non-constant field names
5.2.6 Parameter names, 5.2.7 Local variable names) but in rules you uses "^[a-z][a-z0-9][a-zA-Z0-9]*$" format insteed of ^[a-z][a-zA-Z0-9]*$

so xMargin or yPos will be a wrong parameter name

**Comment by romani** [comment]
please give a link to google opensource project who follow Google Style Guide and has code like you described. 

As far as I remember we did that intentionally after testing over Guava sources. 

Your format will allow prefixes to variables like "mFieldMember", "aFirstArgument"

**Comment by altair2010** [comment]
I'm agree with the intention to block mFieldMember and aFirstArgument or other Prefix/Hungarian notation.
But there's no regExp expression whith can reject Prefix/Hungarian notation.

With actual rules i can use msName (with "member string" prefix) but i can't use xPos or yPos for coordinate (nor x or y like in java.awt.geom.Point2D)

Sorry but i don't have opensource project.

**Comment by mkordas** [comment]
I agree with @altair2010 - right now it's not possible to declare variable `mBean`, which is perfectly fine name for bean visible via JMX.

**Comment by romani** [comment]
@altair2010 ,

> But there's no regExp expression whith can reject Prefix/Hungarian notation.

absolutely agree. But we use regexp instead of very complicated algorithm as it work in 95% cases. Rest of cases could be suppressed. Non of the Check have 100% correct validation on all sources in the word, exceptional cases always exists.

> With actual rules i can use msName (with "member string" prefix)

Checkstyle can only give a hint to user that name is not correct, we can not recheck that variable is named correctly. I do not know a tool which can do that. Good name it is even for most developers the most complicated task.
We restrict the most obvious patter from the past - "iValue" , "sName".
prefix size 2 is taken after testing on opensource code, and it raises minimal amount of false-positives, that could actually be renamed. 
It does not mean that such format will match too all.

> but i can't use xPos or yPos for coordinate (nor x or y like in java.awt.geom.Point2D)

yes this is one of cases where one letter become a term. You can put suppression or rename to posX , posY. 
You can update a regexp and exclude x and y from consideration.

One more potential option is extend a Check to have some "exclude" names from validation that become standard de facto in the project and can not be changed.
http://checkstyle.sourceforge.net/config_naming.html#Enhancements

> Sorry but i don't have opensource project.

you can share a chunk of code out of context and a bit obfuscate it. We need chunk, structure of code and we do not need complete code.

====================================

Do not expect that Google style will match you code completely (you might already notice a very unique demand in Google style for import ordering - it will not work work for you). 
In my practice each team have it own config. They might be very similar with others, but UI project and pure-library project will always have different set of Checks. Some Checks are designed for libraries and can not be applied to UI, example - MagicNumber.

**Comment by romani** [comment]
> right now it's not possible to declare variable mBean, which is perfectly fine name for bean visible via JMX.

please prove this by examples.

http://docs.oracle.com/javase/tutorial/jmx/mbeans/ here we most likely have example of human abbreviation term that passed to CamelCase naming convention incorrectly. Please see our Check - http://checkstyle.sourceforge.net/config_naming.html#AbbreviationAsWordInName
Old code in Java have a lot of abbreaviations  (I also created a lot of classes at the past) but it does not meant that it should continue. Users need to use suppressions on legacy code or refactor it to best practices. If nobody want to bother - disable a Check completely.

**Comment by mkordas** [comment]
Here are examples:
* **mBean** - on [Wikipedia](https://en.wikipedia.org/wiki/Java_Management_Extensions) it is official name for JMX managed bean, GitHub shows [hundreds of thousands of occurences](https://github.com/search?utf8=%E2%9C%93&q=mbean), name `beanM` doesn't make sense
* **xPath** - you woudn't name local variable holding some XPath like `pathX` or `xmlPathLanguage` - it must stay `xPath`. It has over [5 million occurences](https://github.com/search?utf8=%E2%9C%93&q=xpath&type=Repositories&ref=searchresults) on GitHub.

Other examples: `xStream`, `xQuery`.

**Comment by romani** [comment]
All these are words, new words of code vocabular. They need to be mbean , xpath .

If smb do not like to do this, they have to use suppressions

**Comment by mkordas** [comment]
@romani - thanks, sounds reasonable. Should we close this issue?

**Comment by romani** [comment]
more examples of how abbreviation become a word - https://en.wikipedia.org/wiki/Acronym

the best known for software engineers are XML and URL - they have to appear in code as a word url,Url,xml,Xml

to help users to enforce no abbreviations there is - http://checkstyle.sourceforge.net/config_naming.html#AbbreviationAsWordInName 

One more prove (see table):
https://google.github.io/styleguide/javaguide.html#s5.3-camel-case

---------

I am closing this issue, but if somebody find more ideas/evidences why this(format) should be changed, please share them there.
