### ISSUE TITLE
Allow finishProcessing for Checks

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2221]
I am trying to write a TreeWalker check that must do some final processing, and error reporting, after all the files have been processed.
My check is: All non-abstract classes must be final if they are not inherited.
I am implementing it by collecting all the classes, and their parents from the 'extends' clause, into 2 lists and finding which classes aren't in the other list.

Since this requires all files to be processed first, my only choices of overriding methods is "destroy" and "finishProcessing".
"destroy" doesn't report any messages I print out using "log", and Check doesn't implement the "finishProcessing" method.

Going by the source: https://github.com/checkstyle/checkstyle/blob/2b4a02d2c8a498a8a1ee38e9396426209fa65fad/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L275
Errors are only reported after "process", and each "FileSetCheck" must implement its own reporting code if it wants to report errors in the "finishProcessing" method. Example: https://github.com/checkstyle/checkstyle/blob/c899af31c112c07ea1244f6bbe2c5c6c56818ae5/src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java#L267

A TreeWalker check can't access "getMessageDispatcher", so it can't implement its own error reporting in the "destroy" method like TranslationCheck does.
My only choices right now, is to make a second "FileSetCheck" that reports the errors my "TreeWalker" check finds, or to make only a "FileSetCheck" that redoes the java parsing that TreeWalker does for me.

It would make things easier if Check implemented the "finishProcessing" method, and allowed us to report errors after all the files are finished.
##

**Comment by rnveach** [comment]
Here is what I have done in my own fork to implement this.

The overall changes to CS' base files: https://github.com/rnveach/checkstyle/commit/548a5193ac58e97cac724ea7e2c6754f6cad5542
My check that uses the above changes: https://github.com/rnveach/checkstyle/blob/159b459b8790900f049d9a61ed445f218d601764/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalClassCheck.java#L98

**Comment by rnveach** [comment]
> > You are only considering FilesetChecks while I am including AbstractChecks

> ok , let not mix problems, lets resolve it for FilesetChecks here. Caching for java checks is another long discussion.

As referenced in the issue above, allowing `AbstractCheck` to call `finishProcessing` would cause issues with the cache if any new checks needed multiple files to process violations like `TranslationCheck`. The check I mentioned above and referenced as `FinalClassCheck` is an example of this.

The rest is pulled in conversations from the issue above as we are splitting the issues apart.

-------

**by rnveach:**

To fix this, I think we should have the checks control the cache more. By default, checks should follow the current behavior and skip the file if it is in the cache. More in-depth checks like TranslationCheck should be able to override it and force the utility to process cached files if it needs them.

For hardcore checks that need every file and AST, we might want to consider:
allow other checks to add their own, custom information to a cache through a new API.

----

**by romani:**

> allow other checks to add their own, custom information to a cache through a new API.

too much ...

We previously always thought about checkstyle as single file validator. But TranslationCheck is not like this even some custom check could be multi-file by design.
What if we just split Checks by annotation who is affected by cache and who is not (@NoCache).
Checkstyle will do second scan of files and run that set of Checks without cache at all.
It is better to sacrifice that limited set of checks rather than do hacks in caching.

----

**by rnveach:**

> Checkstyle will do second scan of files and run that set of Checks without cache at all.

If we don't keep the files and their AST tree in memory for the second run, you are going to really kill performance by reloading/reparsing all those files. To give an example, my laptop takes 2 minutes to run checkstyle against itself, which is already annoying. If we reloaded all files, that will double to 4 minutes even if only 1 check wants them reloaded.

> What if we just split Checks by annotation who is affected by cache and who is not (`@NoCache`).

having the annotation blindly ignore all files in the cache would definitely defeat the purpose of the cache and you would not see any speed improvements with the cache and the check. The slowest part of Checkstyle is loading and parsing the Java files, not running the logic of a check. I believe the purpose of the cache is to improve speed while giving the same reporting standards. Skipping processing/parsing Java files is the only way to get this improvement.
When I was originally suggesting providing checks a way to override the cache, it was on a verify first basis, not an all-files-ignore-cache.

------

**by romani:**

> having the annotation blindly ignore all files in the cache would definitely defeat the purpose of the cache and you would not see any speed improvements

yes, but it is better than false-positives and incorrect work at all. If user need run heavy Check , he will wait to get reliable result.

> The slowest part of Checkstyle is loading and parsing the Java files

yes, and if we want optimize this we could to serialize AST tree for each file, to boost performance of heavy Checks. But we do not have such Checks for now, cache will be big. We could make it when it become required for us.

> When I was originally suggesting providing checks a way to override the cache

Checks can do as much caches as they want. Cache of Checker should not be affected by any Check activity.

> so not all files need to be reloaded then they would get around this issue of needing to invalidate the entire cache.

should be resolved by second launch of checkstyle with different configuration (filters and extension filters).

> If we just communicate between the check and the cache more, we can acquire an equilibrium.

Check is pure algorithm, that eventually become stateless to be ready to run in MT mode. Cache is common for all, certain Check should not have access to it.

-----

end of referenced issue and copied talks

**Comment by rnveach** [comment]
@romani 
> Check is pure algorithm, that eventually become stateless to be ready to run in MT mode

Since we are splitting things up, we probably should not include multi-threaded mode in our discussions as that changes more than just this cache issue and depends solely on how we will actually achieve multi-threaded status. This ok?
Even with MT, we may still have checks that can't be completely stateless just like `TranslationCheck` and `ActualFinalClass`.

> if we want optimize this we could to serialize AST tree for each file

I thought about this before as a work around and I am against putting the tree to any file cache. Each Tree will always be around +/- 50x the size of the file which will be huge. If check really needs full tree in cache for a speed up, let the check do it itself with its own cache. I don't see this being needed for any normal checks.

> > so not all files need to be reloaded then they would get around this issue of needing to invalidate the entire cache.
> should be resolved by second launch of checkstyle with different configuration (filters and extension filters).

I'm not sure what you are talking about here. I wasn't talking about changing the configuration and erasing the cache. My original statement was basically `let the check interact with the cache more and not do a blind invalidate whole cache with no-cache-mode FileSet and reload every file`.

> Cache of Checker should not be affected by any Check activity.
> Cache is common for all, certain Check should not have access to it.

I'm not saying check should have complete control of the cache, I am saying that checks should have more say in how the cache operates and if it should skip a file or not.
Right now the main problem is `Checker` will skip files in the cache and not tell any of the checks about this. This is the main issue with the `TranslationCheck` problem, it thinks the files don't exist instead of just being skipped by the cache. Some checks will need all files, most won't.

I propose we use this as the fix to the cache. This is my idea:
1) `FileSetCheck` implements new method `boolean canSkipCachedFile(File file)`.
2) `TreeWalker` chains this method to every check. If one method returns `false`, `TreeWalker` returns `false`, otherwise it returns `true`.
3) Default checks and filesets will return `true`. `TranslationCheck` returns `true` and calls `processFiltered` to add the file for processing later. It loads the files personally in `getTranslationKeys`, so it can get away with telling `Checker` it doesn't need the files from it.
4) `Checker` calls this new method after `cache.isInCache` returns only `true`. If the new method returns `true` then the file is completely skipped. If the new method returns `false` then `Checker` proceeds as if the file wasn't in the cache at all.

That would be all the changes required in Checkstyle and we won't have to do extra processing or hold extra memory for cache and non-cache filesets/checks. It handles `FileSets` and `Checks` the same, no one is given special privileges or isolated executions.

As of right now, ActualFinalClass` needs every file to report proper violations. So how will `ActualFinalClass` do its work properly with the above changes and not force every cached file to be ignored?
1) It will maintain its own cache of just the variable `inheritedClasses` for each file. This will be alot smaller than the AST tree.
2) `canSkipCachedFile` will return `true` if it can pull that file's cache from the check's personal stash into the runtime of `inheritedClasses`. If it can't, it will return `false` and the file must be processed.
3) `destroy` or `finishProcessing` would then save the check's personal cache somewhere for the next run.

So we leave it up to the check to tell us how it wants to handle caching. We don't keep the check in the dark, but have more informed conversations with it. `This file is cached and we are skipping it, are you ok with that?` `We are erasing the checkstyle cache for some reason, you should do what you need to do because of this action`.
Most checks won't care about these conversations, but the more detailed checks will. It will be up to the check creator to be aware of the cache and how he should handle if it is encountered.

**Comment by romani** [comment]
> I am trying to write a TreeWalker check that must do some final processing, and error reporting, after all the files have been processed.

previously I tell people that it is not possible by design as Checkstyle is single file validation tool.
Hight activity in project and resurrection of TranslationCheck now make me think about it....

> All non-abstract classes must be final if they are not inherited.

very custom Check

> "destroy" doesn't report any messages I print out using "log", and Check doesn't implement the "finishProcessing" method.

destroy should be used only de-allocate resources.
finishProcessing - we need to add it to TreeWalker and AbstractCheck with empty implementation.
It is reasonable to let Java Checks to have ability to do smth at the end of all java files review.

> in the "destroy" method like TranslationCheck does.

TranslationCheck uses hack way to report violation ..... it should not be used as good example.

> It would make things easier if Check implemented the "finishProcessing" method, and allowed us to report errors after all the files are finished.

yes, I am agree.

---------------------------

Your Check idea should run without cache always, your check is heavy and multi-file checks , it is not in design of Checkstyle to do validation like this.
We could give to users ability to do such no-matter what , but all performance issues should be on users resposibility. No changes in design for cache control from Check. It will looks like hack and serve minimal amount of cases.
Checkstyle could give ability to group all such checks (no-cache) and run them separately. But what could be better is to force user to have two configs, one for Checks with cache usage and one is not.

Such heavy checks is a disaster for IDE integrations. Checkstyle plugin will kill IDE performance on save operation to re-parse all files. User need to be clearly aware of what he is doing. Such check make sense mostly for CIs.

**Comment by romani** [comment]
> how we will actually achieve multi-threaded status. This ok?

yes, MT is unrelated. But general Check should be stupid listener of visitToken and be pure algorithm in most case. If logic is complicated and does not satisfy already configured Checker, create a new Checker and custom Check and do whatever user want.

> I don't see this being needed for any normal checks.

I do not know reason too make it, but if smth will come with such request tomorrow, he will need to make its own Check and all that logic in his custom FilesetCheck.

> let the check interact with the cache more and not do a blind invalidate whole cache with no-cache-mode FileSet and reload every file

Check is not controlling cache, Check is not controlling set of files, order of files, even location of files, .... .
It is controlled by Checker (cache, extensions), it is nonsense to put in TranslationCheck to Checker that that filters by extension "*.java", kind of the same problem as with your Check. TranslationCheck can not force Cheker to put "*.properties" extension to filtering silently.

> I'm not saying check should have complete control of the cache, I am saying that checks should have more say in how the cache operates and if it should skip a file or not

it is kind of the same. Look at my example with TranslationCheck on Checker with only "*.java" filter.

> Right now the main problem is Checker will skip files in the cache and not tell any of the checks about this. 

user configured top level element in certain way, all Checks bellow follow that configuration.
User need to reconfigure Checker, or use another Checker that will do what TranslationCheck is expecting.

> I propose we use this as the fix to the cache.

such approach will kill IDEs if such Check come up set of Checks to execute.  I even think that grouping(by annotation) Checks is also bad idea as it will damage IDEs seriously. For user it will be hard to understand why it is happening like this. Multi-file Check need to reject to work under Checker that have cache.

> As of right now, ActualFinalClass needs every file to report proper violations.

All he need to stay simple and demand Checker without cache.

>Most checks won't care about these conversations, but the more detailed checks will. It will be up to the check creator to be aware of the cache and how he should handle if it is encountered.

They also need to be aware of usage in IDE, where validation is running is not by request (as in cli, maven, ant, ......., any CIs) but by "Cntrl+S" or any other IDE action. Even seconds in delay will make user furious.

**Comment by rnveach** [comment]
> such approach will kill IDEs if such Check come up set of Checks to execute.

Can you explain why the proposal will hurt IDEs? IDEs already use `Checker` and the cache and all I am planning is to add more logic inside `Checker` for the cache. If user wants to use this type of check, then there is no way around it and they should be warned, but we can help ease the pain of its performance.

> Even seconds in delay will make user furious.

Which is what my proposal will prevent as high usage checks will be able to work with the cache and reduce their runtime. Can you explain how my proposal will make performance worse when you are suggesting users shouldn't use the cache for these checks? With my proposal, runtime will only be the same as non-cache in first run, and always faster, or instant, every future run until the cache is reset, which should be rare.

>  But what could be better is to force user to have two configs, one for Checks with cache usage and one is not.

Even with separate configurations, or with `NoCache` annotation, this will not work. One will run with cache and the other without. In the end it will be either at best the same runtime as one configuration without cache or at worse double the runtime. Each configuration is a separate run, and that means reloading and reparsing the Java files.

> Checkstyle plugin will kill IDE performance on save operation to re-parse all files.

Your contradicting yourself here. You want to force users to use non cache run, but you don't want to re-parse all files. My proposal is directly making sure not all files need to be re-parsed if they don't need to be, reducing overhead on the IDE for these checks.

> Check is not controlling cache
> TranslationCheck can not force Checker to put ".properties" extension to filtering silently.

I am talking about guiding, not controlling. I will not be giving checks the cache instance so it can't manipulate anything. The check will not force other filesets/checks to change their behavior. It is not the same as having one check force `properties` only extensions to Checker. A closer and more accurate analogy would be to `BeforeExecutionFileFilters`, in that it is telling Checker which files don't need to be processed.

> Check is not controlling set of files, order of files, even location of files, .... .
> TranslationCheck can not force Checker to put ".properties" extension to filtering silently.

FileSets control the extension of the files passed to it and its children. FileFilters will control what files other checks receive. Suppressions controls what violations other checks print out, which to the user looks like hiding checks or hiding files. Each one modifies and 'controls' how other parts of Checker work. I don't see how my proposal is any different.
What I am proposing isn't modifying the configuration at all nor will it affect how other checks operate. There is nothing in the configuration file for the cache that says how it should operate. It should be understood that if user enables cache, checks will alter their behavior to work with the cache to not cause issues.

> all performance issues should be on users responsibility

For choosing those checks, and on the creators of the check on how they write them. So why can't we give them the tools to take measures to improve performance and work with the cache? The proposal by itself won't hurt performance, only if a custom check doesn't make full use of it when it could.

> All he need to stay simple and demand Checker without cache.

I wouldn't be here if I wanted simple. I am asking for speed of caching over simplicity of writing the Check.

-----

I think we are reaching an impasse with me trying to change your mind.
I assume you are leaning to somehow force these type of checks to not use the cache, like throwing an exception in `finishProcessing` if they call `log` when the cache is on? Are we going to do the same to FileSets?

**Comment by romani** [comment]
> Errors are only reported after "process", and each "FileSetCheck" must implement its own reporting code if it wants to report errors in the "finishProcessing" method


Checkstyle is single-file-validation tool now. All attempts to do smth out of this contract is a HACK and responsibility of Check author.
Yes, we have TranslationCheck that was recently restored from non-working state and it is my bad that I missed that misconception in its design.




Cache was designed for single-file-validation mode - and it works fine(except for few bugs), as designed.


Cache is like other prevalidation filters we have:
By user who give us certain set of files (even it is not complete set of file, misconfiguration, checkstyle have to follow and do his job)
By file extension in Checker  “fileExtensions” - http://checkstyle.sourceforge.net/config.html#Checker
By BeforeExecutionFileFilters - user defined exclusions for all Checks below.


We even have filtering by extension in FileSetChecks/TreeWalker “fileExtensions” -  http://checkstyle.sourceforge.net/config.html#TreeWalker


If file is passed filtering on top level(Checker) - Check just follow it, Check is called.


------------------------


> More in-depth checks like TranslationCheck should be able to override it and force the utility to process cached files if it needs them.


I pretty sure IDE plugin launch checkstyle on single file only most of the time (as user press cntl+s only for one file). So cache is most likely not used, as we have as target one file and we know it is changed. Cache is useful on whole project rebuild(ide relaunch, ….) time.
So if check can give guidance on what interested and what is not … How it can decide ? there is no order in what files will pass to validation. If Check make a decision based on changed files that it need more files ….. But required files might already passed by file traverser.
Global cache usage in multi-file-validation is just inappropriate , but could be useful in very specific cases. But we have to make general workflow in library.


Multi-file-validation , especially java-multi-file-validation is time consuming as logic might require caching all sources and do super smart validation when all files are parserd.
Fortunately TranslationCheck use only property files. Unfortunately your Check requires AST trees. Yes, you check is using so little from AST tree so you think that separate execution is not appropriate and any changes to ease your problem will help. Yes, help for you only as you implementing inner cache.


Mutil-file-validation is heavy and could be very heavy by user request/checks.


As we are going to implement NEW mode - multi-file-validation. It should not affect single file validation mode by design and by performance.


We can put AST trees to in-memory cache to ease execution on next phase after single file execution, I would rather postpone this as far as possible, but potentially it is doable. User give us complicated task, give us memory - we do a job.


If you look at multi-file-validation as a general task (not specific to your Check), there is no room for cache , as any changes in any file could required reconsideration of all other files.
Example: new Check - verify that all properties at resource file are in use in java files. Changes in property file require validation of all java files from scratch.


In general there is no room for cache, but in specific requirements Check could be as smart of TreeWalker and have its own cache, and do parsing of java file by RegExp to flag item to reparsing by grammar parser or skip file. Or even further ….. Keep your own cache with paths to all files and just wait for call …. Ones you called, analyse all you got and then reparse files that you have in your cache(if you cache have path to files). :) No limitations :) .




> 3) Default checks and filesets will return true. TranslationCheck returns true (“boolean canSkipCachedFile(File file)”) and calls processFiltered to add the file for processing later. It loads the files personally in getTranslationKeys, so it can get away with telling Checker it doesn't need the files from it.




If Check is skippping file, it will not receive “process”/”processFiltered” on it at all. I do not understand this point. Or smth is missed or I miss smth.




> As of right now, ActualFinalClass needs every file to report proper violations. 


You adjusting whole checkstyle you requirements of your Check. It is unfare. Se my comments above.


> So we leave it up to the check to tell us how it wants to handle caching.


No, Check is just a listener of what is configured at above modules. No decision, all decisions only about violations.


> Most checks won't care about these conversations, but the more detailed checks will.


All checks that will care about this method , most likely will have own cache :), bad smell …..


> Can you explain how my proposal will make performance worse when you are suggesting users shouldn't use the cache for these checks?


I just do not like implementation. I still think it is a HACK for very specific validation cases.




>  You are also mixing my proposal for the changes in CS with the check I gave as my example.


Yes, it is very long , and complicated discussion, if that answer does not work, we need to change different model of communication.


>  So why can't we give them the tools to take measures to improve performance and work with the cache?


Even you will work fine , it is damage for design.




> I think we are reaching an impasse with me trying to change your mind.


Yes, I am recalling all my proposals but do not give you green light to implement this hack for checkstyle.
We need to make general multi-file processing mode.


> I assume you are leaning to somehow force these type of checks to not use the cache, like throwing an exception in finishProcessing if they call log when the cache is on?


finishProcessing is only reasonable for multi-file validations. I do not want this method to appear at all in existing Checks. There should be separate interface probably or….. But it should be clear by design that Check is multi-file or not.


---------------------------------------------

if you have any further long discussions plans , lets skip model of discussion to google doc or chat or .... . It is already disaster to read  this thread of ideas and mixture of problems.

**Comment by rnveach** [comment]
This is closed in support of #3540 because request is directly connected to multi-file validation.
