### ISSUE TITLE
Usage of all modules in chekstyle_checks.xml

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2268]
base on #819 and #2261 .

We need to extend UT that check that all Checks are present in checkstyle_checks.xml to let it validate that all modules(Filters and AuditListeners, .... ) are used in our own config. 
Documentation should be updated to provide link from example section to that configuration.

Usage of some modules (most likely some filters) will be artificial , need to be discussed with before.

Example: FileContentsHolder is not present in checkstyle_checks.xml file.

**Comment by MEZk** [comment]
@romani 
We can use [getCheckstyleModules](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/AllChecksTest.java#L215) to get all checkstyle modules classes or just [getCheckstyleChecks](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/AllChecksTest.java#L188) to get checkstyle checks classe only. 

The problem is that we do not use all checkstyle modules in our checkstyle_checks.xml.

**Comment by rnveach** [comment]
@romani I am working on this.

getCheckstyleModules/getCheckstyleChecks will not pickup FileContentsHolder/SuppressWarningsHolder because they call "isCheckstyleNonAbstractCheck" and it requires the class name to end with "Check".
https://github.com/checkstyle/checkstyle/blob/3a2cb4d787e3c626bb0e2e02915cc1c37deb9d0b/src/test/java/com/puppycrawl/tools/checkstyle/AllChecksTest.java#L246

Should we make an override or will this affect other areas these checks shouldn't appear in and just hardcode the missing checks?

**Comment by MEZk** [comment]
@rnveach 
SuppressWarningsHolder  will be picked.
See https://github.com/checkstyle/checkstyle/blob/3a2cb4d787e3c626bb0e2e02915cc1c37deb9d0b/src/test/java/com/puppycrawl/tools/checkstyle/AllChecksTest.java#L260

Just add "FileContentsHolder" into isCheckstyleModule. 

I used reflection to find the subclasses of Check class and filter the subclasses (pick only those classes which end with "Check" and do not contain "Input"), because some UTs or test input files extend Check and also can be picked.

**Comment by rnveach** [comment]
@romani I believe this issue can be closed now.

**Comment by romani** [comment]
Done, released in 6.12
