### ISSUE TITLE
Checkstyle internal exceptions lack contextual information

### ISSUE THREAD

**Issue by lkoe** [checkstyle/checkstyle#2285]
Referencing bug #2284 this seems to indicate more general issue.

The "new" error handling in Checkstyle (bubble exceptions up to the caller) is not yet ideal.
Although the stacktrace is now available in eclipses error log, there is no contextual information on the exception, e.g. file (and possibly AST location).

This makes it very hard currently to track down the source file and location which caused the internal exception.

Checkstyle should possible catch all unhandled exception first (e.g. at TreeWalker/Checker level) and rethrow as a new CheckstyleException(?) adding the needed additional info.

This way both the full stacktrace as well as the source location can be available for troubleshooting.

**Comment by romani** [comment]
> (and possibly AST location)

we will not return this as Checker and Treewalker do not know what AST was under validation in Check. AST token that Treewalker give to Check is only starting point of most up-and-down traversing of AST tree that Check do.

Filename is vital information, should be provided.

@MEZk , all static analysis tools will scream on you attempt to catch Throwable - they need to be suppressed with a link to this issue as a reason. We need to catch Throwable because we has to brake a rule no matter what, and not all code in this world respect difference between Error and Exception, see real-life experience http://roman-ivanov.blogspot.com/2015/03/catch-exception-or-catch-throwable-when.html

**Comment by romani** [comment]
fix is merged.

@lkoe , please take a look.

**Comment by lkoe** [comment]
Thanks guys, looks good
