### ISSUE TITLE
Refactor Comments AST Test

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2396]
We have one test file for building an entire AST tree from scratch to verify it matches an input file.
https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/grammars/comments/CommentsTest.java#L85

I recently had the joy of understanding the flow and where new code fits in for updating it for a simple package name change.

Even if you look at my changes in the diff,
https://github.com/checkstyle/checkstyle/commit/df28ab043954d0d4da8b1999ea97d95ccffe8c21#diff-ec0a7089eddbc170ebbc07b12d3095d5R93
You can not easily understand why my changes were made without looking at the original java file. It is even harder to ascertain how valid the changes are. Yes the tests pass, but it is easy to make mistakes, have them go unnoticed, and still have a valid tree. We are also assuming there are no hidden issues with the antlr tree. The raw tree is not even made in line/column order, so you have to jump around to grasp the full picture.

There is a reason we let antlr control the grammar in the normal AST building, it is not easy to read and maintain by a human. The downside is we still need to verify its structure somehow against future changes.

I propose the following change:
Instead of building the raw AST tree in code, why don't we make a "printTree" utility method that will output antlr's AST tree in a text format, with all the necessary values to compare. We then save this as another input file with the "Ast.txt" suffix, and use this to then compare to antlr's generated tree.
Example Text Tree output:
````
+-- "CLASS_DEF" (CLASS_DEF) Line 3 Column 6
     +-- "MODIFIERS" (MODIFIERS) Line 3 Column 6
          +-- Text "/*" (BLOCK_COMMENT_BEGIN) Line 1 Column 49
               +-- Text "12" (COMMENT_CONTENT) Line 1 Column 51
               +-- Text "*/" (BLOCK_COMMENT_END) Line 1 Column 52
````

The benefits are:
1) We don't have to create complex tree's manually for testing, but still validate the tree structure.
2) Updates will be easier to read and understand.
3) We can now generate more tree compares instantly with this utility with the assumption that the current tree structures are valid and any future changes need review. Outside of "CommentsTest", I couldn't find any other tests like it.

**Comment by romani** [comment]
@baratali , please share your thoughts

**Comment by rnveach** [comment]
@romani There has been no response.
Since we are working on a similar issue , we could implement this once issue #2638 is finished.

**Comment by trial13365** [comment]
Sorry for not answerring.
I agree with @rnveach. That would improve readability of the unit test. All you need to compare AST nodes are type, line number, column number and text.
There may be a problem with OS specific line separator in comment's text, because CommentsTest uses ``System.getProperty("line.separator")`` while building trees. We can simply replace all ``\n`` by OS line separator after reading AST from txt file.
By the way, as I know DetailAST's text might be null, so printTree should distinguish null value and "null" string.

**Comment by baratali** [comment]
Sorry for not answerring.
I agree with @rnveach. That would improve readability of the unit test. All you need to compare AST nodes are type, line number, column number and text.
There may be a problem with OS specific line separator in comment's text, because CommentsTest uses ``System.getProperty("line.separator")`` while building trees. We can simply replace all ``\n`` by OS line separator after reading AST from txt file.
By the way, as I know DetailAST's text might be null, so printTree should distinguish null value and "null" string.

**Comment by romani** [comment]
if all agree - lets do this, issue is approved.

**Comment by rnveach** [comment]
Per romani, this depends on #408 for using the `AstTreeStringPrinter` to print out comments.
As it is currently is written, comments are not generated by the tree walker and hence don't appear in the print results.

**Comment by romani** [comment]
after discussion with @baratali , he is planning to send PR to show comments nodes as fist PR of update by new option.

```
Options:
--tree - the same as '-t', AST tree without comments
--tree-comment - AST tree with comments
--tree-javadoc - AST tree with comments and Javadoc tree 
--javadoc-tree - AST tree for Javadoc comments (no java AST)

Example:
 jar ..... --javadoc-tree myfile.javadoc
```

The same options should be in UI in main menu or in context menu.

**Comment by rnveach** [comment]
Thanks to @baratali 's latest commit, I have enough to work on this issue now.

**Comment by romani** [comment]
fixes are merged.
