### ISSUE TITLE
UTs for Xdoc validation of package subsection 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2442]
Raised by @rnveach ,

https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_annotation.xml#L604
This is the 'package' section for 'AnnotationLocation'. It says "com.puppycrawl.tools.checkstyle.checks" but the check is located in "com.puppycrawl.tools.checkstyle.checks.annotation". The display should always be the check's package location, right?

So we need UT to validate "package" subsection.

**Comment by rnveach** [comment]
this and 2443 are about the same in terms this is all about missing check information from the xdocs.
And there is more.

For example:
We tell the users about 'allowNewlineParagraph' in 'JavadocParagraphCheck'. https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_javadoc.xml#L1275
But we don't document it as a property. https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_javadoc.xml#L1255

https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_filters.xml#L24
SeverityMatchFilter has no "Examples" section.

https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_misc.xml#L1560
FileContentsHolder's parent should be TreeWalker since it has to go inside the TreeWalker module.

**Comment by rnveach** [comment]
I am working on this.

**Comment by romani** [comment]
Only one code violation remains from CS. if you have any thoughts on how to fix it, feel free to say.

    XDocsPagesTest.java:342:5: error: Cyclomatic Complexity is 13 (max allowed is 10).

**Comment by romani** [comment]
release as 6.12.1
