### ISSUE TITLE
remove xdoc link reliance on master

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2519]
Right now the links in XDOCs point straight to master.
Example: https://github.com/checkstyle/checkstyle/blob/c10d886b139e2d92cca65a14b9b63fb126ea3d1c/src/xdocs/config_javadoc.xml#L989
````
https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L268
````

This creates issues after a release when the file keeps getting updated and causes the links to point to the wrong location.

**Comment by mkordas** [comment]
In my opinion we shouldn't have any links to hardcoded line numbers. They are too hard in maintenance. Instead the links should look similar to `checkstyle_checks.xml#NonEmptyAtclauseDescription` instead of `checkstyle_checks.xml#L268`. First one in not possible on GitHub, but we could host copy of the `checkstyle_checks.xml` at our page.

If we want to stick to GitHub here's working solution: https://github.com/search?q=NonEmptyAtclauseDescription+path%3Aconfig+repo%3Acheckstyle%2Fcheckstyle
Just replace `NonEmptyAtclauseDescription` with proper check name.

**Comment by romani** [comment]
I like this idea with search links.

**Comment by rnveach** [comment]
@romani 
Let me know if we are going to go with changing the links to searches.
This will change #2517 to be a simpler validation. And we will expand this to sun and google configs, correct?

**Comment by romani** [comment]
> Let me know if we are going to go with changing the links to searches.

I do not see any drawbacks with such approach. I am ok with it.

>And we will expand this to sun and google configs, correct?

yes, all "Example of usage" and http://checkstyle.sourceforge.net/google_style.html should be affected.

**Comment by romani** [comment]
release as 6.12.1
