### ISSUE TITLE
OverloadMethodsDeclarationOrder reports an error when static and instance method not together: opportunity for improvement?

### ISSUE THREAD

**Issue by supercobra** [checkstyle/checkstyle#2652]
It seems `Checkstyle OverloadMethodsDeclarationOrder ` likes a static and an instance method with same name together (since they are overload of each other) and therefore generate an error if not. However this makes grouping methods by group `static` v.s. not impossible. This could be an opportunity to create an option to do this making Checkstyle more flexible.  

    public class Item {
        public String toString() {
            return "";
        }

        public String amethod() {
            return "something";
        }

        public static String toString(String str) {
            return str;
        }
}

       Item.java:8: error: Overload methods should not be split. Previous overloaded method located at line '2'.

**Comment by romani** [comment]
> However this makes grouping methods by group static v.s. not impossible.

Please rephrase this, I do not understand this sentence. 
Imagine that everything is possible to change in Check, propose name of option, its description and code examples how it should affect validation behaviour. 

Please extend description of this issue to specify a reason why you think Check need an option, provide examples of code to prove your idea.

**Comment by romani** [comment]
@supercobra, can you clarify your issue ?

**Comment by LoPoBo** [comment]
We have the same issue in our project. It makes it impossible to separate static methods from non-static methods (at least in some cases).

Example:

    public class MyInt {
      ...
      public static MyInt add(MyInt lhs, MyInt rhs) { ... }
      public static MyInt subtract(MyInt lhs, MyInt rhs) { ... }
      public void add(MyInt rhs) { ... }
      public void subtract(MyInt rhs) { ... }
      ...
    }

This is how we would organize the methods in our project, with static methods first, but `OverloadMethodsDeclarationOrderCheck` complains that the ones with the same name aren't adjacent.

**Comment by romani** [comment]
Issue is controversial as by terminology of "override" methods only name is considered - `... have the same name but signatures that are not override-equivalent. ...`(from jdk specificaation).

https://en.wikibooks.org/wiki/Java_Programming/Overloading_Methods_and_Constructors

>  The signature of a method is comprised of its name, its parameter types and the order of its parameter. The signature of a method is not comprised of its return type nor its visibility nor its exceptions it may throw.

https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.4.9
but it does not exists in java8 specification!!! , so let me grab content for future reference, see below.

So from pure terminology perspective Check works fine. We could make an option to make it "up to user" but we need more prove of demand for this, some discussion on stackoverflow about style or ..... .

----------------------------

CONTENT FROM https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.4.9 :
8.4.9. Overloading

**If two methods of a class (whether both declared in the same class, or both inherited by a class, or one declared and one inherited) have the same name but signatures that are not override-equivalent, then the method name is said to be overloaded.
**
This fact causes no difficulty and never of itself results in a compile-time error. There is no required relationship between the return types or between the throws clauses of two methods with the same name, unless their signatures are override-equivalent.

When a method is invoked (§15.12), the number of actual arguments (and any explicit type arguments) and the compile-time types of the arguments are used, at compile time, to determine the signature of the method that will be invoked (§15.12.2). If the method that is to be invoked is an instance method, the actual method to be invoked will be determined at run time, using dynamic method lookup (§15.12.4).

Example 8.4.9-1. Overloading
```
class Point {
    float x, y;
    void move(int dx, int dy) { x += dx; y += dy; }
    void move(float dx, float dy) { x += dx; y += dy; }
    public String toString() { return "("+x+","+y+")"; }
}
```

Here, the class Point has two members that are methods with the same name, move. The overloaded move method of class Point chosen for any particular method invocation is determined at compile time by the overloading resolution procedure given in §15.12.

In total, the members of the class Point are the float instance variables x and y declared in Point, the two declared move methods, the declared toString method, and the members that Point inherits from its implicit direct superclass Object (§4.3.2), such as the method hashCode. Note that Point does not inherit the toString method of class Object because that method is overridden by the declaration of the toString method in class Point.

Example 8.4.9-2. Overloading, Overriding, and Hiding

```
class Point {
    int x = 0, y = 0;
    void move(int dx, int dy) { x += dx; y += dy; }
    int color;
}
class RealPoint extends Point {
    float x = 0.0f, y = 0.0f;
    void move(int dx, int dy) { move((float)dx, (float)dy); }
    void move(float dx, float dy) { x += dx; y += dy; }
}
```

Here, the class RealPoint hides the declarations of the int instance variables x and y of class Point with its own float instance variables x and y, and overrides the method move of class Point with its own move method. It also overloads the name move with another method with a different signature (§8.4.2).

In this example, the members of the class RealPoint include the instance variable color inherited from the class Point, the float instance variables x and y declared in RealPoint, and the two move methods declared in RealPoint.

Which of these overloaded move methods of class RealPoint will be chosen for any particular method invocation will be determined at compile time by the overloading resolution procedure described in §15.12.

This following program is an extended variation of the preceding program:
```
class Point {
    int x = 0, y = 0, color;
    void move(int dx, int dy) { x += dx; y += dy; }
    int getX() { return x; }
    int getY() { return y; }
}
class RealPoint extends Point {
    float x = 0.0f, y = 0.0f;
    void move(int dx, int dy) { move((float)dx, (float)dy); }
    void move(float dx, float dy) { x += dx; y += dy; }
    float getX() { return x; }
    float getY() { return y; }
}
```

Here, the class Point provides methods getX and getY that return the values of its fields x and y; the class RealPoint then overrides these methods by declaring methods with the same signature. The result is two errors at compile time, one for each method, because the return types do not match; the methods in class Point return values of type int, but the wanna-be overriding methods in class RealPoint return values of type float.

This program corrects the errors of the preceding program:
```
class Point {
    int x = 0, y = 0;
    void move(int dx, int dy) { x += dx; y += dy; }
    int getX() { return x; }
    int getY() { return y; }
    int color;
}
class RealPoint extends Point {
    float x = 0.0f, y = 0.0f;
    void move(int dx, int dy) { move((float)dx, (float)dy); }
    void move(float dx, float dy) { x += dx; y += dy; }
    int getX() { return (int)Math.floor(x); }
    int getY() { return (int)Math.floor(y); }
}
```

Here, the overriding methods getX and getY in class RealPoint have the same return types as the methods of class Point that they override, so this code can be successfully compiled.

Consider, then, this test program:
```
class Test {
    public static void main(String[] args) {
        RealPoint rp = new RealPoint();
        Point p = rp;
        rp.move(1.71828f, 4.14159f);
        p.move(1, -1);
        show(p.x, p.y);
        show(rp.x, rp.y);
        show(p.getX(), p.getY());
        show(rp.getX(), rp.getY());
    }
    static void show(int x, int y) {
        System.out.println("(" + x + ", " + y + ")");
    }
    static void show(float x, float y) {
        System.out.println("(" + x + ", " + y + ")");
    }
}
```
The output from this program is:
```
(0, 0)
(2.7182798, 3.14159)
(2, 3)
(2, 3)
```
The first line of output illustrates the fact that an instance of RealPoint actually contains the two integer fields declared in class Point; it is just that their names are hidden from code that occurs within the declaration of class RealPoint (and those of any subclasses it might have). When a reference to an instance of class RealPoint in a variable of type Point is used to access the field x, the integer field x declared in class Point is accessed. The fact that its value is zero indicates that the method invocation p.move(1, -1) did not invoke the method move of class Point; instead, it invoked the overriding method move of class RealPoint.

The second line of output shows that the field access rp.x refers to the field x declared in class RealPoint. This field is of type float, and this second line of output accordingly displays floating-point values. Incidentally, this also illustrates the fact that the method name show is overloaded; the types of the arguments in the method invocation dictate which of the two definitions will be invoked.

The last two lines of output show that the method invocations p.getX() and rp.getX() each invoke the getX method declared in class RealPoint. Indeed, there is no way to invoke the getX method of class Point for an instance of class RealPoint from outside the body of RealPoint, no matter what the type of the variable we may use to hold the reference to the object. Thus, we see that fields and methods behave differently: hiding is different from overriding.
