### ISSUE TITLE
XDocsPagesTest$validateCheckSection has NPath complexity of 217

### ISSUE THREAD

**Issue by attatrol** [checkstyle/checkstyle#2906]
I'm trying to solve issue #56, it adds some functionality into NPathComplexityCheck, and now this check generates a single error for the checkstyle:

> /checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java:301:5: NPath Complexity is 217 (max allowed is 200). [NPathComplexity]

After i got this message i checked that method complexity manually and got the same result, so it should be refactored.

**Comment by romani** [comment]
We try to suppress such Check in test code, most metrics Checks are suppressed in test code.

@rnveach , please share your thiughts.

**Comment by rnveach** [comment]
@romani This method, since it was first introduced, has always come up as too complex. Originally it was CyclomaticComplexity ([suppresion](https://github.com/checkstyle/checkstyle/blob/2a0fa19e821d6c26ab6fd9889f40d33259cc6354/config/suppressions.xml#L77)), now its NPathComplexityCheck.
I personally don't think the method is that complex. If you wish me to fix it, I can do that. I assume moving the contents of the [for loop](https://github.com/checkstyle/checkstyle/blob/ba6781e1098fbbd76482c67a2e21f2796db166a2/src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java#L313) to its own method will bring it down more than 17 npath.

**Comment by attatrol** [comment]
@rnveach
Your assumption is wrong, contents of the for loop itself has complexity of 216

**Comment by rnveach** [comment]
Sorry, I am not familiar with calculating npath and the current check gives me 34, but I assume the switch is what is generating the high numbers. Is it lowered enough if the empty switch cases are removed or switched to if/else?

**Comment by attatrol** [comment]
@rnveach ,
I mean my own improved version of a check and manual calculation give value of 217. Current version of a check doesn't calculate expression values as described in issue #56

**Comment by romani** [comment]
@attatrol , please add this method to suppression for NPath Check - it is ok.

**Comment by attatrol** [comment]
@romani,
understood
