### ISSUE TITLE
Add HTML5 tags support to Javadoc antlr4 grammar and related classes

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#3332]
We should extend void(singleton) elements list and list of elements with optional end tag.

List of void elements:
basefont, frame, isindex - are not supported in HTML5; but they have to stay in Javadoc grammar.

| [HTML5](https://www.w3.org/TR/html5/syntax.html#void-elements) | HTML4 |
| --- | --- |
| area | area |
| base | base |
| br | br |
| col | col |
| hr | hr |
| img | img |
| input | input |
| link | link |
| meta | meta |
| param | param |
| embed |  |
| keygen |  |
| source |  |
| track |  |
| wbr |  |
|  | basefont |
|  | frame |
|  | isindex |

List of elements with optional end tag:

| [HTML5](https://www.w3.org/TR/html5/syntax.html#optional-tags) | HTML4 |
| --- | --- |
| html | html |
| head | head |
| body | body |
| li | li |
| dt | dt |
| dd | dd |
| p | p |
| option | option |
| colgroup | colgroup |
| thead | thead |
| tbody | tbody |
| tfoot | tfoot |
| tr | tr |
| td | td |
| th | th |
| optgroup |  |
| rb |  |
| rt |  |
| rtc |  |
| rp |  |
##

**Comment by blerner** [comment]
Out of curiosity: why hard-code the list of tags at all?  Per the javadoc spec, https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDBGGIH, 
```
Write Comments in HTML

The text must be written in HTML with HTML entities and HTML tags. You can use whichever version of HTML your browser supports.
```
And per the HTML5 spec, https://www.w3.org/TR/html5/syntax.html#parsing-main-inbody, any element with an unknown name is handled uniformly by simply creating an HTMLUnknownElement (https://www.w3.org/TR/html5/syntax.html#create-an-element-for-the-token).  The only restriction on such tags is that they can't be self-closing.  So, rather than having hundreds of nearly-identical lines of code in JavadocParser.g4 for each of the various node cases, why not just hard-code the list of self-closing tags, and then just require that the remaining tags match up?

(The one major complication I can see in parsing Javadoc with HTML tags in it is if the Javadoc contains `Foo<T>` bits of Java code that weren't wrapped in `{@code ...}`, which makes it look like a `<T>` tag has been opened.  This could be tricky to handle, so maybe that's why the list of tags is hardcoded?)

**Comment by romani** [comment]
There are bunch of nuances with parsing , but our goal is not to parse but make AST that is convenient for Check creation and allow user with less code create new Check. We keep certain tokens hardcoded to create special AST token, all unknown tags will be in AST to but as general tags.

http://checkstyle.sourceforge.net/writingjavadocchecks.html#Javadoc_parser_behavior_for_current_HTML_version_and_new_HTML_version

If you are interested, read whole page, it describes some points.

**Comment by blerner** [comment]
Thanks for the link.  Yes, parsing is always surprisingly subtle.  The main reason I thought the repetitive grammar rules might be a problem was because of the example I mentioned above.  A student of mine commented out a huge chunk of code containing `Foo<T>` text...but instead of using `/* ... */`, used `/** ... **/`, which marked the code as a Javadoc block  But, parsing this comment (as part of other checkstyle rules in an auto-grader for the relevant homework assignment) took unbelievably long, and I had to force-quit the autograder.  I truncated the comment to 20 lines, and parsing sped up.  Some searching led me to https://groups.google.com/forum/#!topic/antlr-discussion/8uclWFreMSs and https://github.com/checkstyle/checkstyle/issues/1064.  I'm using v7.7 of checkstyle, so I know I have that fix as part of the library...but I'm still getting really bad performance.  But as part of reading that group post and issue report, I tried to debug what might be wrong with the grammar, leading me to this suggestion.

I can provide a simplified repro of the problem in a separate issue, if that's more useful...?

**Comment by rnveach** [comment]
> commented out a huge chunk of code containing Foo<T> text...but ... used /** ... **/, which marked the code as a Javadoc block 

@blerner Your issue sounds very similar to https://github.com/checkstyle/checkstyle/issues/3727#issuecomment-272631389 which hung in a similar area and failed.
I never looked into where it was hanging, but is most likely a different area than the original text grammar issue.

**Comment by blerner** [comment]
Yes...that does sound similar.  The reduced test case I was using was basically
```java
class DontCare {
/**
  @Test
  public void someTestMethod() {
    List<Foo> x;
    List<Foo> x;
    ...add more copies of this line to make the runtime worse...
    feefiefoefum
    feefiefoefum
    ...and add more copies of this line, too.
  }
**/
}
```
As far as I can tell:
* You need at least two `List<Foo>` lines before the parser chokes
* With ~20 lines of "feefiefoefum", each additional `List<Foo>` line adds ~2 seconds to the parse time
* With more lines of "feefiefoefum", the runtime grows accordingly
* If I replace every `List<Foo>` with `List?Foo?`, so that the text is identical in length, the runtime is ~ 1sec (including the startup time of my surrounding application, so, basically instantly).

**Comment by romani** [comment]
Let's move this case in separate issue and do discussion in separate thread/issue

**Comment by Vladlis** [comment]
In html5 void tags are allowed to be self-closing, so the following rule has to be removed: https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L826

**Comment by rnveach** [comment]
> In html5 void tags are allowed to be self-closing, so the following rule has to be removed

We still need it to support older HTML versions as grammar will not enforce a specific HTML version, right? If so, we can't break compatibility with older versions.

**Comment by Vladlis** [comment]
We'll only break compatibility by allowing void self-closing tags like `<br/>` which is a part of update to html5, as well as we are going to break it by adding new tags.

**Comment by romani** [comment]
@rnveach , @Vladlis 

> We still need it to support older HTML versions as grammar will not enforce a specific HTML version, right?

we have to support HTML4, it will be in javadoc for long time, most of java engineers do not know all nuances of html5 features. So breaking compatibility is not expected for now. If it is not avoidable - need to be explained to users somewhere in xdoc and too all maintainers to confirm.

**Comment by ps-sp** [comment]
@Vladlis 
>so the following rule has to be removed: 

Please correct me if wrong, but that rule is about void elements not having an end tag, and in html 5 too void tags must not have an end tag. So it shouldn't be removed.

**Comment by ps-sp** [comment]
@Vladlis 
>so the following rule has to be removed: 

Please correct me if wrong, but that rule is about void elements not having an end tag, and in html 5 too void tags must not have an end tag. So it shouldn't be removed.

As [this](https://www.w3.org/TR/html51/syntax.html#void-elements) page says:

> Void elements only have a start tag; end tags must not be specified for void elements.

**Comment by Vladlis** [comment]
checked the following
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
   <title>TITLE</title>
</head>
<body>
   <div>
     <p/>     
   </div>
</body>
</html>
```
in https://validator.w3.org/check and only got warning about `<p/>`
so the current rule is valid and I'm closing this issue.

**Comment by Vladlis** [comment]
@ps-sp yes, sorry, I've misunderstood `wrongSinletonTag` rule

**Comment by ps-sp** [comment]
As has been discussed with @Vladlis PR shall be created for each new HTML tag to be added for better PR management.

**Comment by ps-sp** [comment]
@romani @rnveach @Vladlis 
Uptil now we had allowed tag omission unconditionally for tags like `<p>`, `<li>` and so on. But there are actually conditions attached to ommiting end tags. For example, consider the `<rb>` element which is to be introduced in this issue, [from specification](https://www.w3.org/TR/html5/text-level-semantics.html#the-rb-element):
>An rb element's end tag may be omitted if the rb element is immediately followed by an rb, rt, rtc or rp element, or if there is no more content in the parent element.

Should we incorporate such conditions in grammar ?

**Comment by romani** [comment]
I do not we need to be , as it over complicate grammar, lets keep all of such tags with non required end tag.

**Comment by Vladlis** [comment]
I think we could look deeper, but certainly not in this issue. And it won't be our priority.
@romani , should we have an issue for this? Even if we decide to keep the grammar simpler we still have to add a note about this in documentation.

**Comment by romani** [comment]
Ok with note in documentation and separate issue

**Comment by rnveach** [comment]
@romani @ps-sp Please confirm what is left to do with this issue or close it if it is done.

**Comment by ps-sp** [comment]
@rnveach 
`rb`, `rt`, `rtc`, and `rp` are the only tags that remain to be added. They should be added in a single PR with one commit for each tag in a way similar to [#4995](https://github.com/checkstyle/checkstyle/pull/4995).

**Comment by romani** [comment]
@ps-sp , thanks a lot for you help.

**Comment by romani** [comment]
@ps-sp , please do us big favor make all this changes during this month to make only one release be with damaging for compatibility. 

We appreciate your activity in PRs to finish updates, but PRs could wait a  bit more, but this Issue is better to do in one release.
Thanks in advance.

**Comment by ps-sp** [comment]
@romani 
Yeah sorry, couldn't work. Will hopefully have a PR by tomorrow.

**Comment by rnveach** [comment]
Final fix was merged
