### ISSUE TITLE
IllegalImportCheck should allow fully-qualified classes

### ISSUE THREAD

**Issue by dhalperi** [checkstyle/checkstyle#3358]
Existing `IllegalImportInput.java` has this snippet:

```java
1. import sun.*;
2. 
3. import java.awt.Component;
4. import java.awt.Graphics2D;
5. import java.awt.HeadlessException;
6. import java.awt.Label;
7. import java.util.Date;
8. import java.util.Calendar;
9. import java.util.BitSet;
```

We can do now:
==
* Blacklist line 1 with the default value `sun`
* Blacklist lines 3--9 with the value `java`
* Blacklist lines 3--6 with the value `java.awt`
* Blacklist lines 7--9 with the value `java.util`

But we cannot:
==
* Blacklist line 7 with the value `java.util.Date`, and similar.

This is because the check is that the import test starts with `pattern + "."`. It's an easy fix to check for either `startsWith(pattern + '.')` or `equals(pattern)`.

But it could also be improved under the hood by using a compiled Regex (`Pattern`) to implement the check.

**Comment by rnveach** [comment]
@dhalperi 
IllegalImportCheck says it is specifically written just for validating packages.
[ImportControlCheck](http://checkstyle.sourceforge.net/config_imports.html#ImportControl) states it is for controlling what classes can be imported from the packages.

Why can't you use ImportControlCheck for your needs?

**Comment by dhalperi** [comment]
@rnveach you raise a good point, but config in a separate file frankly stinks. We blacklist packages in `checkstyle.xml` and classes in `import_control.xml` -- can't see one thing in one place.

Separate Q: assuming you don't want #3359 , do you want the pattern speedup factored out separately?

**Comment by dhalperi** [comment]
Also, it looks like `ImportControl` is for package-local, not project-global settings. We want the latter.

**Comment by dhalperi** [comment]
For more fun: `ImportControl` does not appear to be able to find configurations that are resources, only files. So this does not seem to be usable at all if `checkstyle.xml` is in your project as a resource rather than a file.

**Comment by caugner** [comment]
How about implementing a second parameter `illegalClasses` (default: `null`):

```xml
<module name="IllegalImport">
    <property name="illegalPkgs" value="sun, java.awt"/>
    <property name="illegalClasses" value="java.util.Date, java.util.Calendar"/>
</module>
```

Furthermore we could add a third parameter `regexp` (default: `false`) that determines whether the comma separated package or class names should be interpreted as regular expressions:

```xml
<module name="IllegalImport">
    <property name="illegalPkgs" value="sun, java\.awt"/>
    <property name="illegalClasses" value="java\.util\.(Calendar|Date)"/>
    <property name="regexp" value="true"/>
</module>
```

Both would support the mentioned case without interfering with the current behavior.

@rnveach What do you think? I personally don't think it would hurt. Note also:

1. Users might want to use more than one `ImportControl` check with varying severity. This would be much less straight forward using the `ImportControlCheck`, simply because it would require multiple `import_control.xml` files.
2. Users might just want to globally forbid certain classes (such as old [FindBugs annotations](http://findbugs.sourceforge.net/api/edu/umd/cs/findbugs/annotations/package-summary.html), where some annotations in the same package are still valid). In cases like this, defining an `import_control.xml` file seems like overkill to me, when the same could be achieved with just these two additional parameters.

**Comment by romani** [comment]
@dhalperi ,

> Separate Q: assuming you don't want #3300 59 , do you want the pattern change at all?

no, we will not do update in this way.

>  We blacklist packages in checkstyle.xml

yes, it should be possible to be done by IllegalImportCheck - simple list of backlist packages. 

> Also, it looks like ImportControl is for package-local, not project-global settings.

we use ImportControl for whole project rules.

@caugner,

I like your idea. I moved it to #3449 , to keep description clear.

**Comment by romani** [comment]
Additional issues: #3451 , #3450

**Comment by romani** [comment]
Issue is closed as it was split in few issues, and original request is strict proposal.

**Comment by romani** [comment]
While issues are not resolved, you can take a look at http://sevntu-checkstyle.github.io/sevntu.checkstyle/apidocs/com/github/sevntu/checkstyle/checks/coding/ForbidCertainImportsCheck.html it should do what you need.

**Comment by romani** [comment]
@dhalperi ,

> And I can't figure out how to put ImportControl into blacklist mode, aka except everything but the things I've listed. (Using allow pkg="" seems to allow everything and ignore disallow blocks.)

It should work, we allow bigger package ["java.util"](https://github.com/checkstyle/checkstyle/blob/master/config/import-control.xml#L13) and disallow ["java.util.stream.Stream"](https://github.com/checkstyle/checkstyle/blob/master/config/import-control.xml#L20) . See our internal config for more examples - https://github.com/checkstyle/checkstyle/blob/master/config/import-control.xml

We also plan to better support "blacklist" mode , please join discussion at #3451 .
