### ISSUE TITLE
no blank line between import groups in google style

### ISSUE THREAD

**Issue by elharo** [checkstyle/checkstyle#3553]
<property name="separateLineBetweenGroups" value="true"/>

should be

  <property name="separateLineBetweenGroups" value="false"/>

in google_checks.xml

per https://google.github.io/styleguide/javaguide.html#s3.3-import-statements

**Comment by rnveach** [comment]
This is related to what #3551 is about fixing.

**Comment by romani** [comment]
>`<property name="separateLineBetweenGroups" value="true"/> `

https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L170

Check: http://checkstyle.sourceforge.net/config_imports.html#CustomImportOrder

from google style:
> If there are both static and non-static imports, a single blank line separates the two blocks. There are no other blank lines between import statements.

option `separateLineBetweenGroups` is required to be `true` because request is `... , a single blank line separates the two blocks. .....`

>...... There are no other blank lines between import statements.

will be addressed during #3551 .
