### ISSUE TITLE
refactoring: CodeSelectorPModel do double copy of collectio in c-tor

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3555]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentation.java#L51

not clear why ....

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39298075-refactoring-codeselectorpmodel-do-double-copy-of-collectio-in-c-tor?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by rnveach** [comment]
`unmodifiableList` may not really serve a purpose. We don't pass the field anywhere in that class, so we have no worries of modifications.

The array copy is most likely because we are worried about the list being modified from outside the class from where it was originally generated. `unmodifiableList` still references the list being copied.

The list is generated [here](https://github.com/checkstyle/checkstyle/blob/d49732c325b15cb6d7d34f7f838bd51ced2b8e3d/src/main/java/com/puppycrawl/tools/checkstyle/gui/JTreeTable.java#L241), which does another array copy and 'unmodifiable'.
Which is again a list generated from [here](https://github.com/checkstyle/checkstyle/blob/d49732c325b15cb6d7d34f7f838bd51ced2b8e3d/src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java#L177), which does another array copy and 'unmodifiable'.
All of which, is finally first generated [here](https://github.com/checkstyle/checkstyle/blob/d49732c325b15cb6d7d34f7f838bd51ced2b8e3d/src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java#L210), when the file is first opened.

I think the code at MainFrameModel.java#L177 is valid. All the other array copies and 'unmodifiable' may be just extra protection to make sure we are not passing around a list that can be modified. One class won't know what its children are doing with it.

**Comment by MEZk** [comment]
@rnveach @romani 
Collections.unmodifiableList does not create copy. It creates unmodifiable view of the list. It is a kind of wrapper.

See
https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#unmodifiableList(java.util.List)

**Comment by romani** [comment]
fix is merged
