### ISSUE TITLE
Unexpected loss of coverage for PropertyCacheFile.java

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3594]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java

Catch block is not covered :
```
    private static byte[] loadExternalResource(String location) throws CheckstyleException {
        byte[] content = null;
        final URI uri = CommonUtils.getUriByFilename(location);

        try {
            .....
        }
        catch (IOException ex) {
            throw new CheckstyleException("Unable to load external resource file " + location, ex);
        }

        return content;
    }
```

noticed at https://travis-ci.org/checkstyle/checkstyle/builds/179591339

**Comment by rnveach** [comment]
Travis: https://travis-ci.org/checkstyle/checkstyle/builds/179591339

Travis is failing because we unexpectedly lost code coverage of the above mentioned catch.
We had this covered before. It was covered by [CheckerTest.testCacheIoExceptionWhenReadingExternalResource](https://github.com/checkstyle/checkstyle/blob/56cc11416ebdf52dd299d11424fb04fda42fa63f/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L618).

The reason for the change was due to an external URL not throwing the exception anymore when loading `http://mock.sourceforge.net/suppressions_none.xml`. Reason for no exception being thrown now is unknown atm.

The biggest thing to take note of is when this external change happened, code coverage failed but our tests still passed. Ideally, both should fail not one. For our tests not to fail, it means we are missing testing something. So I consider this to be a secondary failure.
The reason for this secondary failure is because we are calling methods and not verifying any type of result.
Example: https://github.com/checkstyle/checkstyle/blob/56cc11416ebdf52dd299d11424fb04fda42fa63f/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L635-L637
Even though we are expecting and testing an exception, the test in question doesn't throw an exception to junit because `PropertyCacheFile.loadExternalResources(Set<String> resourceLocations)` hides the exception and does other processing. No where in those lines are we testing to make sure the exception happens.

There are more tests like this for the cache in `CheckerTest` that could cause the same type of failure. Some examples:
https://github.com/checkstyle/checkstyle/blob/56cc11416ebdf52dd299d11424fb04fda42fa63f/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L661-L664
https://github.com/checkstyle/checkstyle/blob/56cc11416ebdf52dd299d11424fb04fda42fa63f/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L682-L684
https://github.com/checkstyle/checkstyle/blob/56cc11416ebdf52dd299d11424fb04fda42fa63f/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L712-L718

**Comment by romani** [comment]
fix is merged, no problems with coverage

**Comment by rnveach** [comment]
@romani We aren't going to examine/fix any of the other areas I identified in my comment that could cause similar issues?

**Comment by romani** [comment]
please open new issue on this with clear description what to do
