### ISSUE TITLE
Use reflection to load Checks base on checkstyle_packages.xml

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3607]
base on #3184

Consider to use reflection. 
Use checkstyle_packages.xml and our naming notation that Check class should be "*Check".
How to get all classes from package - http://stackoverflow.com/a/520339

But problem will still be with extensions(custom Checks in custom jars), for example sevntu extension.

**Comment by MEZk** [comment]
@romani 
Are you sure that we need additional library (Reflections) for this?
We can scan the package and get all file names which end with Check and then instantiate the classes based on the fully qualified class names.

**Comment by rnveach** [comment]
> our naming notation that Check class should be "*Check".

We dropped this convention in test's `CheckUtil` because it missed out on our own checks that end with `Holder` instead of `Check`.
I think checking the class' inheritance is enough, who cares what it is named.

> We can scan the package 

@MEZk I don't think we can scan packages without an extra library as you have to look in the JARs that are on the classpath. It is not naturally part of the Java Reflection API. Guava may support it like the PR states, but we are trying to rely on it less.

I do question why we need this as we can already load 3rd party classes and our own just fine.
`CheckUtil` picks up everything fine for our tests.
Why do we need in-depth production runtime scanning?

I assume this issue wanted to just look into the idea and discuss, not go straight to implementation.

**Comment by MEZk** [comment]
> I do question why we need this as we can already load 3rd party classes and our own just fine.
CheckUtil picks up everything fine for our tests.

Agree. Why do we need the extra dependency on Reflections?
We can continue using ClassPath from Guava.

@romani 
Please, share your ideas.

**Comment by romani** [comment]
If we can do scan without extra dependencies it is good.

Reuse guava is ok, as we can not drop it as we use their fancy collections.

I do not know the best solution for this problem, we can look at PRs for this.

**Comment by rnveach** [comment]
> should we finish our discussion in issue first to make expected design decision?

@romani I don't think I have anything more to add to issue.
If we are able to find all our checks without issue, I don't see why we need to this new dependency.
If we need this to be able to find 3rd party checks, please give us an example where current implementation fails in this regard or new dependency does it better.

**Comment by MEZk** [comment]
@rnveach 
> If we are able to find all our checks without issue, I don't see why we need this new dependency.

Completely agree. I'm against the new dependency. New dependency will bring new problems. There always be a desire to use it once again. As I sad at #3607, we do not introduce new checks very frequently, so we are able to add the checks into the map.

**Comment by MEZk** [comment]
@romani 
Can you share your opinion b ased on https://github.com/checkstyle/checkstyle/issues/3607#issuecomment-293072266 and https://github.com/checkstyle/checkstyle/issues/3607#issuecomment-292790092 to allow us to continue https://github.com/checkstyle/checkstyle/pull/4152 ?

**Comment by romani** [comment]
lets consider solution without any extra dependency.

**Comment by romani** [comment]
fix is merged.
