### ISSUE TITLE
Write Tag severity configuration is inconsistent with ConfigurationLoader

### ISSUE THREAD

**Issue by cypai** [checkstyle/checkstyle#3669]
The Write Tag check is expected to output warnings even if the severity is set to ignore. See the example in the documentation on flagging warnings on `@incomplete` tags: http://checkstyle.sourceforge.net/config_javadoc.html#WriteTag

However, downstream projects like eclipse-cs rely on checking the severity for performance reasons:
https://sourceforge.net/p/eclipse-cs/bugs/413/

ConfigurationLoader within checkstyle as well assumes that the severity is an on/off switch:
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java#L103

Write Tag is the only check in checkstyle where the severity is not regarded as a global ignore switch. The workaround is to just use RegexpSingleline, but it might be a good idea to make it the severity for Write Tag an on/off switch as well for consistency's sake (though backwards compatibility will be broken).

**Comment by romani** [comment]
This Check is complete mis-design and problem.
It is deprecated, it is better to use RegExp checks.

Related issues: #2506 , #952 .

For now I do not know what will be better: to remove Check completely now and redo it or update their properties to make it somehow reasonable.

Problems with keeping it:
1) I do not know use-cases where it is reasonable to demand certain tag in javadoc. `@since`  is reasonable for all api classes, but check currently does not support any way to differentiate targets of validation. All Other javadoc tokens are not applicable for all.
2) Name is bad, it is hard to understand what it is doing.
3) it has to be reimplemented to use Javadoc Parser Tree to be reliable.
4) properties `tokens` will go as "3)" is done, so `javadocTokens` property will appear.
5) property "tagSeverity" should be removed completely!!
6) so all changes it result in minor or major braking compatibility.

Benefit to keep it:
just to keep compatibility..... but I doubt that smb use this terrible Check.

I am more in favor of removing it completely.

@rnveach , please share your thoughts ? to keep(and try to fix) or drop it.

**Comment by rnveach** [comment]
@romani 
Truthfully, I never really looked into this check and didn't really understand its use before now.
It's description talks about stylesheets and reports. I don't find myself needing a special report hence why I avoided it.

Now that I understand it is a custom regexp for javadocs, I would like to keep its use, but it doesn't have to be as this specific check. Like I said, name and description was misleading to me.
So I am fine with removing it, if we could redo it as new check(s) with similar or additional features.

> do not know use-cases where it is reasonable to demand certain tag in javadoc.

This check has other use cases besides requiring a tag:
1) Prevent tags from showing up, like `author`.
2) Requiring all tags to start with an uppercase letter if it starts with an ascii letter or end with a period.
3) I saw one use case on github where they require `since` to be a 3 digit number separated by periods.
4) Another case on github required `author` to only be specific person's name and email.

I can think of other ideas for new checks to make javadoc follow pattern based on the type of method it defines, which is similar to this check but would require more logic so it might as well be a different check.

**Comment by romani** [comment]
> Prevent tags from showing up, like author

Yes, I would like to forbid this tag too.
This does not work in Eclipse, as described in issue.

> Requiring all tags to start with an uppercase letter if it starts with an ascii letter or end with a period.

good idea but it is not supported now by Check. Upgrade of the Check to have regexp for `tag` is possible and not braking compatibility.

> I saw one use case on github where they require since to be a 3 digit number separated by periods.
Another case on github required author to only be specific person's name and email.

Reasonable, as soon as it is not demand for all comments and could be enforced only at Class level. Current Check has option to be specific to certain javadoc comment.

> properties tokens will go as "3)" is done, so javadocTokens property will appear.

it is applicable to all javadoc checks, so it is not a reason to remove Check.

**Comment by romani** [comment]
Weirdness of this Check:
a) Even severity is set to "warning", Check do report "infor".
b) Check report matched and not matched tags in the same time .....
```
/var/tmp$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
                        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <property name="charset" value="UTF-8"/>
  <property name="severity" value="warning"/>
  <module name="TreeWalker">
    <module name="WriteTag">
      <property name="tag" value="@author"/>
      <!-- author has to finish with dot -->
      <property name="tagFormat" value=".*\.$"/>
      <property name="tokens" value="METHOD_DEF"/>
    </module>
  </module>
</module>

/var/tmp$ cat MyClass.java 
public final class MyClass {
    /**
     * This is a method.
     * @author Name with dot.
     */
    public void foo(){}

    /**
     * This is a method.
     * @author Name without dot
     */
    public void foo2(){}    
}

/var/tmp$ java -jar checkstyle-7.3-all.jar -c config.xml MyClass.java 
Starting audit...
[INFO] /var/tmp/MyClass.java:4: @author=Name with dot. [WriteTag]
[WARN] /var/tmp/MyClass.java:10: Type Javadoc tag @author must match pattern '.*\.$'. [WriteTag]
Audit done.
```

**Comment by romani** [comment]
merged to https://github.com/checkstyle/checkstyle/issues/952
