### ISSUE TITLE
Can't override `-t` option for custom tree modules

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3792]
I am planning to start looking into making new custom trees in another project. It would be very helpful if Checkstyle's CLI allowed printing those module's trees. Right now `TreeWalker` has a monopoly on the `-t`/`-T` options. Those options go directly to `TreeWalker` and there is no way to override the default for custom modules with their own trees. Viewing trees is very helpful when debugging the tree and making new modules for that tree. The only current way to do this without the CLI is to make print module.

I would like an option to override the default tree module and be able to select a different one.
This is the current CLI example I am thinking of now: `-t -m MyCustomTreeModule`.
Just like the configuration, it would work if the class is defined in the packages XML or if I specify the full classpath.

To make this more seamless, we might want to consider moving Checkstyle's tree specific code from `AstTreeStringPrinter` to the actual tree class (`TreeWalker` and `AbstractJavadocCheck`) and have `AstTreeStringPrinter` be a full utility class that any class can use for their own trees. Also make an API interface defining these special modules as AST Tree modules that support methods like `parse` and `print`.

**Comment by romani** [comment]
> I would like an option to override the default tree module and be able to select a different one.

Checkstyle CLI is created only for checkstyle's purposes. it is not a api and it is not framework and not a toolkit, .... .

> To make this more seamless, we might want to consider moving Checkstyle's tree specific code from AstTreeStringPrinter to the actual tree class (TreeWalker and AbstractJavadocCheck) 

it not good idea.

> I am planning to start looking into making new custom trees in another project.

it is good idea to just copy code from chekstyle (if you like it) and make smth other that will serve all your needs. 

>  Those options go directly to TreeWalker and there is no way to override the default for custom modules with their own trees.

chekcstyle CLI and checkstyle functionality are different parts, ideally there should be less dependencies, we reuse TreeWalker because it is integral part of checkstyle that is hard to work without. It would be better to use java parser directly from cli, but this is another issue.

**Comment by rnveach** [comment]
@romani If we won't allow customizing the CLI somehow with extra JARs, then close this issue.

**Comment by romani** [comment]
I do not see future in this issue.
in your custom project you need do sme hack over chekstyle code to make what is convenient for you.
