### ISSUE TITLE
reconsider behavior for multiple property lines of the same name in config

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3836]
from #3751

Why we have two lines for tokens ? It is override. Should be forbidden by XML schema.

[DefaultConfiguration merges multiple properties together like it was one line.](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DefaultConfiguration.java#L106-L114) Some were already like this in the config, so I thought it was acceptable for history viewing to clearly show removes/adds.
[There is an old commit where tokens were purposely made like this.](https://github.com/checkstyle/checkstyle/commit/95f7a7cde50ceac50d41c2bff65b6983c888bea3) Most of those changes and documentation are still around.
Ex: http://checkstyle.sourceforge.net/property_types.html#stringSet
> this property can be supplied multiple times which is equivalent to a set of comma separated strings.

**Comment by rnveach** [comment]
I disagree with forbidding. It helps us with 100 column limit in XML files. This would be a breaking change if implemented.

**Comment by romani** [comment]
@rnveach , yes, to some extend I agree with you, should we document this? any ideas where ?
 as it is not very obvious behavior.

**Comment by rnveach** [comment]
I agree it isn't obvious. You already mentioned one area where it is documented.
> Ex: http://checkstyle.sourceforge.net/property_types.html#stringSet

> > this property can be supplied multiple times which is equivalent to a set of comma separated strings.

Which makes sense to me since it is specifying the definition of a String set, which is what this type of property is. It also specifies it for IntSet, http://checkstyle.sourceforge.net/property_types.html#intSet .

The other area which makes sense, http://checkstyle.sourceforge.net/config.html#Properties , specifies the catch all at the bottom with a link.
> You can find information about property types on Property Types page. 

I don't see what else we can do for documentation that wouldn't just be to be sure to read documentation on property types.

**Comment by romani** [comment]
Ok, let's close this issue
