### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for MethodLength

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4042]
subtask of #3891 .

do a copy of all test input files to separate folder for MethodLength .
Not any other Check should use new inputs.

**Comment by GabrielBercaru** [comment]
Is this issue pre-assigned to someone or anyone could start working on it?

**Comment by romani** [comment]
@GabrielBercaru , no, you can take it.

**Comment by GabrielBercaru** [comment]
I am on it.

**Comment by GabrielBercaru** [comment]
Since the input files "InputModifier.java" and "InputSimple.java" are used by multiple check test files, should I copy them inside a new directory "methodlength" and also keep the old ones inside "sizes" package? Should I dupilicate them or should I update all the check test files that use those files?

**Comment by rnveach** [comment]
@GabrielBercaru You should copy them to new directory and leave old ones where they are.

**Comment by romani** [comment]
fix is merged
