### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for ParentPad

### ISSUE THREAD

**Issue by sabaka** [checkstyle/checkstyle#4062]
subtask of #3891 .

do a copy of all test input files to separate folder for ParentPad .
Not any other Check should use new inputs.

**Comment by sabaka** [comment]
Preassigned to Sami Bilal: https://groups.google.com/forum/#!topic/checkstyle-devel/r7oUvEnF9cE

**Comment by sami5596** [comment]
I am on it

**Comment by sami5596** [comment]
Can you also provide me with a brief explanation of the issue?

**Comment by sami5596** [comment]
If we are to organize the checkstyle inputs by test for parentpad then we should start by making a directory for one single test like for example, for ParentPad if test name is ParentPadCheckTest then the directory would be 
**.../checks/design/ParentPad/** 
This directory will contain the ParentPadCheckTest as well as another directory i.e. Inputs
**.../checks/design/ParentPad/Inputs**
This directory will contain all the inputs that are to be used by the ParentPadCheckTest.

Now if we want to organize the inputs for the test in the Inputs folders we should simply rename the inputs as 
**Input_[AnyIdentifier]**
[] are just used for an example and should not be used in the final name of the input. 

Instead of [AnyIdentifier], we can use an ID or keep different names for different inputs in order to differentiate them from other inputs that are to be used by ParentPadCheckTest.

Once we have renamed the inputs for ParentPadCheckTest, we should start naming all the future inputs in the similar manner so that all required inputs for a test are kept together in one place.

**Comment by romani** [comment]
please look at commit https://github.com/checkstyle/checkstyle/commit/7fc36c4dbf90c0e880831c5055a11eb59fcf04e0 , there are bunch of similar issues fixed and merged, so please look at them as example .

**Comment by Kietzmann** [comment]
@sabaka 
Could you please approve this issue to pass my pull request by CI?
Thanks

**Comment by rnveach** [comment]
issue approved

**Comment by romani** [comment]
fix is merged
