### ISSUE TITLE
reevaluate tokens in google config for OperatorWrapCheck

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4122]
Taken from PR #4120 ,
When reviewing the tokens of OperatorWrapCheck, it is unclear if we should add the following tokens to google configuration.

>  "COLON", "TYPE_EXTENSION_AND"

We should review them and either add them to our google config or explain why they shouldn't be added in a comment.

**Comment by bossever** [comment]
I'm on it.

**Comment by bossever** [comment]
## `TYPE_EXTENSION_AND` Token
In Google Java Style Guide, Section [4.5.1 Where To Break](https://google.github.io/styleguide/javaguide.html#s4.5.1-line-wrapping-where-to-break), it is clearly mentioned that _"when a line is broken at a non-assignment operator the break comes before the symbol"_ and this also applies for an ampersand type bound (<T extends Foo & Bar>).

![image](https://user-images.githubusercontent.com/58329164/111031790-40c65080-842f-11eb-9c74-b96131bf5ebf.png)

________________________________________________________________________________________________

## `COLON` Token
The `COLON` token has multiple uses - 

**1. In a for-each loop, in an "assignment-operator-like" manner
2. In a conditional operator - `expression1 ? expression2 : expression3`
3. In a labelled `break` or `continue` statement**

**1. for-each loop**
In Google Java Style Guide, Section [4.5.1 Where To Break](https://google.github.io/styleguide/javaguide.html#s4.5.1-line-wrapping-where-to-break), the second point mentions
> When a line is broken at an assignment operator the break typically comes after the symbol, but either way is acceptable.
This also applies to the "assignment-operator-like" colon in an enhanced for ("foreach") statement.

**2. Conditional operator**
While the Google Style Guide mentions nothing about line wrapping after/before a colon in the conditional operator, it does mention that it is preferable to break at a higher syntactic level. However, in a conditional operator such as `expression1 ? expression2 : expression3`, the expressions `exoression2` and `expression3` seem to be at the same syntactic level. So we can't draw any conclusions in this case.

**3. Labelled `break` or `continue`**
It looks something like this - 

```java
 search:
        for (i = 0; i < arrayOfInts.length; i++) {
            for (j = 0; j < arrayOfInts[i].length; j++) {
                if (arrayOfInts[i][j] == searchfor) {
                    foundIt = true;
                    break search;
                }
            }
        }

```
The `break` statement in this case would break the outermost loop labelled `search`. In my exprience, labels in Java are very rarely used, and even when they are, there seems to be no need of line wrapping in a label. Even if we were to consider a scenario with line wrapping, it would be inconvenient to separate the colon from the label itself, and it would lead to confusion.
__________________________________________________________________________________________________

## Conclusion
In 2 out of 3 types of usages of the `COLON` token, it is advisable to line wrap after the token, rather than before. So I would suggest leaving out this token from the Google config.

**Comment by rnveach** [comment]
Fix was merged
