### ISSUE TITLE
RightCurly: Update logic for option ALONE and ALONE_OR_SINGLELINE to support handling METHOD_DEF and other such tokens without shouldStartLine

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#4231]
$ cat RightCurlyTest.java

    public class RightCurlyTest {
        public class TestClass {
            int method(int a) { 
        	    System.out.println(" "); return ++a; }   //line 4
        }
    }

     $ cat config.xml

     <?xml version="1.0"?>
     <!DOCTYPE module PUBLIC
              "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
              "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

    <module name="Checker">
        <property name="charset" value="UTF-8"/>
        <module name="TreeWalker">
             <module name="RightCurly">
                 <property name="option" value="ALONE"/>
                 <property name="shouldStartLine" value="false"/>
                 <property name="tokens" value="METHOD_DEF"/>
             </module>
        </module>
    </module>

    $ java -jar checkstyle-7.7-SNAPSHOT-all.jar -c config.xml RightCurlyTest.java
    Starting audit...
    Audit done.

---------------
I expected a violation at line 4 since the `rightCurly` pertaining to the `METHOD_DEF` isn't alone on line.

The issue seems to be with `isAloneOnLine` method which just checks if the `rightCurly` and the `leftCurly` and the 'nextToken` aren't on the same line.

**Comment by rnveach** [comment]
@ps-sp If you turn on `shouldStartLine`, a violation will show.

You are specifically telling it that the curly shouldn't start the line by turning the property off, so why should a violation still show?

**Comment by ps-sp** [comment]
@rnveach because option `Alone` says: 
>Represents the policy that the brace must be alone on the line
But it's not the only thing that's on line. Please correct me if I am interpreting it wrong

Also, as #4022 suggests, `shouldStartLine` needs to be taken off !

**Comment by rnveach** [comment]
@ps-sp until it is taken off and a better way is found, we should still obey what it's intended use is for.
yes, `option` is the main controller of the lines but I assume `shouldStartLine` was originally added to override `option` in some specific situation otherwise it has no use as `option` would always override it.

@romani @MEZk Your opinions?

**Comment by ps-sp** [comment]
@rnveach Yes, and to take `shouldStartLine` off perhaps the right way would be to fix method `isAloneOnLine` and that's what I was trying to point out. Perhaps that can be taken care of in issue 4022 itself or any of the issue blocking 4022 and this issue can be closed.

**Comment by MEZk** [comment]
@rnveach @ps-sp 
From my point of view there should be a violation in both cases (shouldStartLine = true and shouldStartLine = false). The option should not affect the behavior of the check. The title of the issue needs to be changed in order to state this fact. As we found one more case where shouldStartLine influences the check's behavior, I think that resolving of this issue will help us to deal with https://github.com/checkstyle/checkstyle/issues/4022.

**Comment by ps-sp** [comment]
@MEZk is this title okay ?

**Comment by MEZk** [comment]
@ps-sp 
Lets keep the title similar to https://github.com/checkstyle/checkstyle/issues/4057 . Both issues blocks https://github.com/checkstyle/checkstyle/issues/4022 .

**Comment by romani** [comment]
@ps-sp , I completely puzzled by this issue. Is it valid ? as we remove "shouldStartLine" what is the purpose of this issue?

**Comment by ps-sp** [comment]
@romani this issue looks to be a child of #4022 to keep the PR for #4022 short. I will be able to answer your queries better once I update #4247 .

**Comment by ps-sp** [comment]
@romani yeah this issue seems to be obsolete / redundant and may be was unnecessarily created. #4247 introduces test cases similar to the ones pointed in this issue. May be we can simply close this issue once #4022 is fixed.
