### ISSUE TITLE
Use Spotbugs tool in our build process

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4373]
https://github.com/spotbugs/spotbugs

we need to start to use it.

**Comment by Nimfadora** [comment]
@romani Are we intent to use spotbugs in parallel with FindBugs or instead of it? Cause in the doc said that:

> SpotBugs is the spiritual successor of FindBugs, carrying on from the point where it left off with support of its community.

So, all checks from FindBugs must be included in the spotbugs.
If we plan to use it in parallel with findbugs we should configure if its possible to do via Maven. Currently it doesn't have its own plugin. It relies on findbugs maven plugin. [Here is more about it](https://github.com/spotbugs/spotbugs/issues/8)
I guess, we can use hazendaz's solution for now, but there is no confidence it will be supported in future. And it could be a problem to update in future.

**Comment by romani** [comment]
> So, all checks from FindBugs must be included in the spotbugs.

must ...... it is not a true. It is just another tool and probably with big overlap to findbugs. Time will show what too is better and lives longer.

> I guess, we can use hazendaz's solution for now, but there is no confidence it will be supported in future. 

it is fine, as it become misbehave we always have option to disable it.

**Comment by Nimfadora** [comment]
@romani , I've applied spotbugs to our project and used our exclusions from findbugs. It looks like it didn't find nothing new:
````
[INFO] BugInstance size is 0
[INFO] Error size is 0
[INFO] No errors/warnings found
````

**Comment by romani** [comment]
@Nimfadora , please find out what new in this tool in comparison with findbugs.
After we merge support of it, please do one more PR with bad code to let us see violation from spotbugs.

By the way, we need to activate plugin in Travis validation, please  use the same build item/command as pmd&findbug

**Comment by romani** [comment]
fix is merged.

**Comment by ThrawnCA** [comment]
> I guess, we can use hazendaz's solution for now, but there is no confidence it will be supported in future.

The thing is, FindBugs hasn't had any support in quite a while :(

That's why SpotBugs exists, to continue community support.
