### ISSUE TITLE
ASTs should be appended with comment nodes only when javadoc checks are present. ASTs shouldn't be walked if there are no corresponding types of checks

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#4393]
Taken from this [comment](https://github.com/checkstyle/checkstyle/pull/4378#issuecomment-305086724). It seems that hidden comment nodes are appended and then the complete AST (with javadoc) is walked even when there are no javadoc checks. Calls to [walk](https://github.com/checkstyle/checkstyle/blob/de50d3465849b83d25910590e1f5f39a25fe6e2c/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L180-#L184) method shouldn't be made if corresponding checks are not there (ordinary - javadoc).

Here are the related [statistics](https://drive.google.com/open?id=0B4RBU0-G54TUUXI2QWRncFk2WkE). (produced using jprofiler).

_program arguments:_ `-c sun_checks.xml -o NUL contribution\checkstyle-tester\repositories\guava` 
_had removed all the checks which would lead to javadoc parsing, i.e checks which have `isCommentNodesRequired()` returning true_

**Comment by rnveach** [comment]
> https://github.com/checkstyle/checkstyle/blob/de50d3465849b83d25910590e1f5f39a25fe6e2c/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L180-#L184
> hidden comment nodes are appended and then the complete AST (with javadoc) is walked

Since this code is in TreeWalker, it has nothing to with Javadocs.
Javadocs aren't generated until we actually add a Javadoc check and reach a valid javadoc node in `visitToken` at https://github.com/checkstyle/checkstyle/blob/de50d3465849b83d25910590e1f5f39a25fe6e2c/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L268 . 
The code in question more closely relates to normal `AbstractChecks` that need to be comment aware, which return true from `isCommentNodesRequired` (like `TodoCommentCheck` and yes the Javadocs).

[Since we are already separating comment-aware checks and non-comment aware checks](https://github.com/checkstyle/checkstyle/blob/de50d3465849b83d25910590e1f5f39a25fe6e2c/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L76-L80), all we need to do is check if `commentChecks` is empty and skip the appending and walking.

This should be an patch, but I don't think it will be common for most users to not have atleast 1 of our comment-aware checks.

**Comment by romani** [comment]
@ps-sp , true to say it was originally designed to skip walk if no javadoc checks are used in config as it cause enormous performance hit - http://roman-ivanov.blogspot.com/2016/02/performance-problem-while-using-checks.html .

But looks like we addressed the most obvious part and missed that append action, walk will do nothing as there is no javadoc. So I presume you speak about optimization to avoid appending tokens. That is valid.

Please update issue title to  more clear on target of optimization. Please update description to show in details place of problem. In other case we need to prove issue by CLI.

in PR please put some values how much time this optimization reduce execution on guava project, with no google config withtout javadoc Checks.

@rnveach ,

>  but I don't think it will be common for most users to not have atleast 1 of our ~12 comment-aware checks and javadoc checks.

yes, but I usually recommend users to have two configurations -  for code and javadoc ; and run javadoc less frequently on code.

**Comment by rnveach** [comment]
> I usually recommend users to have two configurations - for code and javadoc 

@ps-sp [We can also skip processing ordinary run if `ordinaryChecks` is empty](https://github.com/checkstyle/checkstyle/blob/de50d3465849b83d25910590e1f5f39a25fe6e2c/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L180) for full comment configurations.

**Comment by ps-sp** [comment]
@romani @rnveach acknowledged.

**Comment by romani** [comment]
@rnveach 
 
> If absolutely no checks are specified, we should still do parse as a check that code is parsable by grammar.

that is not good for user. This is good for us only, but we always can use the most light Check to force parsing.
Lets skip parsing also if no Checks are defined, code for java and javadoc checks will be the same  - consistent.

**Comment by rnveach** [comment]
Fix is merged
