### ISSUE TITLE
pitest: increase mutation coverage for pitest-checkstyle-tree-walker profile to 100%

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4398]
We created pitest profiles for non-checks code in #4367. Currently, we should increase coverage for `pitest-checkstyle-tree-walker` profile up to 100%.
This issue is a subtask of #3708

Current threshold of `pitest-checkstyle-tree-walker` profile: 83

**Comment by romani** [comment]
@Nimfadora ,

> TreeWalker.java//lexer.setFilename(contents.getFileName());

lexer/parser is using getFilename when error in parsing is happening, try to feed parser with bad source file from lexer and syntax perspective to cover both cases.

> TreeWalker.java//lexer.setTreatAssertAsKeyword(true);
lexer.setTreatEnumAsKeyword(true);

looks like you need to feed a java file with "enum" and "assert" , as I see from his code Lexer do special processing of them in its code.

> ordinaryChecksResources.size() + commentChecksResources.size()

try to move them inside Hashset c-tor, if still a problem, remove this line completely.

> isPositionGreater

it might be related to cases where you put `/**/` at all places in class , instead of all space. 
Try to change in big input file all spaces to `/**/` and see a coverage. If covered, minimize input file and ... . If not covered , add to suppress.

> countLinesColumns

related to javadoc Checks, you need to run javadoc Checks that are based on AbstractJavadocCheck to see effect.

**Comment by romani** [comment]
profile is set to 100%, but issue is not done yet as there a lot of `excludedMethods` .

**Comment by romani** [comment]
Final fix is merged
