### ISSUE TITLE
IllegalType: support arrays as types

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4429]
taken from #4425
But imagine that use want to forbid only "Boolean[][]" and allow "Boolean" in the same time.

```
$ cat TestClass.java 
public class TestClass {
    private Boolean[][] x;
}

$ java -jar checkstyle-7.6.1-all.jar -T TestClass.java 
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> TestClass [1:13]
`--OBJBLOCK -> OBJBLOCK [1:23]
    |--LCURLY -> { [1:23]
    |--VARIABLE_DEF -> VARIABLE_DEF [2:4]
    |   |--MODIFIERS -> MODIFIERS [2:4]
    |   |   `--LITERAL_PRIVATE -> private [2:4]
    |   |--TYPE -> TYPE [2:21]
    |   |   `--ARRAY_DECLARATOR -> [ [2:21]
    |   |       |--ARRAY_DECLARATOR -> [ [2:19]
    |   |       |   |--IDENT -> Boolean [2:12]
    |   |       |   `--RBRACK -> ] [2:20]
    |   |       `--RBRACK -> ] [2:22]
    |   |--IDENT -> x [2:24]
    |   `--SEMI -> ; [2:25]
    `--RCURLY -> } [3:0]
```

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java#L319
We do special exclusion of array braces - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtils.java#L77

We do not support for now non simple types: array and generics.
Should add support of them? it is big question, as it will force us to parse user input to analyse what did he mean.
May be we can do only arrays, it is more simple.

Clarification:
This issue is about treating Boolean and Boolean[] and Boolean and Boolean[][] as different types.
#4425 is about treating Boolean[] the same as Boolean[][].

**Comment by romani** [comment]
@rnveach , please share your position on this issue.

**Comment by rnveach** [comment]
@romani Just to confirm, since I am not clearly seeing the difference between this issue and other. This issue is about separately identifying `Boolean` and `Boolean[]` while #4425 is about treating them the same?

I see no reason why not supporting handling them differently so user can exclude one and not the other.

**Comment by romani** [comment]
> This issue is about separately identifying Boolean and Boolean[]

yes.

> while #4425 is about treating them the same?

no, ..... to treat `Boolean[]` the same as `Boolean[][]`

**Comment by rnveach** [comment]
@romani thanks for clarification. I still no reason why we shouldn't give user more flexibility on the type, with or without braces.

**Comment by sergileon** [comment]
@romani, What do you need to do with the task, except [PR](https://github.com/checkstyle/checkstyle/pull/5073)? I added new functional, tests. I think no change documentation, because now `IllegalType` work how description in [documentation](http://checkstyle.sourceforge.net/config_coding.html#IllegalType).

**Comment by romani** [comment]
> What do you need to do with the issue, except PR?

I do not understand question, please rephrase.

**Comment by rnveach** [comment]
Fix was merged
