### ISSUE TITLE
Replace terms in AST Tokens by terms from HTML specification

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4448]
documentation was changed at #3218

https://www.w3.org/TR/html4/
beginning/closing tag -> start/end tag
singleton tag -> empty tag

Reason: it is better to keep terminology of specification and to break before it become public.

Expected fix:
- rename in javadoc grammar (
        singletonTag --> emptyTag ; 
        OPEN --> START; CLOSE --> END;
        xxxxOpen --> xxxxStart; xxxxClose --> xxxxEnd;
        *_OPEN -> _START; *_CLOSE -> _END
)
- renames is AST trees in xdoc files.

**Comment by Vladlis** [comment]
@romani 
Should this issue be a part of GSoC project https://github.com/checkstyle/checkstyle/projects/4 ?

**Comment by romani** [comment]
@Vladlis , yes, it should be part of GSoC project.

**Comment by ps-sp** [comment]
@romani 
`singletonElement` can be renamed to `voidElement` as seen here: https://www.w3.org/TR/html51/syntax.html#void-elements

**Comment by Vladlis** [comment]
@ps-sp yes, I think it should be

**Comment by romani** [comment]
> singletonElement can be renamed to voidElement as seen here

yes, it has to be renamed. BUT in description I mentioned it as:
`singleton tag -> empty tag`, please provide investigation report on what term we should use "empty" vs "void"

**Comment by ps-sp** [comment]
@romani 
Got it.

**Comment by ps-sp** [comment]
@romani @Vladlis 

### **TOPIC**: To support [`singletonTag`](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L782) rule or not.

**FYI:** self-closing tags are used to refer to tags which don't have an end token and end with `SLASH_CLOSE; .../>`. As per our current grammar both [`singletonTag`](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L782) rule and [`singletonElement`](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L765) qualify as self-closing. 

Looking at the standard at https://www.w3.org/TR/html5/syntax.html#parsing, this is how things apparently work in relation with self-closing tags _(like `<p/>, <li/>`;)_ :

**1.** When `<` is encountered in [data-state](https://www.w3.org/TR/html5/syntax.html#data-state), switch is supposed to be made to [tag-open-state](https://www.w3.org/TR/html5/syntax.html#tag-open-state). **(these states resemble to the modes in ANTLR grammar)**

**2.** In [tag-open-state](https://www.w3.org/TR/html5/syntax.html#tag-open-state), after processing ASCII characters _(uppercase or lowercase)_ switche is to be made to [tag-name-state](https://www.w3.org/TR/html5/syntax.html#tag-name-state).

**3.** In [tag-name-state](https://www.w3.org/TR/html5/syntax.html#tag-name-state) when `/` is encountered, switch is made to [self-closing-start-tag-state](https://www.w3.org/TR/html5/syntax.html#self-closing-start-tag-state) and sets the `self-closing` flag as soon as `>` is encountered.

### **NOW THE CATCH:**

The way in which the standard specifies to [acknowledge-self-closing-flag](https://www.w3.org/TR/html5/syntax.html#acknowledge-self-closing-flag). If you go through that documentation _(or look at the note in [this section on html.spec.whatwg.org](https://html.spec.whatwg.org/#parse-error-non-void-html-element-start-tag-with-trailing-solidus) )_ you would realize that only [void-elements](https://www.w3.org/TR/html5/syntax.html#void-elements) and only [foreign-elements](https://www.w3.org/TR/html5/syntax.html#foreign-elements) are allowed to have `self-closing` flag set. Having any other self-closing tag is **parse error**. The way parse error has been defined on that page:

>This specification defines the parsing rules for HTML documents, whether they are syntactically correct or not. Certain points in the parsing algorithm are said to be parse errors. The error handling for parse errors is well-defined (that's the processing rules described throughout this specification), but user agents, while parsing an HTML document, may abort the parser at the first parse error that they encounter for which they do not wish to apply the rules described in this specification.
<br>

I was able to find the way the parser is supposed to behave in such cases on: https://html.spec.whatwg.org/#parse-error-non-void-html-element-start-tag-with-trailing-solidus, which too is official doc page. Quoting from that page:

>This error occurs if the parser encounters a start tag for an element that is not in the list of void elements or is not a part of foreign content (i.e., not an SVG or MathML element) that has a U+002F (/) code point right before the closing U+003E (>) code point. The parser behaves as if the U+002F (/) is not present.
<br>

So we are supporting something that specification suggests should either be ignored or result in parse error in form of `singletonTag`.

### **Javadoc tool doesn't properly support self-closing tag either**

Example can be seen [here](https://gist.github.com/ps-sp/1dedcb8657e88f175d7ba903bdb29609). As can be seen in the logs provided both the self-closing tags provided in javadoc yield errors. **But, the site rendered has links working** as you can check for yourself by executing the javadoc tool on the file. Closing the tags properly makes the errors go away.

###**SOLUTION 1:** 
No need to separately support `singletonTag` and the `/` in `singletonTag`s can be ignored as specification recommends and inputs like `<p/>, <li/> ...` can be included in corresponding `...TagOpen` rules.

###**SOLUTION 2:**
Continue supporting `singletonTags` as we do. Though I don't think they should be called `void` since `void-elements` is used to refer to only particular tags. We can call them `selfClosingTag` or `otherSelfClosingTag` or something like that. But again, supporting these is against the standard and the javadoc tool.

**Comment by Vladlis** [comment]
> So, in form of singletonTag, we are supporting something that specification suggests should either be ignored or result in parse error.

and also SVG or MathML, right?

> Example can be seen here. As can be seen in the logs provided both the self-closing tags provided in javadoc yield errors.

You are referring html5 doc whereas javadoc tool supports only html4 until java9.

> SOLUTION 1:
No need to separately support `singletonTag` and the `/` in `singletonTags` can be ignored as specification recommends and inputs like `<p/>, <li/> ...` can be included in corresponding `...TagOpen` rules.

Won't this make inputs like `<p/>some text</p>` possible? It is unacceptable.

I think we need to continue supporting `singletonTag` and `singletonElement` so we don't need to support all tags from SVG and MathML. And yes, we cannot rename `singletonTag` to `voidTag` because it is not always a void tag. We could make a separate rule `voidTag` with only void tags inside, but in html5 these tags are also self-closing and we are going to support html5 here https://github.com/checkstyle/checkstyle/issues/3332.
So I think that **second** option is what we need, but renaming should be done in scope of https://github.com/checkstyle/checkstyle/issues/3332.

**Comment by Vladlis** [comment]
> Example can be seen here. As can be seen in the logs provided both the self-closing tags provided in javadoc yield errors.
>
> You are referring html5 doc whereas javadoc tool supports only html4 until java9.

Sorry, tags in example are not supported as self-closing in html5 either, only void, SVG and MathML tags. Looks like we have another issue - `singletonTag` should not allow anything apart from `HTML_TAG_NAME`, because `<p/>` is not correct as well as the others listed in this rule. Please create a new issue if you agree.

**Comment by ps-sp** [comment]
>and also SVG or MathML, right?

SVG and MathML tags can be self-closing right ?

>Won't this make inputs like <p/>some text</p> possible? It is unacceptable.

I agree. But just fyi, Inputs like `<b/> bold </b>` result in bold texts in javadoc.

>I think we need to continue supporting singletonTag and singletonElement so we don't need to support all tags from SVG and MathML.

The topic says _to support singletonTag rule or not_. But if you see all I am trying to say that we shouldn't support tags that are not supposed to be self-closing i.e these elements in [JavadocParser.g4#L785-#L799](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L785-#L799) in `singletonTag` rule. We of course do want to support tags that can rightfully be self-closing.

_I have updated the TOPIC header in previous comment now_.

>Please create a new issue if you agree.

Issue #4827

**Comment by rnveach** [comment]
@Vladlis @ps-sp Is there more to do in this issue?

**Comment by Vladlis** [comment]
@rnveach 
I suppose the rest of questions is moved to the other existing/new issues, so I am closing this one.
