### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by eimperat** [checkstyle/checkstyle#4477]
it appears that this change
https://github.com/checkstyle/checkstyle/commit/bfed57cdc87c736661d743222f1b64062b6a84d4
intentionally breaks thread safety of the checkstyle plugin
Maven lists the plugin as known to be thread safe, since version 2.6, albeit being a dated page
https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3

is this intentional? if so this seems to be a step backwards, as maven builds now fail with a -T flag since upgrading from v7.2

please investigate and reconsider, it seemed threading was working properly up until this change

**Comment by romani** [comment]
> is this intentional? 

yes, it is intentional.

Checkstyle is not thread safe by design. All abilities to run in MultuThread mode is just a luck.
after this commit we removed illusion that we are safe.
MT implementation will be done at the end of summer (if it pass testing).

> it seemed threading was working properly up until this change

I doubt, it was just matter of luck. Unfortunately Checkstyle is not thread safe. All incomplete code for MT mode was removed, to let us make new implementation.
