### ISSUE TITLE
idea: third part of violations

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4713]
sub-task of #4681

too widespread to be included to the report:
Duplicate String Literal **8645**
Hard coded strings **11888**
String concatenation **9477**
Single class import **4567**
Static import **705**

[report on all other violations](https://nimfadora.github.io/idea/suppressed_3_part.html)

violations included:
```
AbstractClassExtendsConcreteClass
BooleanMethodIsAlwaysInverted
BooleanVariableAlwaysNegated
BreakStatement
ContinueStatement
CyclicClassDependency
CyclicPackageDependency
DuplicateStringLiteralInspection
EmptyMethod
ErrorRethrown
HardCodedStringLiteral
IfMayBeConditional
LawOfDemeter
MagicCharacter
NonThreadSafeLazyInitialization
PublicInnerClass
SameParameterValue
SameReturnValue
SingleClassImport
StaticImport
StringConcatenation
NestedTryStatement
ProtectedField
ProtectedInnerClass
AssignmentToForLoopParameter
ForLoopWithMissingComponent
CheckedExceptionClass
ExtendsConcreteCollection
StaticVariableInitialization
StaticVariableUninitializedUse
```

**Comment by romani** [comment]
> Duplicate String Literal

suppress: it will result in too much dependencies between classes, some case are only have the same value by chance, too much wont-fixes.

**Comment by romani** [comment]
> AssignmentToForLoopParameter

need to refactored to "while"

> BreakStatement

suppress: "we like breaks to be in code"

> ContinueStatement

suppress: "we like continue statements to be in code"

> ForLoopWithMissingComponent

activate the only option in it, all violations that are left should be addressed.

> IfMayBeConditional

suppress: "we do not conditional expressions, we like more verbose code"

> BooleanMethodIsAlwaysInverted
BooleanVariableAlwaysNegated

suppress: "even it is always negated, it is better than possible negation/inversion of negated term"

> LawOfDemeter

suppress: "it is impossible to follow this Law for us as most violation are caused by fact that we do logic not only on token that come to visitToken, but by extra traversing over subtree"

**Comment by Nimfadora** [comment]
@romani  after merge of the last pull request task may be closed, all violations are fixed

**Comment by Nimfadora** [comment]
@romani task may be closed, all violations are fixed
