### ISSUE TITLE
remove AbstractTypeAwareCheck from Chekstyle

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#473]
Checkstyle is not type aware tool, so till we implement smth stable in that area of validation - all Checks derived from AbstractTypeAwareCheck should be removed.
Example of really buggy Check: RedundantThrowsCheck.java

**Comment by BoyuanYan** [comment]
But how can I fix the problem caused by RedundantThrows? Just remove it from my checks.xml?

**Comment by romani** [comment]
@BoyuanYan, yes, just remove it from configuration file.

**Comment by gunnarmorling** [comment]
FWIW, removing `RedundantThrows` in a minor release such as 6.2 was a bit of an unfortunate move. IMHO, it would have been much better to e.g. make it a no-op and raise a warning that this check is no longer supported and will be removed in a future release such as 7.

Due to the removal you now get the rather unspecific error "cannot initialize module TreeWalker - Unable to instantiate RedundantThrows". It's not exactly straight forward to come to the conclusion that this check just does not exist any longer. Also note that this comes to the surprise of users of the CS Eclipse plug-in which get a very annoying build failure due to that when using recent versions of the plug-in.

I recommend to do a Google search for that error message and you'll see many people are having trouble by this. Personally I think a library should keep this sort of pain away from users by moving forward in a sensible backwards compatible manner and rather raise a meaningful deprecation message in such cases. E.g. it could state: "The RedundantThrows check is deprecated and has become a no-op as of CS release 6.2. It should not be used any longer in checkstyle.xml configurations. The check will be removed in the next CS major release." That way a user clearly knows what's happening and how to react.

**Comment by amahdy** [comment]
I do agree with @gunnarmorling

**Comment by romani** [comment]
> removing RedundantThrows in a minor release such as 6.2 was a bit of an unfortunate move. 

yes, it is not as in all other projects. But Checkstyle have huge expose(api, check names, their options) to public and almost and changes in should be considered as major release (and minor dump only for bugfixing.).

So I decided to keep major version to major update -  changes in AST tree structure, serious API changes.
Minor version will contain braking compatibility too, but minor braking - changes in Names of Checks and options, minor API deprecations/substitutions, Changes in checks algorithms, changes in default values. 
Third version - bug fixing.


> "The RedundantThrows check is deprecated and has become a no-op as of CS release 6.2. It should not be used any longer in checkstyle.xml configurations. The check will be removed in the next CS major release."

that is good idea,  I will try to remember to put some logic to Check Loader to print smth like that to user but without "will" - "..... The check was removed in the CS 6.X release."
