### ISSUE TITLE
Intellij Idea inspection from 2017.2.4 or 2017.2.6

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5069]
1) request TC support to upload 2017.2.4 binaries to web service
2) Resolve all new inspection problems from IDEA 2017.2.4 and with update in TC to the same version of inspections.

update to code could done in branch and wait till TC web service upload inspection binaries.

attention: update only TC or resolving inspection violation could cause problems like "redundant suppress"

**Comment by romani** [comment]
TC team uploaded 2017.2.4 version, we could start to use it.

**Comment by rnveach** [comment]
@romani 
> we could start to use it.

How do we switch TC to this new version?

**Comment by romani** [comment]
I need to do switch in TC settings.
I could do it ones, copy report and return it back till we resolve most. Ones most is done, I activate required version in TC and fix it quickly.

Does it works for you ?

**Comment by rnveach** [comment]
This sounds fine.
I opened an issue for 2017.3 and am fixing ones my local IntelliJ report there.
Let's wait until I resolve most of those before upgrading TC. Should be 2-3 PRs.

**Comment by rnveach** [comment]
@romani Please do upgrade.

**Comment by romani** [comment]
Master branch updated to 2017.2.6 , build is relaunched

**Comment by romani** [comment]
the same violations on 2017.2.4 in  TC.

So I am reverting TC back to 2017.1.5

**Comment by romani** [comment]
@rnveach , do you see such violations on your side ?

**Comment by rnveach** [comment]
@romani These violations were talked about at https://github.com/checkstyle/checkstyle/issues/5409#issuecomment-354586887 and https://github.com/checkstyle/checkstyle/issues/5409#issuecomment-355715454 .
I do see them and they can't be fixed until TC is violating on them so we can be allowed to suppress them. Otherwise old TC will complain about the new suppressions since it isn't printing violations on these new areas.
https://github.com/checkstyle/checkstyle/issues/5409#issuecomment-355715454 addressed my reasoning why I say they can't be fixed. If you agree, they must be suppressed.

I don't see how we can fix them unless we leave new TC version and fix them in new PRs.
Please let me know what you want me to do.

**Comment by romani** [comment]
please send PR, I will setup new IDEA version only for your PR.

**Comment by romani** [comment]
TC is switched to 2017.2.6 for PR and master builds.

**Comment by romani** [comment]
I reopen it as I still need to report issues IDEA and put such issues to explanation of suppress.

**Comment by romani** [comment]
WeakerAccess - https://youtrack.jetbrains.com/issue/IDEA-187208
