### ISSUE TITLE
JavadocTokenTypes should keep values of tokens

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5139]
create GeneratedJavadocTokenTypesTest.
see java analog - https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/grammars/GeneratedJavaTokenTypesTest.java

it is required to avoid serious compatibility problems, as static values are compiled as inlined values in other projects, changes in numbers will cause serious damage to Checks behavior. 

See example of compatibility problems at #505 .

checkstyle/target/generated-sources/antlr/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.java

There is no compatibility damage between 8.0 and 8.1.

compatibility damage between 8.1 and 8.2:
![image](https://user-images.githubusercontent.com/812984/30776369-cdb17c1c-a059-11e7-8a91-76ed00fdd283.png)

compatibility damage between 8.2 and 8.3-SNAPSHOT:
![image](https://user-images.githubusercontent.com/812984/30776374-03366262-a05a-11e7-8d6a-32e85a794a9c.png)

We need to restore token values to 8.1 state finally.
as first step we can enforce values that we have in 8.3-SNAPSHOT now.

**Comment by romani** [comment]
@ps-sp , please help us to address this ASAP, we are at serious compatibility problem.
Please send PR with enforcing 8.3-SPANSHOT values, not allow further regression from PRs. 
We need to restore values as it was before, change in names is not a problem.
 
@Vladlis , FYI.

**Comment by rnveach** [comment]
Please also add a UT similar to https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/grammars/GeneratedJavaTokenTypesTest.java#L43 to make sure we don't break compatibility again.

**Comment by ps-sp** [comment]
@romani 
Sorry for the delay. I will try to get things done as soon as possible, bit occupied at the moment, sorry.

**Comment by romani** [comment]
issue for UT creation is created - #5186

**Comment by romani** [comment]
@ps-sp ,
thanks a lot for fix at #5186 

and now .... can we restore to previous values , as they were at 8.1 version ?

**Comment by ps-sp** [comment]
@romani @Vladlis @rnveach 

Right now I can't see any _graceful_ way to override the token and rule numbers generated by ANTLR since apparently there's no mechanism provided by ANTLR to naturally override the order of generation of token or rule numbers.

ANTLR seems to generate token or rule numbers in the order in which it encounters the corresponding elements in the grammar. So new tokens and new rules can be added at the end of the grammar to preserve the previous numberings **but** if one wishes to append to an existing rule, like in #3332 for example, then all the rule numbers beyond that rule shall change. Same goes if one has to delete a token, though this can may be worked around by removing all the token uses from parser grammar and letting its definition stay in the lexer grammar. Anyway, the point is that there can be some certain kind of updates to grammar in which we may not be able to _naturally_ preserve token and rule numbers.

That said, one way I can think of to overcome this is by completely decoupling `JavadocTokenTypes` from the parser generated token and rule numbers. We can hard code the constants in `JavadocTokenTypes` and map the corresponding token and rule numbers in the generated class `JavadocParser` to their corresponding values in `JavadocTokenTypes`. We can do this mapping either via reflection or explicitly. This way we will be able to have complete control over the token numbers we provide to the users. We will need to update the `getType` and `setType` methods in `DetailNode` implementation accordingly.

What do you guys think ?

**Comment by romani** [comment]
> So new tokens and new rules can be added at the end of the grammar to preserve the previous numberings but if one wishes to append to an existing rule, like in #3332 for example, then all the rule numbers beyond that rule shall change.

please give a link to update where new grammar elements has to be added in the middle of grammar, not to the end of grammar.
Decoupling is last resort approach only.

**Comment by ps-sp** [comment]
@romani 

Ohh wait. For example in #4943 when `embed` tag was [added as an alternative to an existing rule](https://github.com/checkstyle/checkstyle/pull/4943/files#diff-dc341f0403799db1d0f9788f72c8a4f4R817), I (wrongly)thought that it might change the rule numbers but that might not be the case. Let me have a look again and get back to you.

**Comment by rnveach** [comment]
Fix was merged

**Comment by Vladlis** [comment]
@ps-sp Thanks!

**Comment by romani** [comment]
We have two options:
1) leave breaking compatibility tat we already caused. And force all thirparty javadoc Checks to recompile. But be careful in future with grammar updates and make decision later on, when we come to case that will force us to decouple Tokens.

2)Looks like decoupling TokenTypes from ParserTokens is only way out. We should use map function after parsing to convert tree to TokenTypes from ParserTokens.

I do not see another solutions.

@ps-sp , @rnveach , @Vladlis , please share your thoughts .... what approach it better for you?

I am more in favor of "1)", I doubt that there are a lot of thirparty Checks in the works now, javadoc processing is not that mature. We changed grammar a lot, and no body complained :), it kind of mean nobody use .... so is not a breaking compatibility :).
So we will just close this issue ... I put label "breaking compatiblity" of issue that introduced this regression at 8.1 and we close all issues. Existing PR should be closed, sorry to not to merge, but it helped us to understand a lot of stuff. @ps-sp ,thanks you very much , no matter what.

**Comment by rnveach** [comment]
> Looks like decoupling TokenTypes from ParserTokens is only way out. We should use map function after parsing to convert tree to TokenTypes from ParserTokens.
> Looks like 2) is the only way out.

We have already started this in https://github.com/checkstyle/checkstyle/pull/5455 with the method `getJavadocTokenType`.

**Comment by rnveach** [comment]
this issue will be dropped for https://github.com/checkstyle/checkstyle/issues/5880

**Comment by romani** [comment]
This issue was closed as we introduced one more damage to JavadocTokenTypes at PR #5101 (Issue  #3332). No sense to restore to 8.1 tokens.
Unfortunately all affected extensions should be recompiled.
