### ISSUE TITLE
Provide empty FileContentsHolder module for deprecation transition

### ISSUE THREAD

**Issue by baron1405** [checkstyle/checkstyle#5187]
The removal of the FileContentsHolder module in CheckStyle 8.2 caused the developers in our enterprise to have failed builds and errors in their IDEs. Given the number of developers we have, it is not possible to quickly accommodate such a sudden change. Can you put back the FileContentsHolder as an empty module, and issue a deprecation warning when it is found. This will give developers time to update their configuration files.

In terms of versioning, it would be helpful to change the major version of CheckStyle when breaking changes are made (i.e. changes that will cause existing configuration files to no longer be successfully parsed). For example, the release where the FileContentsHolder module is removed would be 9.0 rather than 8.2.

**Comment by romani** [comment]
Sorry that we did serious damage to functionality without providing alternative for all.

> Can you put back the FileContentsHolder as an empty module, and issue a deprecation warning when it is found.

Severity(what you meant by "warning") is configurable by users. We have violations.
We do not have functionality to report config problems, rather than fail execution.

> This will give developers time to update their configuration files.

You need to provide a bit more details on how you do migration from version to version.
If we by some imaginary way can raise a warning, there is no guaranty that it will be fixed. Just another violation from checkstyle....
Empty functionality will not crash execution but will produce a lot false-positives. We follow "fail-fast" model.
Any upgrade could make a problems, so migration should always be by dry-run/check first before apply for whole enterprise.
If you can not upgrade, do not upgrade and stay on version that satisfy your enterprise till your issue is resolved.

> In terms of versioning, it would be helpful to change the major version of CheckStyle when breaking changes are made

http://checkstyle.sourceforge.net/#Development_Circle, there is link to issue where all is explained. Sorry that is not done in very intuitive way.

@MEZk , please share your plans to restore user ability to suppress violations from FileSet Checks.

**Comment by baron1405** [comment]
Thanks, @romani for the detailed and thoughtful reply! We use CheckStyle directly in our builds and through the CheckStyle-IDEA plugin in IntelliJ IDEA. We conduct qualification testing of new versions of CheckStyle (especially in the IDE) but accommodating breaking changes can be very challenging. We have over 5000 projects throughout our org and getting each to update their CheckStyle configuration file to accommodate a new version of CheckStyle is not a quick process. Based on what you described above, we probably need to completely rethink how we work with CheckStyle so that we are much more conservative and assume that every release will break compatibility.

**Comment by MEZk** [comment]
@romani 
I sent PR https://github.com/checkstyle/checkstyle/pull/5213 which adds SuppressWithPlainTextCommentFilter which allows to suppress violations from FileSet Checks.

**Comment by romani** [comment]
@baron1405, sorry that we make so much problems for you. We postponed such baking changes for 3 years, to provide community hundreds of bug fixes, without serious compatibility problems.

> every release will break compatibility.

in next 8.X releases I think there will be braking changes in each release. We try to be very accurate in releasenotes generations, so you can trust our release notes grouping: "Breaking backward compatibility", "New", .... .
If you have some big project in opensource and checkstyle is enforced over it with no errors/warnings we can add your project in our CI , so you will be alarmed in advance.

> We have over 5000 projects throughout our org and getting each to update their CheckStyle configuration file to accommodate a new version of CheckStyle is not a quick process.

if you see how we can improve users migration process , please share ideas.
