### ISSUE TITLE
Convert sevntu-checkstyle-check to ant run

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5385]
See https://issues.apache.org/jira/browse/MCHECKSTYLE-346 .
We need to deprecate all usage of `maven-checkstyle-plugin` so we can start implementing backward breaking changes.

We must convert our `sevntu-checkstyle-check` run to an ant run.
Specified section: https://github.com/checkstyle/checkstyle/blob/06ff5677fa5a19afe3f55078fff79ead61068a51/pom.xml#L558-L597

**Comment by romani** [comment]
this was  interesting hack a while ago, as it make self dependency of snapshot checkstyle to previous checkstyle version `${maven.sevntu-checkstyle-check.checkstyle.version}`.

It was not done as ANT, only because I personally do not like ANT at all, so I try to minimize its usage as much as reasonable. May be is it a reason to make it by ANT....

lets come initial reasons ...

@rnveach , what force us to migrate from maven-checkstyle-plugin here ?
braking changes like at #5324 , was not detected by this validation....
so to make it clear "we must" or "we should" migrate.

**Comment by rnveach** [comment]
> braking changes like at #5324 , was not detected by this validation....

This maven plugin run doesn't use snapshot version of checkstyle. If we used snapshot version, problem would be the same. This is why we only saw issues in wercker, as wercker used maven plugin with snapshot version.

If we leave this area the same, it will be broken once we release and try to upgrade our project to new Checkstyle version.

**Comment by romani** [comment]
Ok, make sense.
I am ok with change, but ant is not an option, we can use maven exec plugin to run validation as by cli execution. It might be easier to setup, it will be based on release version of checkstyle again.
If you are ok, please remove ant from title and let's keep it as option of implementation.

**Comment by nrmancuso** [comment]
Closed via #12346
