### ISSUE TITLE
Jacoco coverage report

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5516]
Base conversation: https://groups.google.com/forum/#!topic/checkstyle-devel/KnPfFZZiumA

There are a lot of problems with Cobertura, it is kind of dead. It hasn't been updated since 2015.
One possible replacement is [Jacoco](https://github.com/jacoco/jacoco).

Recent release (very long awaited) [v0.8.0](https://github.com/jacoco/jacoco/releases/tag/v0.8.0) has all the required features for us to give it one more chance.

**Comment by romani** [comment]
related issue #1173

**Comment by rnveach** [comment]
I played around with restoring the jacoco a while ago when we were starting to have issues with cobertura.
https://github.com/rnveach/checkstyle/commits/jacoco

**Comment by romani** [comment]
@pbludov , should we create separate issues for all items to fix coverage to 100% ? or you plan to do this in scope of this issue.

**Comment by pbludov** [comment]
I'm going to send a minor PR for each case. We should discuss them separately.

**Comment by pbludov** [comment]
The last one, `com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser.JavadocParserErrorStrategy` is a `private` `static` `class`, so it can't be easily mocked.  It has only two lines of code and the second line is not covered since the `BailErrorStrategy.recoverInline` method always throws an exception.
It is better to leave the suppression as is.

**Comment by rnveach** [comment]
@pbludov @romani 
I just happened to think of this. We also use pitest as a secondary code coverage test. It is one of its requirements that must succeed before it begins mutation.
What code coverage library does pitest use?

Also we should create an issue for dropping cobertura, defining when we will decide to go and what we will be removing.
There are import controls that are restricted because of cobertura issues. https://github.com/checkstyle/checkstyle/blob/master/config/import-control.xml#L19

**Comment by pbludov** [comment]
@rnveach try-with-resource is also forbidden due to incompatibility with Cobertura.
There will still be a lot of work after the Cobertura will be gone.
