### ISSUE TITLE
CI: spellchecker script is not ready for running manually by contributors

### ISSUE THREAD

**Issue by daniilyar** [checkstyle/checkstyle#6021]
The spellchecker script (`.ci/test-spelling-unknown-words.sh`) has few issues that makes it failing on most popular platforms that Checkstyle contributors use.

For example, it fails on 
Debian, 
~~MacOS~~ fixed in #6348
 ~~and Windows (all versions of above)~~ - shell scripts are not for Windows by design.

Also, this script does not care about relative paths handling, error handling and has bad logging.

We need to redesign it so it becomes easy to use by contributors.

Some issues found so far:
1. Script only works when executed from git repo root folder and fail from anywhere else:
```
.ci/test-spelling-unknown-words.sh - works
cd .ci && ./test-spelling-unknown-words.sh - fails
xxx/checkstyle/.ci/test-spelling-unknown-words.sh - fails
```
It lacks proper quotation around path arguments so it fails on any catalog with spaces in name.

2. Scripts has bad logging and error handling. See the example log below from Debian Stretch - it will tell everything better than all words:
```
$ bash .ci/test-spelling-unknown-words.sh
...
Run w
Experimental keys on scalar is now forbidden at /home/dyaroslavtsev/Desktop/Code/opensource/checkstyle/daniilyar/checkstyle/.ci/jsoref-spellchecker/spelling-unknown-word-splitter.pl line 37.
Experimental keys on scalar is now forbidden at /home/dyaroslavtsev/Desktop/Code/opensource/checkstyle/daniilyar/checkstyle/.ci/jsoref-spellchecker/spelling-unknown-word-splitter.pl line 37.
xargs: /home/dyaroslavtsev/Desktop/Code/opensource/checkstyle/daniilyar/checkstyle/.ci/jsoref-spellchecker/spelling-unknown-word-splitter.pl: exited with status 255; aborting
Review results
There are now fewer misspellings than before.
...
``` 
Especially notice the exit with 255 status line in the middle. That is a critical error which breaks the logic which should stop the processing with human readable error message, but is doesn't

~~3. Script sleeps for 5 sec before exiting without the clear reason~~ - by design, required for Travis.

**Comment by daniilyar** [comment]
This script is one of the most often failing ones, so I believe that making it easier to use will save contributors and project owners a lot of time

**Comment by pbludov** [comment]
> Script does not support any OS that doesn't use rpm because it has a hardcoded rpm package dependency

The script loads the "dependency" with curl and extracts it using unzip. It works great in Travis, which is Ubuntu based. No RPM-based package manager is required.

**Comment by romani** [comment]
> Scriptonly works when executed from git repo root folder and fail from anywhere else:

this is nuance for all scripts, it would be awesome to update all to work from any places.

> Script lacks proper quotation around path arguments so it fails on any catalog with spaces in name.

one day ... #5826 will be enforced.

> Script does not support any OS that doesn't us rpm because it has a hardcoded rpm package dependency

:) do not dream about support of all OSs, please update it for your cases and that is enough for now.
It is better to fail with "rpm command not found" to let user know that "rpm" package need to be installed.
Please update script to print version of rpm or what ever to make failure more clear.

> Scripts has bad logging and error handling

Agree, design of this script of far from my expectations, I hate perl, BUT it did a job that was not feasible by any other tool. And author of is fixed all spelling mistakes in whole repo ... HUGE amount of typos.
So as treat it as-is .
One day we will implement Checkstyle Check for spelling, but it might stay to test spelling in non java code.


> It works great in Travis, which is Ubuntu based. No RPM-based package manager is required.

Danil use pure versions of debian. Travis use ubuntu based version but with a lot of tool installed (non-default tools). I use ubuntu 16.04 , and looks like I got rpm package a while ago for some other application or ... .

**Comment by daniilyar** [comment]
The script is also sleeping for 5 sec without reason :)

**Comment by daniilyar** [comment]
@pbludov, you are right about rpm, it seems that script doesn't directly call rpm, I missed it

**Comment by rnveach** [comment]
@daniilyar our scripts usually sleep 5 seconds before ending because when it exits it also stops travis console output so usually the end of the script cuts off and we don't know the reason for the failure.

**Comment by romani** [comment]
@jsoref , can you help us resolve this issue?
 to make usage of your script a bit more friendly for contributors.

**Comment by jsoref** [comment]
Sure.
* The experimental thing was https://github.com/jsoref/spelling/issues/6 which is fixed.
* MacOS was fixed by https://github.com/checkstyle/checkstyle/pull/6348 as noted
* I'm not sure why debian would complain about anything I'm doing, I suppose it's possible that rpm2cpio.sh is bashist.

I'm happy to address the path pinning if requested, however, as noted by https://github.com/checkstyle/checkstyle/issues/6021#issuecomment-403706343 this matches the rest of them. I'm pretty sure someone else could fix this at the same time.

It would be helpful if someone provided samples for the rest of the things.

In general, my scripts do tolerate spaces in them, they mostly use `hg locate -0` or `git ls-files -z`:
```sh
$ echo 'funn' > 'hello world'
$ .ci/test-spelling-unknown-words.sh
Clean up from previous run
Run w
Review results
No new words and misspellings found.
$ hg add hello\ world
$ .ci/test-spelling-unknown-words.sh
Clean up from previous run
Run w
Review results
New misspellings found, please review:
funn

If you are ok with the output of this run, you will need to
patch .ci/jsoref-spellchecker/whitelist.words <<EOF
@@ -483,2 +483,3 @@
 func
+funn
 Fwhitespace
EOF
```

I can offer a fix for the pipe case now...

**Comment by romani** [comment]
@daniilyar , please provide details.

**Comment by jsoref** [comment]
I've tested w/ current master on **Debian Stretch** w/ both **hg** and **git** and it seems to work fine in both the clean and dirty cases.

It currently fails silently if **curl** can't retrieve the directory index for the rpm file... (#6370)

If it can manage to get the index but not the file, it yields:
```
$ .ci/test-spelling-unknown-words.sh
Retrieve ./usr/share/dict/linux.words
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: rpmfind.net.localdomain
```
(Well, in this case, I've intentionally botched the domain in order to trigger the failure)

I think at this point, it's pretty good. If it can't decode the `.rpm`, the `rpm2cpio` script fails w/ a vaguely useful message (this mostly happens if one triggers a 404 and thus gets random html instead of an archive).

Note: If someone has a preferred wordlist, there's no need to use the rpm one. It's bigger than the **Darwin** list (**Apple**'s actual dictionary is elsewhere) and the **Debian** list.

**Comment by romani** [comment]
@jsoref , did you addressed all requested items from description ?
should we close the issue ?

> Script only works when executed from git repo root folder and fail from anywhere else

I doubt any other scripts follow this good practice, it is ok to skip this.

**Comment by jsoref** [comment]
I think so. But, it's really a question for @daniilyar

**Comment by romani** [comment]
I am closing this issue for now , it try to address too much items.

@daniilyar , if there still smth left, please create new issue.
