### ISSUE TITLE
Replacement for DoubleCheckedLocking check 

### ISSUE THREAD

**Issue by VaughanJackson** [checkstyle/checkstyle#6135]
According to this discussion on Stackoverflow https://stackoverflow.com/questions/13479021/double-checked-locking-disappeared-from-checkstyle-why, the DoubleCheckedLocking check was removed from CheckStyle because of the adoption of Java 1.5+.
However, the same discussion suggests the bug is still possible, just less likely in Java 1.5+.
I wonder whether the check should be updated and restored in CheckStyle?

**Comment by romani** [comment]
I do not remember exact reason ... but it might be removed due to problems win proper implementation of it. It might require to be type aware.

old implementation - https://github.com/checkstyle/checkstyle/blob/release5_5/src/checkstyle/com/puppycrawl/tools/checkstyle/checks/coding/DoubleCheckedLockingCheck.java

Checkstyle is is not type aware and there are bunch of limitations - https://checkstyle.org/writingchecks.html#Limitations

If you see how reliably implement logic, please be welcome to propose a solution.
There could be a lot of implementations of Double-Checked Locking pattern, so be prepared for a lot of case to support.

**Comment by VaughanJackson** [comment]
Thank you for putting me in the picture @romani. Food for thought. Not sure I want to get into something this open-ended right now!

**Comment by romani** [comment]
Closing as I do not see how to implement this reliably, if somebody come up with idea, let's reopen issue
