### ISSUE TITLE
sync content of cli tool in xdoc and cli tool help output 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6216]
identified at https://github.com/checkstyle/checkstyle/pull/6211#issuecomment-438958556

TODO:
1) We need to move content from xdoc to cli output all valuable details of how options works, looks like xdoc is more reach in explanations.

2) find way to generate content of xdoc section directly from cli tool output, to avoid manual sync in future. All hyperlinks that we use in xdoc is ok to sacrifice. Or place then in non-generated section.

**Comment by gaurabdg** [comment]
I am on it

**Comment by gaurabdg** [comment]
@romani @rnveach Since description attributes are supplied through annotations and they need to be compile time constant how do we plan to implement this. I did all the generation from xdoc content to hashmap in `Main.java` and then realized.
One option is if we refactor the code from annotation based model to a programmatic API based approach: https://picocli.info/picocli-programmatic-api.html

**Comment by romani** [comment]
> to a programmatic API based approach

I do not see a benefit, please explain.

-----

please do `2)` first, and `3)` as second step, it might be treaky.

**Comment by gaurabdg** [comment]
> > to a programmatic API based approach
> 
> I do not see a benefit, please explain.
> 
> please do `2)` first, and `3)` as second step, it might be treaky.

For `1)` a lot of refactoring has to be done, so it would be difficult.
@romani I have implemented the second approach only.

**Comment by romani** [comment]
fix is merged.
