### ISSUE TITLE
Review javadoc validations of eclipse compiler

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6342]
continuation of #5060 and #2600

Disabled validations:
`org.eclipse.jdt.core.compiler.problem.missingJavadocComments=ignore
org.eclipse.jdt.core.compiler.problem.missingJavadocTags=ignore`

Enabling these checks results in 4702 errors for missing javadoc comments in the test code.

**Comment by romani** [comment]
We are highly unlikely to create javadoc over tests code.

Please describe reasons to have test to be documented

**Comment by pbludov** [comment]
> Please describe reasons to have test to be documented

Here: https://github.com/checkstyle/checkstyle/pull/6331#pullrequestreview-188764664

**Comment by rnveach** [comment]
Original comment was trying to ask for disabled checks to be moved to  Issue https://github.com/checkstyle/checkstyle/issues/5060 as documented in disabled line at https://github.com/checkstyle/checkstyle/blob/master/config/org.eclipse.jdt.core.prefs#L73 .

Your response didn't mention if there was a conflict or not. Test code won't be documented as it wouldn't provide any real benefit since we don't organize tests cases that well. We usually just jam them into whatever input file we want. So enabling them for everything will cause a conflict.

> But we will need to make two different configurations

While we could make 2 configurations for CI purposes, you can't do this with the Eclipse IDE. You must have 1 configuration for the entire project. It doesn't provide any granularity of control.

------------

@pbludov It sounds like we aren't going to enable these javadocs, atleast the ones disabled. You can update your other PR with the reasons they won't be updated.
However, some are enabled and it looks like you fixed failures resulting from them. They don't need a reason since they are enabled and should stay that way unless @romani says otherwise.

**Comment by romani** [comment]
@pbludov ,

from comment
>  But we will need to make two different configurations. One for the main code and another for the tests. We usually don't have javadoc comments in tests.

split probably make sense if you want to make it happen. But please  clearly define this in this issue. I do not think it a cost efforts to create extra eclipse config ... just for javadoc. But if you want  ... we can create such issue.

> While we could make 2 configurations for CI purposes, you can't do this with the Eclipse IDE.

whole reason of such configuration was to make sure that after importing project to Eclipse, user have no warnings. I still think we should keep it as goal at least for main config. Unfortunately I do not know how define scope of validation for Eclipse (for IDEA can have one config because excluding tests is part of main config.)

**Comment by rnveach** [comment]
> Unfortunately I do not know how define scope of validation for Eclipse

There is no that I have ever seen. I use this on my other projects and it is always been for the entire project. Only way is to split checkstyle into 2 projects, main and test, but this doesn't make sense imo.

**Comment by pbludov** [comment]
Ok, this issue is unnecessary.
