### ISSUE TITLE
Improve documentation of "cacheFile" property

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#6396]
I just stumbled over the "cacheFile" property by accident. The documentation at http://checkstyle.sourceforge.net/config.html#Properties is very short, it basically just describes how to set the file name.

What is really missing in the documentation, however, is an answer to the question, when is caching safe to be used and when not? Do I as a user have to watch for some corner cases, or can I always enable this locally and on my CI server? Is it okay to re-use a cachefile from another branch, when running multi-branch-builds on Jenkins?

Side note: Depending on the outcome, we may also want to check if that property should be set by the eclipse plugin by default.

**Comment by romani** [comment]
>when is caching safe to be used and when not?

Always safe, should be like this.
There is only one problem that we know, is support of Transaction Check - it doesn't work well with cach. But this is due to the fact that such Check is multi file validation, that we do not support.

>or can I always enable this locally and on my CI server?

It should work

>Is it okay to re-use a cachefile from another branch, when running multi-branch-builds on Jenkins?

It should work, cache file is simply  hashcodes of files content that had no violations. If nothing changed, we even check config and all config of modules - no need to revalidate file.

The only problem that we did not resolve yet, is we did not count version of binaries, so if Check becomes more demanding in new version, user will not see violation till he change a file.

-----

If you know how to make our doc better , please propose PR

**Comment by rnveach** [comment]
There is one other open issue with cache when an exception occurs in a check. https://github.com/checkstyle/checkstyle/issues/6297 But this is extremely rare as we are cracking down on these exceptions hard in our own checks. It is rare that we see one reported. We can't guarantee any 3rd party checks will not throw an exception.

> if Check becomes more demanding in new version, user will not see violation till he change a file.

Or until the cache is invalidated/erased.

**Comment by romani** [comment]
>if Check becomes more demanding in new version, user will not see violation till he change a file.

Ideally we need to fix this in library code, so all plugins, can simply use cache file.

**Comment by Bananeweizen** [comment]
Fun fact: The checkstyle-maven-plugin sets the property by default, so there is even more evidence that it is safe to use in basically all cases.

**Comment by romani** [comment]
it is not good metric, most of users might enforce this in CI, where no files are shared between executions, so cache fie is just created and unlikely reused. I doubt most users are aware of cache at all.

@Bananeweizen , if you see how documentation can be improved - please let us know.
If this issue was just for discussion - please close it.
