### ISSUE TITLE
links in header comment block of sun_checks.xml are outdated 

### ISSUE THREAD

**Issue by zenglian** [checkstyle/checkstyle#6420]
Oracle bought sun in 2009. The links in this file is not valid now. The name "sun" is outdated.

https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/sun_checks.xml#L13

**Comment by rnveach** [comment]
Even if they were bought out, the original document specifically says it was written by sun, so that is why we are still referencing it as the `sun` config, since it follows their style guide.

https://www.oracle.com/technetwork/java/javase/documentation/codeconventions-139411.html#16712
>  This document reflects the Java language coding standards presented in the Java Language Specification , from Sun Microsystems, Inc. 

Has oracle created their own code conventions for Java and thus outdated the original sun ones? Unless that happens, I think we should continue with `sun`.

Even our own links in the config are outdated, so I feel it is fine to update the links to their newest locations.

**Comment by zenglian** [comment]
You are right. So please fix the broken links only.

**Comment by rnveach** [comment]
Issue has to stay open for us to work on it once @romani approves it.

**Comment by romani** [comment]
on what page we have bad link ?

**Comment by rnveach** [comment]
@romani We are discussing the sun XML configuration file. Most of the links listed are bad or old.
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/sun_checks.xml#L13 This one doesn't work anymore. I found the code conventions through googling.

**Comment by romani** [comment]
@zenglian , issue is approved, please be welcome with PR to fix links.

**Comment by romani** [comment]
Fix is merged
