### ISSUE TITLE
MultipleVariableDeclarations missing from sun style

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6490]
The rational of the check says the sun style demands this, but it is not part of the sun checks XML.

https://checkstyle.org/config_coding.html#MultipleVariableDeclarations

**Comment by romani** [comment]
https://checkstyle.org/sun_style.html this page is empty, because style guide is not properly created.
Sun config is seriously in unclear state.

One day we will find contributor to make like https://checkstyle.org/google_style.html , but this is a big project https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2019-Project-Ideas#project-name-sun-and-open-jdk-code-convention-coverage

**Comment by Vampire** [comment]
Did you maybe misunderstand me?
Because I cannot relate your comment to my report @romani.
The rationale of the check says that the sun style demands what this check validates.
But the `sun_checks.xml` file does not include this check which is what I reported.

**Comment by rnveach** [comment]
@Vampire Our sun and google configuration files are validated against the written guides from sun and google respectively. We create a table to show what line of text in the guide related to the check we have setup and configured to prove we follow the guide.

We already have a complete mapping for google:
http://checkstyle.sourceforge.net/google_style.html#Google_Coverage_table
http://checkstyle.sourceforge.net/reports/google-java-style-20170228.html

Sun's mapping is empty because no one has sat down and worked on it. Any text that says style is a demand of sun could be wrong.
https://checkstyle.org/sun_style.html#Sun_Coverage_table

**Comment by Vampire** [comment]
Ah, now I understand what you mean, but actually the rational is correct:
![grafik](https://user-images.githubusercontent.com/325196/53899541-b62a0a00-403a-11e9-9af7-4db133ec2aea.png)
