### ISSUE TITLE
pitest: increase mutation coverage for pitest-filters profile to 100%

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6659]
We should increase coverage for pitest-filters profile up to 100%.
This issue is a subtask of #3708

https://github.com/checkstyle/checkstyle/blob/d68d8c2d5d4037746cbe61e5d973a12e0ec886a4/.ci/pitest.sh#L68-L94

-------

<a href="https://www.bountysource.com/issues/72804115-pitest-increase-mutation-coverage-for-pitest-filters-profile-to-100">
<img src="https://api.bountysource.com/badge/issue?issue_id=72804115">
</a>

**Comment by esilkensen** [comment]
I have a branch in my fork where I was able to increase coverage for pitest-filters to 100% 🙂 

In the process I think I discovered a small bug in SuppressWithNearbyCommentFilter - I'm going to confirm that and if so will open a new issue for it.

Assuming it's valid and approved, I'm wondering about rolling that bug fix into the same PR that increases the pitest-filters coverage... (the fix for it is the only change I made to `src/main`)

**Comment by romani** [comment]
> it would probably be best to fix the bug first in its own PR then do the pitest coverage.

It would be awesome. Please report an issue.

**Comment by romani** [comment]
Fix is merged

**Comment by romani** [comment]
@esilkensen , please request bounty

**Comment by esilkensen** [comment]
Awesome, thank you!

**Comment by rnveach** [comment]
@romani @esilkensen `pom.xml` was never updated for 100% for profile.
https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L2928

**Comment by esilkensen** [comment]
Ah sorry about that - should I open a PR to update that to 100? Could it be a "minor:" commit?

**Comment by romani** [comment]
Please do PR with reference to this issue, it not a problem that issue is already closed.
Thanks a lot for help.

**Comment by rnveach** [comment]
Thanks @esilkensen
