### ISSUE TITLE
new check: MissingJavadocVariableCheck from JavadocVariableCheck

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6704]
Split from https://github.com/checkstyle/checkstyle/issues/5411 ,

Split missing javadoc functionality from `JavadocVariableCheck` and create  `MissingJavadocVariableCheck`.
It should only have the properties needed to validate if a violation should be printed on missing javadoc.

**Comment by timurt** [comment]
@romani @rnveach can I take this issue?

**Comment by romani** [comment]
@timurt , sure ! 
You do not need confirmation from us, as issue is approve, just make comment "I am on it" and send a PR.

thanks a lot for help.

**Comment by timurt** [comment]
@romani @rnveach 

> Split missing javadoc functionality from JavadocVariableCheck and create MissingJavadocVariableCheck.

Now `JavadocVariableCheck` checks only for existence of the Javadoc, so `JavadocVariableCheck` is already `MissingJavadocVariableCheck` by default

**Comment by rnveach** [comment]
@romani Looks like he is right. No other validation is done on fields except checking if they are missing the javadoc or not.
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheck.java#L45
Looks like this issue isn't needed and can be closed.

**Comment by romani** [comment]
as some interest come to this Check, I would recommend to convert it to be based on AST completely.
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheck.java#L107 - it uses non AST approach.
All Java related Checks should stop using `getFileContents()` it is hack (not hack :) it is how it was before comments become available as AST in Checkstyle).

But it is better to create more specific issue on this.
This issue is better to close.
