### ISSUE TITLE
Use violation term as much as possible

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6771]
We need to remove all usages of error  word ( with only few exceptions) from our documentation.

Example https://checkstyle.org/config_metrics.html#BooleanExpressionComplexity_Error_Messages

We need to use term violation, because error and warn is severity of violation.
https://checkstyle.org/property_types.html#severity

**Comment by rnveach** [comment]
Fix was merged.

**Comment by romani** [comment]
I will do more fixes

**Comment by romani** [comment]
@rnveach , @pbludov , @strkkk ,

to proceed cleanup of terminology we need to start API cleanup:
method `fireErrors` https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/MessageDispatcher.java#L41-L46
should be renamed to `fireViolations`, logic is completely the same.

rename https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java and create new class `Violation` that will clearly explain what it has (message + all details + severity). Or we can make `Violation` as interface, keep it in API and move whole implementation to non-api package as class `ViolationImpl`, ... but this class have some weird `BUNDLE_CACHE` that definitely need to be moved out ... So I am more in position just rename it only. 

rename method `addError` https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/AuditListener.java#L62-L66
to `addAuditEvent`, as we wrap Violation to AuditEvent, lets use only AuditEvent terms there.

This will be huge damage to, most likely all plugins will be damaged/affected. So it is definitely required to be done in special issue and it will result in major version bump, as all plugins use custom AuditListener. But we probably can implement new method as `default` in interface (that do nothing), so we can skip BIG compatibility damage, so it will work in run time (need to tested to be sure).

**Comment by rnveach** [comment]
> API cleanup

@romani You will definately need a middle ground in the meant as you not be able to break compatibility like this in 1 PR.
https://github.com/apache/maven-checkstyle-plugin/search?q=AuditListener&unscoped_q=AuditListener
https://github.com/apache/maven-checkstyle-plugin/search?q=LocalizedMessage&unscoped_q=LocalizedMessage
Maven Checkstyle has its own listener using these names. Breaking compatibility with Maven means everything that uses it will stop working, including regression and our own checkstyle run.
I didn't mean Eclipse-cs since they have stopped updates and are not as embedded into our group as maven.

I have brought up before that we should break away from maven so we can damage easier. Even with a middle ground interm, you will still need to wait for maven to switch to good methods before you can fully remove them.
These are the issues required from break away maven: https://github.com/checkstyle/checkstyle/issues/5386 , https://github.com/checkstyle/checkstyle/issues/5385 , https://github.com/checkstyle/contribution/issues/273

**Comment by rnveach** [comment]
@romani Is this issue completed?

**Comment by romani** [comment]
let me close this issue, as it is now hard to find misusage or "error" when "violation" is required.
There are too much instances of error term and almost all of them a valid.
