### ISSUE TITLE
eclipse violation over javadoc of AtclauseOrderCheck.java

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6947]
from : https://travis-ci.org/checkstyle/checkstyle/jobs/567697101#L588

```
1. ERROR in /home/travis/build/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/
checkstyle/checks/javadoc/AtclauseOrderCheck.java (at line 68)
	* Default value is {@code @author, @deprecated, @exception, @param, @return,
	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Javadoc: Missing closing brace for inline tag
```

it will become a failure in master ones I merge https://github.com/checkstyle/checkstyle/pull/6945 .

introduced by https://github.com/checkstyle/checkstyle/commit/7493dd41a4fe26e357de5cd8945717b13d13d86c#diff-6d4b0d5911e5ed5f47a227650ec06fa0R68 .

simiar issue was in Eclipse , but fixed in 4.7:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=206345
we are using 4.10 - https://github.com/checkstyle/checkstyle/blob/master/.ci/eclipse-compiler-javac.sh#L11

**Comment by romani** [comment]
@pbludov , please help to resolve ASAP.

**Comment by esilkensen** [comment]
@romani @pbludov I opened PR #6952

**Comment by romani** [comment]
fix is merged, but link to Eclipse issue is pending.

**Comment by romani** [comment]
fix is merged.

**Comment by esilkensen** [comment]
I know I saw this error last night on my personal computer with Eclipse - but now I'm trying on another one and can't seem to reproduce it with Eclipse 4.12.0. 

I will check it out again later and try and confirm I can reproduce it. Otherwise maybe it's an issue that has already been fixed in the newer versions?

**Comment by romani** [comment]
We can upgrade our eclipse jar to 4.12

**Comment by esilkensen** [comment]
This is strange, I do see the error on Eclipse 4.12 on one computer, but on another computer with the same Eclipse version 4.12 I _don't_ see the error. 

I wonder if related to: https://stackoverflow.com/questions/18413971/eclipse-complaining-about-javadoc-even-after-disabling-javadoc-in-compiler-optio 
>Even stranger: The same code in a smaller project in a different workspace works OK. I've compared the 2 projects' settings a couple times and they appear to be the same.

**Comment by pbludov** [comment]
Interesting.
```
package test;

/**
 * Default value is {@code @author, @deprecated, @exception, @param, @return,
 * @see, @serial, @serialData, @serialField, @since, @throws, @version}.
 */
public class TestClass {
}
$ /usr/lib/jvm/java-11/bin/javadoc TestClass.java
Loading source file TestClass.java...
Constructing Javadoc information...
Standard Doclet version 11.0.3-internal
Building tree for all the packages and classes...
TestClass.java:4: error: unterminated inline tag
 * Default value is {@code @author, @deprecated, @exception, @param, @return,
                    ^
TestClass.java:5: error: unexpected content
 * @see, @serial, @serialData, @serialField, @since, @throws, @version}.
   ^
```

but for this code
```
package test;

/**
 * Default value is {@code @author, @deprecated, @exception, @param, @return,
 * * @see, @serial, @serialData, @serialField, @since, @throws, @version}.
 */
public class TestClass {
}
```
the same command reports no violations. 


That is crazy. The javadoc tool (and Eclipse too) recognizes a block tag even if it placed inside a `{@code }` and `{@literal }` tags! This should be a test case to #6929

One possible reason for this behaviour is a chance to recover after missing `}` after the `{@code` block.

**Comment by pbludov** [comment]
> This should be a test case to #6929

No. It is a different story. The block tag is located where it should be.
So it is not a case for the `BlockTagLocation` check.
The real problem is that our parser is more strict than the javadoc tool or Eclipse.
We need to fix (actually break) our parser to mimic their behavior.

**Comment by romani** [comment]
Is it better for javadoc to fix issue ?

**Comment by pbludov** [comment]
I did not find in the specification a clear indication that block tags should have a preference over inline tags. In my opinion, the behavior of `javadoc` is wrong. The text inside an inline tag should be plain text.

Perhaps this was done for some compatibility. Or, the developers decided that unclosed `}` is a big problem for javadoc comments and found a way to recover quickly.

But checkstyle is designed for more accurate code. And from this point of view, the checkstyle parser is more correct.

For now, I plan to configure javadoc tool validation as part of CI. If there is javadoc that is incorrect from the point of view of the javadoc tool, we need to collect all such cases and investigate. Since the result of this tool is published on the site, we need to pay attention to its warnings, even if they are questionable.
