### ISSUE TITLE
spell checker is failing due to failure to get words file

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6949]
build failure:
https://travis-ci.org/checkstyle/checkstyle/jobs/568596942#L307

```
Retrieve ./usr/share/dict/linux.words
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1271k  100 1271k    0     0   326k      0  0:00:03  0:00:03 --:--:--  326k
/usr/bin/unlzma: (stdin): File format not recognized
./.ci/test-spelling-unknown-words.sh failed to extract words 
(https://rpmfind.net/linux/fedora
/linux/development/rawhide/Everything/aarch64/os/Packages/
w/words-3.0-34.fc31.noarch.rpm
 as .ci-temp/words.rpm) (1 0)
```

spellcheker is disabled at https://github.com/checkstyle/checkstyle/pull/6945 , till issue is resolved.

spellcheker works fine on local(ubuntu 16.04)

**Comment by romani** [comment]
reproduced on my local ... when executed in different checkout folder.

**Comment by romani** [comment]
@jsoref , can you help us to resolve problem ?
looks like some problem with rpm2cpio.sh

**Comment by jsoref** [comment]
Did the package change its format? Probably discernable by comparing the previous version. I'll try to look tonight…

**Comment by romani** [comment]
I am not sure, I did not update for scripts and version of this file for a while, just noticed this problem.

I uploaded cached version of words to 
```
 if [ ! -e "$dict" ]; then
   echo "Retrieve cached english.words"
   curl https://checkstyle.sourceforge.io/reports/english.words -o $dict
fi
```

but .... during testing I noticed that it works completely fine on my local without code that retrieve it from rpm.

**Comment by jsoref** [comment]
What I meant is that the version of the file changed: https://rpmfind.net/linux/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/w/words-3.0-34.fc31.noarch.rpm -- is dated: 2019-07-27 22:40 (i.e. very recently).

Running through the script:
https://github.com/checkstyle/checkstyle/blob/4bffe5d22080315769618006ab263c4e06eb1733/.ci/jsoref-spellchecker/rpm2cpio.sh#L27
```
$ echo $COMPRESSION
/dev/stdin: Zstandard compressed data (v0.8+), Dictionary ID: None
```
It looks like RHEL got fancy and switched to Zstd (that was coming, they had announced it a while ago). 
Zstd support is not available by default in debian (and almost certainly various other random distributions).

I don't have a good solution to this problem. It would be possible to try to write enough code to try to ask **CPAN** to get `Compress::Zstd::Decompressor`, but that's really overkill (the effort to reinvent `rpm` extraction is painful as is).

w/ CPAN, the following would work as `DECOMPRESSOR=`:
`perl -MCompress::Zstd -e '$/=undef; print decompress(<>);'`
But... that requires:
* getting cpan to properly work (I'm fairly confident there's a way to give cpan non-interactive settings, I've done it in the past, but probably 10+years ago)
* asking CPAN for the env vars to set to let the above actually work.

I think you're better served by just hosting a version of the dictionary yourself (and dealing w/ the copyright issues directly instead of trying to skirt it).

**Comment by romani** [comment]
>I think you're better served by just hosting a version of the dictionary yourself 

Yes, after dealing with such issue, I also came to such conclusion, maintenance will be easier. Vocabulary is not changing that often.

**Comment by romani** [comment]
fix is merged.
