### ISSUE TITLE
fix website header rendering issue

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7270]
identified at https://github.com/checkstyle/checkstyle/pull/7254#issuecomment-554760240

![image](https://user-images.githubusercontent.com/812984/69010050-4467c700-0910-11ea-9eca-243292813cd8.png)

but it is not caused by this change, and it is already visible at https://checkstyle.org/ but it worked fine at https://checkstyle.sourceforge.io/version/8.20/ , so it is some our recent change.

**Comment by romani** [comment]
assigned to @jo2 .

**Comment by jo2** [comment]
Thanks. So far I found that it is not a problem of the newer versions of the page. The same problem also exists in the mentioned version 8.20 but is not visible due to header height (To check set height of `<div id="banner">` to `200px`). 

The changed header height originates from the version of the maven-site-plugin from 3.7.1 to 3.8.2 which was introduced in checkstyle 8.24

A easy fix for that would be to just use repeat-x (which may cause a small whitespace below the header image s. Image) or set the headers height to the same height of the image (which may cause problems when changing the image. Also fix values can leed to problems when resizing the window, I didn't have any though). 

![image](https://user-images.githubusercontent.com/7516893/69139776-84ba7700-0ac1-11ea-906c-feff0b2ab80b.png)

Some thoughts on this? The first solution is cleaner but it isn't a perfect fix for this problem.

**Comment by romani** [comment]
I ok with extra empty space under header image. Thanks a lot.

**Comment by rnveach** [comment]
Fix was merged
