### ISSUE TITLE
Xpath implementation: relationship between getLocalPart and getStringValue 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7486]
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&resolved=false&rules=java%3AS4144

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java#L121-L128

src/.../tools/checkstyle/xpath/ElementNode.java
Update this method so that its implementation is not identical to "getLocalPart" on line 126.
L162

src/.../tools/checkstyle/xpath/RootNode.java
Update this method so that its implementation is not identical to "getLocalPart" on line 92.
L128

Should we make it like ?
```
    public String getLocalPart() {
        return getStringValue();
    }
```
https://www.saxonica.com/html/documentation/javadoc/net/sf/saxon/om/NodeInfo.html#getLocalPart--

there is idea that we do not need getStringValue - https://github.com/checkstyle/checkstyle/issues/5604#issuecomment-575275971

**Comment by romani** [comment]
I marked Sonar issue as wontfix as they are conflicting with Idea Inspection, but we can still review reason for `getStringValue`, if not required - we need to remove it.

**Comment by romani** [comment]
@timurt , we appreciate your help with this issue.

**Comment by rnveach** [comment]
Method can't be removed as it is required from `NodeInfo` interface and will cause a compile error when removed. I replaced the implementation with throwing an NPE and all the tests still passed when removed the 1 direct test of it in `RootNodeTest#testGetStringValue`.

**Comment by timurt** [comment]
@rnveach Yes, I did the same, throwing `Unsupported Operation` exception inside method.

**Comment by romani** [comment]
Before we put exception in such method, @timurt can you explain why it is not required, or what for such method is required in general ? How other xpath implementation use it ?

**Comment by romani** [comment]
@timurt, ping

**Comment by timurt** [comment]
@romani 

> Before we put exception in such method, @timurt can you explain why it is not required, or what for such method is required in general ? How other xpath implementation use it ?

**`getLocalPart()`**
method returns name of the current node without namespace.

**`getStringValue()`**
method returns string representation of value of the current node.
`ElementNode` has no value, but can have child nodes. That's why it should throw exception as PMD does or should return concatenation of the descendant nodes

> This method returns the string value as if the node were untyped. Unlike the string value accessor in the XPath 2.0 data model, it does not report an error if the element has a complex type, instead it returns the concatenation of the descendant text nodes as it would if the element were untyped.

How PMD works, [ElementNode](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/ElementNode.java) implementation has method `getLocalPart` and it returns xpath node name. Class has no implementation for `getStringValue` method and throws exception.
Class [AbstractNode](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/AttributeNode.java) has both methods implemented, `getLocalPart` returns attribute name, `getStringValue` returns attribute value

**Comment by rnveach** [comment]
Fix was merged
