### ISSUE TITLE
Standard google_checks.xml throws error: "ENUM_DEF" Not Found

### ISSUE THREAD

**Issue by t-rad679** [checkstyle/checkstyle#7503]
Check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck

# Compile?

```bash
/var/tmp $ javac YOUR_FILE.java
```

## OUTPUT

No output

# Config

```bash
/var/tmp $ cat config.xml
```

## OUTPUT

Using stock google_checks.xml config

# File
```bash
/var/tmp $ cat YOUR_FILE.java
```
## OUTPUT
```java
public class Test {
  int wrongIndent = 0;
}
```

# Checkstyle

```bash
Tome-of-Ancient-Secrets:resources trevorradcliffe$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
Tome-of-Ancient-Secrets:resources trevorradcliffe$ java $RUN_LOCALE -jar ~/Downloads/checkstyle-8.28-all.jar -c $SRC/checkstyle/src/main/resources/google_checks.xml Test.java
```

## OUTPUT

```bash
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "ENUM_DEF" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:473)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:396)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:324)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:187)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:124)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "ENUM_DEF" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck
	at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:228)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:140)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:468)
	... 5 more
Checkstyle ends with 1 errors.
```

---------------

# What Do I Expect

There to be no error when running with a stock config provided in the checkstyle repo

**Comment by rnveach** [comment]
@t-rad679 
> $ java $RUN_LOCALE -jar ~/Downloads/checkstyle-8.28-all.jar -c $SRC/checkstyle/src/main/resources/google_checks.xml Test.java

Since you are using a custom path to your config and you didn't present your config, we can only assume you are using a custom version of the google config. We cannot confirm what your issue is if you don't provide the file. From the exception alone, it looks like you are using a config that has functionality that has not been released yet as mentioned in other issue.

From the description in the other issue, I was under the impression the issue was with the internal configuration. The one that comes packaged with the version of checkstyle works fine for me.

````
$ cat TestClass.java
public class TestClass {
    void method() {
    }
}

$ cat google_checks.xml
cat: google_checks.xml: No such file or directory

$ java -jar checkstyle-8.28-all.jar -c /google_checks.xml TestClass.java
Starting audit...
[WARN] /media/checkstyle/work/test/TestClass.java:2: 'method def modifier' has incorrect indentation level 4, expected level should be 2. [Indentation]
[WARN] /media/checkstyle/work/test/TestClass.java:3: 'method def rcurly' has incorrect indentation level 4, expected level should be 2. [Indentation]
Audit done.
````

**Comment by rnveach** [comment]
@t-rad679 
> $ java $RUN_LOCALE -jar ~/Downloads/checkstyle-8.28-all.jar -c $SRC/checkstyle/src/main/resources/google_checks.xml Test.java

You are using a custom version of the google config so we cannot confirm what your issue is if you don't provide it. From the exception alone, it looks like you are using a config that has functionality that has not been released yet.

From the description in the other issue, I was under the impression the issue was with the internal configuration. The one that comes packaged with checkstyle works fine for me.

````
$ cat TestClass.java
public class TestClass {
    void method() {
    }
}

$ cat google_checks.xml
cat: google_checks.xml: No such file or directory

$ java -jar checkstyle-8.28-all.jar -c /google_checks.xml TestClass.java
Starting audit...
[WARN] /media/checkstyle/work/test/TestClass.java:2: 'method def modifier' has incorrect indentation level 4, expected level should be 2. [Indentation]
[WARN] /media/checkstyle/work/test/TestClass.java:3: 'method def rcurly' has incorrect indentation level 4, expected level should be 2. [Indentation]
Audit done.
````

**Comment by t-rad679** [comment]
I am not using a custom config. That is the config that comes with checkstyle in the repo. I gave that path to make it extra clear that I'm using the same config. That is my local clone of the checkstyle repo. I have made no modifications to it.

I generally use the checkstyle command, installed with brew...not a random jar downloaded from the release page. I wasn't aware specifying a file inside the jar as a config was possible (Indeed, I'm only learning that by inferring from your comments, which seem to assume I knew that) as there aren't really any straightforward usage instructions in the README or on the website. As such, I cloned your repo to get access to the file. I think the issue I'm encountering is because I cloned master, but I don't think that was an unreasonable decision. I can understand, in retrospect, why master might have a config that doesn't match up.

However, I think you should provide a file outside the jar for users of the checkstyle command installed via package managers, which does not find the file inside the jar, and you should reference that file in some usage instructions. Another option would be to have a default config, and/or allow the specification of an alias for a config that *does* work with the command. All of these things together would be the ideal scenario in my opinion.

**Comment by rnveach** [comment]
> I wasn't aware specifying a file inside the jar as a config was possible

Yes, this is why we add the configuration to the JAR. You can load any config file for checkstyle by specifying the classpath. Since the JAR is added to the classpath, you can access configurations stored inside it.

> as there aren't really any straightforward usage instructions in the README or on the website. 

I agree, it is not easy to find. The only example I found online was in https://checkstyle.org/cmdline.html#Download_and_Run . If you know a place to put it that would be straightforward and others could easily find it, then let us know.

>  I think you should provide a file outside the jar for users of the checkstyle command installed via package managers

I am not familiar with package manager installation. Does it not include the all JAR? Is it just the maven version of the JARs? We have the configuration in our main maven folder as part of resources. It should always be with the JAR it is distributed with.

You can always reference the configuration on github but you have to make sure you use the release version that matches what you have installed. Old or newer versions may have breaking changes.

**Comment by aisandbox** [comment]
This is an understandable error (as I've just done the same thing).

The main checkstyle website (https://checkstyle.org/google_style.html) links to the version of google_checks.xml in master, which is different to the one which works with the latest release. So anybody following the website instructions will see this error.

The link on the website should either be changed to point to the latest release, or a note added to warn the user.

**Comment by romani** [comment]
> Using stock google_checks.xml config

There is no such term, config us versioned, the same as Check implementations. But I agree it might be  not obvious for users.

> it looks like you are using a config that has functionality that has not been released yet 

Yes, when we change Google config, not that frequent event, version in master is for information only.

>So anybody following the website instructions will see this error.

Good point. There is nuance, we use on this page search feature of GitHub, it is available only for master head code.
What we can do is to put a warning on top of such html page and warm users to use embedded version in jar or versioned (for certain tag name) file.

Are you ok with such solution ?

**Comment by romani** [comment]
issue is moved to #7505

**Comment by t-rad679** [comment]
Sorry for the delay, yes that sounds fine.
