### ISSUE TITLE
Update doc for MutableException

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7613]
https://checkstyle.org/config_design.html#MutableException

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by sudo-andro** [comment]
I'm on it.

**Comment by romani** [comment]
@sudo-andro  , I placed in description link on how PR should looks like , please do.

**Comment by HirumalPriyashan** [comment]
I am on it. 

(since last comment is more than two years ago and no related PRs)

**Comment by ShubhraSuman** [comment]
I am on it.

**Comment by ShubhraSuman** [comment]
Do I need to write example for both properties or one is fine? Since both of them have same default values.

name	                                                            description	                                  type	default value
- format	                                        Specify pattern for exception class names. Pattern "^.*Exception$|^.*Error$|^.*Throwable$"
- extendedClassNameFormat.      Specify pattern for extended class names   Pattern	"^.*Exception$|^.*Error$|^.*Throwable$"

**Comment by romani** [comment]
For both, and both should have custom values (not defaults)

**Comment by arinmodi** [comment]
@pbludov, I made a PR on this, can you please review that ?
