### ISSUE TITLE
Update doc for ExplicitInitialization

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7639]
https://checkstyle.org/config_coding.html#ExplicitInitialization

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by ar283** [comment]
I'm on it.

**Comment by ImmortalRabbit** [comment]
I would like to do this issue but I have question. It says that I have to add an example for each existing config to show what code is ok and what code cause violation. Does the example  below covers all existing configs or am I missing something? Also, in documentation it was said that "**zero for** numeric types and **char** and false for boolean" which is misleading because according to [docs.oracle.com](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html) : 
char: The char data type is a single 16-bit Unicode character. It has a minimum value of '\u0000' (or 0) and a maximum value of '\uffff' (or 65,535 inclusive).
<img width="287" alt="Screen Shot 2020-03-04 at 17 22 28" src="https://user-images.githubusercontent.com/29354535/75874827-bec74300-5e3c-11ea-8719-45de6e28308d.png">

I suggest to change documentation from 1 to 2.
1:  Checks if any class or object member is explicitly initialized to default for its type value (null for object references, zero for numeric types and char and false for boolean. 
2:  Checks if any class or object member is explicitly initialized to default for its type value (null for object references, zero for numeric types, '\u0000' for char and false for boolean. 

Example:
```
public class Test {
  private int a = 0; // violation
  private int b = 1;
  private int c = 2;

  private char a = '\u0000'; // violation
  private char b = 'b';
  private char c = 'c';
 
  private boolean a = true;
  private boolean b = false; // violation
  private boolean c = true;
  private boolean d = false; // violation
  private boolean e = false; // violation

  private A a = new A();
  private A b = null; // violation
  private C c = null; // violation
  private D d = new D();

  int ar1[] = null; // violation
  int ar2[] = new int[];
  int ar3[];
  private Bar<String> bar = null; // violation
  private Bar<String>[] barArray = null; // violation

  public static void main( String [] args ) {
  }
}
```

**Comment by strkkk** [comment]
@ImmortalRabbit I suggest to first run checkstyle with this check to make sure this is a violation. In test inputs I see only case for `'\0`, but there is nothing about escape sequences (they maybe missed in check, but it is another issue).

Please also don't forget to add example for final fields (they should not be reported as violation)

**Comment by strkkk** [comment]
Fix is merged
