### ISSUE TITLE
Update doc for ReturnCount

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7657]
https://checkstyle.org/config_coding.html#ReturnCount

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by sudo-andro** [comment]
I want to work on this.
Should I edit the html page and add a new section called "Examples"?

I also see a column Example Of Usage - Checkstyle Style, what is that for?

Please guide me on how do I go about solving this issue?
My understanding- 
Some xml file and javadoc needs to be edited right?

**Comment by romani** [comment]
@sudo-andro ,  I placed in description link on how PR should looks like , please do.

**Comment by himanshurijal** [comment]
I am on it.

On a side note, 
Shouldn't the configuration for not allowing any return statements in constructors be 
<img width="412" alt="Screen Shot 2020-12-28 at 1 37 19 PM" src="https://user-images.githubusercontent.com/31570659/103238956-d9116680-4911-11eb-941f-e92034d6dca8.png">

instead of

<img width="1138" alt="Screen Shot 2020-12-28 at 1 39 04 PM" src="https://user-images.githubusercontent.com/31570659/103239061-1970e480-4912-11eb-8e9d-95d8a2612dca.png">

The documentation mentions that the "max property will only check returns in methods and lambdas that return a specific value (Ex: 'return 1;')". If we consider the following example of a constructor with a single 'return' statement, we would expect checkstyle to show an error (with the configuration in the documentation), but it doesn't.

<img width="513" alt="Screen Shot 2020-12-28 at 2 19 09 PM" src="https://user-images.githubusercontent.com/31570659/103241128-e6315400-4917-11eb-900b-8610ef7af75b.png">

Please let me know if I'm misunderstanding something here.

**Comment by kexuancoco** [comment]
I am on it

**Comment by vivek286** [comment]
I want to work on it

**Comment by romani** [comment]
@vivek286 , there is abandoned PR for it, but  I will merge who make PR quicker

**Comment by romani** [comment]
@vivek286 , I am closing abandoned PR, please send new PR.

**Comment by Binita-tech** [comment]
I am on it

**Comment by Perin-Mangukiya** [comment]
@romani I want to contribute to this issue.

**Comment by romani** [comment]
Fix is merged
