### ISSUE TITLE
Update AbstractChecks to log DetailAST - CustomImportOrder

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7728]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on CustomImportOrder.

**Comment by developerhb** [comment]
I am on it

**Comment by developerhb** [comment]
@rnveach @romani Hii.

Currently I am working on issue #7696. After its completion I would like to work on this issue. Please provide me more details about what I need to do. 

Do I need to have prior knowledge about any module? If so, please provide me details of that too.

**Comment by romani** [comment]
@developerhb , please start working on this issue, do not wait for review on first issue, we are overloaded with PRs reviews, please do not waste time, keep fixing issues.

**Comment by developerhb** [comment]
@romani @rnveach

As suggested by @wilcoln on gitter, I spent some time looking at the PR https://github.com/checkstyle/checkstyle/pull/7909. Before I can start working on this issue I have some basic questions.

1) What is AST node?
2) What is XPath?
3) What is SuppressionXpathFilter?
4) What is CustomImportOrder?
5) What changes we need to achieve?

**Comment by developerhb** [comment]
@romani @rnveach @timurt 

If I understand the issue correctly, we need to update the check from logging the line/column to logging on AST Node and for each and every log in that check, we need to write a test.

The Unit Tests are to be written in
`https://github.com/checkstyle/checkstyle/tree/master/src/it/java/org/checkstyle/suppressionxpathfilter`.

The description of issue #5777 says that

_We don't expect drastic change in **current UTs** when making the switch. If any items change the line/column drastically, please point them out to be clear to admins in the PR. Adding a column number when no was there before is ok and an expected change._

Where can I find this **current Unit Tests(UT's)** ?

**Comment by wltan** [comment]
> Where can I find these **current Unit Tests(UT's)** ?

Look for a `CustomImportOrderCheckTest.java`, which contains unit tests for the check's basic functions. This is independent of the XPath suppression tests in `suppressionxpathfilter` that you mentioned, which is completely missing and needs to be implemented. You can refer to similar PRs that have been merged to get a general idea of what needs to be done.

**Comment by developerhb** [comment]
@wltan 
The `CustomImportOrderCheck.java` contains the log functions.

So I need to change
`log(importObject.getStartLineNumber(), MSG_SEPARATED_IN_GROUP, fullImportIdent);`
to
`log(ast, MSG_SEPARATED_IN_GROUP);`

Do I need to import any addition class to make this change.

**Comment by wltan** [comment]
> So I need to change
> `log(importObject.getStartLineNumber(), MSG_SEPARATED_IN_GROUP, fullImportIdent);`
> to
> `log(ast, MSG_SEPARATED_IN_GROUP);`

That is the main idea, yes. You may need to keep the `fullImportIdent` argument at the end because that is part of the check's error message to be generated.

The challenge is to find where you can get `ast` from. You need to trace the method calls from `log` all the way back to an appropriate `DetailAST` object, then pass it along so that you can use it when logging the violation. In this case it looks like you have to modify `ImportDetails` to store the AST object.

> Do I need to import any addition class to make this change.

Most of the time, no. Whatever custom classes a check needs is usually contained within the check class itself. Unless you're making changes to the check's behavior there shouldn't be big changes to the imports (but you might need simple/common stuff like `java.util`).

**Comment by developerhb** [comment]
@wltan Hello
Here's a log function of `JavaDocContentLocationCheck.java`

```java
@Override
    public void visitToken(DetailAST ast) {
        if (isMultilineComment(ast) && JavadocUtil.isJavadocComment(ast)) {
            final String commentContent = JavadocUtil.getJavadocCommentContent(ast);
            final int indexOfFirstNonBlankLine = findIndexOfFirstNonBlankLine(commentContent);
            if (indexOfFirstNonBlankLine >= 0) {
                if (location == JavadocContentLocationOption.FIRST_LINE) {
                    if (indexOfFirstNonBlankLine != 0) {
                        log(ast, MSG_JAVADOC_CONTENT_FIRST_LINE);
                    }
                }
                else if (indexOfFirstNonBlankLine != 1) {
                    log(ast, MSG_JAVADOC_CONTENT_SECOND_LINE);
                }
            }
        }
    }
```
The log function has argument of **DetailAST** object. I would like to see the previous version of this method before implementation of AST. Can you help?

I want this to understand the changes that needs to be done.

**Comment by wltan** [comment]
Based on git blame at https://github.com/checkstyle/checkstyle/blob/4cd2b978ac7b8ef6b25590dd1d4d9f6ee4180627/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheck.java
it seems that when `JavadocContentLocationCheck` was first written it was already made to log DetailAST, so there is no "previous version" to refer to.

If you want some reference you can try looking at some of the merged PRs of https://github.com/checkstyle/checkstyle/pulls?q=is%3Apr+is%3Amerged+detailast
- All of them should have some kind of documentation update
- Most (if not all) of them should have some tests for XPath suppression
- Not all of them have changes to the check (because they were already written to log DetailAST), but it shouldn't be too hard to find other examples

You can look at my PR #7790 for a semi-trivial example as well.

**Comment by developerhb** [comment]
Thank you @wltan . The links provided by you were useful.

According my understanding, the log function in `CustomImportOrderCheck.java` uses startLineNumber attribute of `ImportDetails` class.

Here is the code
```java
log(importObject.getStartLineNumber(), MSG_LEX,
                            fullImportIdent, previousImportFromCurrentGroup);
```

One thing we can do is change the `ImportDetails` class to have one extra attribute which an object of `DetailAST`.

After this change the function would look like
```java
log(importObject.getAST(), MSG_LEX,
                            fullImportIdent, previousImportFromCurrentGroup);
```
where getAST() is method to access the DetailAST object from ImportDetails class.

But doing this would also require to change its constructor and which would lead to changes where ever the constructor is used in entire project.

**Comment by wltan** [comment]
> One thing we can do is change the `ImportDetails` class to have one extra attribute which an object of `DetailAST`.

Sounds like a good plan.

> But doing this would also require to change its constructor and which would lead to changes where ever the constructor is used in entire project.

The `ImportDetails` class is not likely to be used outside of this check. As long as you can fix all the constructor calls inside `CustomImportOrderCheck` itself that should be good enough.

In any case, regression testing is there to make sure functionality is still correct after changes.

**Comment by developerhb** [comment]
Okay @wltan . Think I should go ahead with this plan.

**Comment by developerhb** [comment]
@wltan I have edited the check `CustomImportOrderCheck.java` to log **DetailAST**. Now the next step is to write tests. Please guide me for writing tests.

**Comment by wltan** [comment]
For this it's probably just best to refer to existing PRs like #8069 to see how it's done.

For the test input files you will have to come up with it yourself, based on what you know about the check. Make sure you have enough tests to cover every `log` call in the main check at least once.

For the test file (e.g. `XpathRegressionCustomImportOrderTest.java`) what you can do is copy an existing test file for another check and change the names to your current check. Then modify the configs of the individual tests (e.g. `testOne()`, `testTwo()`, ...) to your current check. The expected queries can be found though trial and error by simply running the tests and seeing what actual output comes up (sounds like a terrible practice, but the output can be reviewed later).

**Comment by developerhb** [comment]
@wltan
As in https://github.com/checkstyle/checkstyle/pull/8069/files the test class methods like testOne(), testTwo()...

Each test uses a class like `SuppressionXpathRegressionMissingJavadocMethod1`. This class has a method which has no code. What is the importance of these classes? How the testing works?

**Comment by wltan** [comment]
The point of `MissingJavadocMethod` check is simply to check if required Javadoc is missing, so that is the only thing that the input classes need to demonstrate.

Similarly for `CustomImportOrder` check you will need to show with inputs how violations are produced, so you will set some out-of-order imports. Whatever else goes on in the input class can be as simple as you want, as it is irrelevant to testing the logging of the check.

**Comment by developerhb** [comment]
Thank you @wltan .
I understand the test and will complete the task soon and create the pull request.

**Comment by developerhb** [comment]
@wltan 
One more doubt. In the check there is function named `logWrongImportGroupOrder` which calls the `log` function. Should I create the test for `logWrongImportGroupOrder` or only for `log` function.

**Comment by developerhb** [comment]
@wltan 
Please explain me these two things

1. expectedViolation string
```java
final String[] expectedViolation = {
            "4:1: " + getCheckMessage(ImportOrderCheck.class,
                        ImportOrderCheck.MSG_ORDERING, "java.util.Set"),
        };
```
Here I would like to know the meaning of `4:1:` and the arguments of `getCheckMessage` function. Like when to give what arguments.

2. expectedXpathQueries string
```java
 final List<String> expectedXpathQueries = Collections.singletonList(
                "/IMPORT[./DOT/IDENT[@text='Set']]"
        );
```
Here I would like to know how this string is formed. That is, the meaning of `"/IMPORT[./DOT/IDENT[@text='Set']]"`

**Comment by wltan** [comment]
> 1. expectedViolation string
> 
> ```java
> final String[] expectedViolation = {
>             "4:1: " + getCheckMessage(ImportOrderCheck.class,
>                         ImportOrderCheck.MSG_ORDERING, "java.util.Set"),
>         };
> ```
> 
> Here I would like to know the meaning of `4:1:` and the arguments of `getCheckMessage` function. Like when to give what arguments.

Each element of the array is a violation, presented exactly as you would see when running a Checkstyle jar.
- `4:1:` is line and column number respectively. 
- `getCheckMessage` is to 'build' the violation message. 
  - First argument is clearly the `.class` of the check. I don't know for sure what this is for either, but my guess is the `[ImportOrderCheck]` that you get at the end of the violation line.
  - There is i18n present so messages are stored as keys to the resource bundle (`ImportOrderCheck.MSG_ORDERING`) and Checkstyle will retrieve the correct message in the current locale for you.
  - Anything beyond that is varargs, which is necessary if and only if the message requires additional information about the violation (e.g. name of class/method with violation).
 
> 1. expectedXpathQueries string
> 
> ```java
>  final List<String> expectedXpathQueries = Collections.singletonList(
>                 "/IMPORT[./DOT/IDENT[@text='Set']]"
>         );
> ```
> 
> Here I would like to know how this string is formed. That is, the meaning of `"/IMPORT[./DOT/IDENT[@text='Set']]"`

The XPath query allows you to uniquely specify the node that you are logging as a path through the AST from the root. 

I'm no expert in XPath so I can't help you with exactly how it works but if the query is near the root of the AST it might be simple enough to write by hand. Otherwise just figure it out with trial and error (run the tests and get the output when it fails).

**Comment by developerhb** [comment]
@wltan 
> 4:1: is line and column number respectively.

Line and column of which thing and how can I obtain it?

**Comment by DXTkastb** [comment]
@developerhb this line: column is the violation location in your test files.
4:1 , so violation is at line 4 and column 1.

We create tests to check if the changed code works properly and we fulfill line coverage.

**Comment by developerhb** [comment]
@wltan How can I run the tests that I have created and check if they are correct?

**Comment by wltan** [comment]
On IntelliJ I know that you can run an individual test by right-clicking the editor and running from the context menu.

The only other way that I know of that works for sure is to just `mvn clean verify`, there might be other ways but I've never had to try them.

**Comment by wilcoln** [comment]
@developerhb 
- To run a test class :  `mvn test -Dtest=MyTestClass`
- To run multiple test classes : `mvn test -Dtest=MyTestClassOne,MyTestClassTwo` (and so on)
- To run a specific method of a test cass: `mvn test -Dtest=MyTestClass#mymethod`

I know that they work because I use those commands on a daily basis.
You can checkout https://mkyong.com/maven/how-to-run-unit-test-with-maven/ for more informations.

**Comment by developerhb** [comment]
Thank you @wilcoln . This is helpful

**Comment by developerhb** [comment]
@wltan I am done with editing files. Now I am generating diff report.

I am running following command
` groovy diff.groovy --localGitRepo ../../checkstyle --baseBranch master --patchBranch 7728-updateabtractchecks-customimportorder --config my_check.xml --listOfProjects projects-to-test-on.properties`

I am getting following error.

```
Caught: java.io.IOException: Cannot run program cmd in directory (directory of checkstyle-tester): Create Process error=5, Access is denied
```
Please help.

**Comment by wltan** [comment]
Sounds like a problem with your local file system.

Unfortunately I can't help you with that, maybe you can try asking on Gitter?

**Comment by rnveach** [comment]
Fix was merged

**Comment by developerhb** [comment]
The PR is merged. Thank you @wltan @DXTkastb @wilcoln for guiding me in this issue.
