### ISSUE TITLE
Update AbstractChecks to log DetailAST - ImportOrder

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7733]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on ImportOrder.

**Comment by DXTkastb** [comment]
I'm on it.

**Comment by DXTkastb** [comment]
@rnveach I tried editing ImportOrderCheck.java and ran mvn clean verify but received error:

**Code causing error:**
```
if (groupIdx > lastGroup) {
        if (!beforeFirstImport && ast.getLineNo() - lastImportLine < 2 && needSeparator(isStatic)){
            log(ast, MSG_SEPARATION, name);
    }
}
```




``
[ERROR] src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java:[664] (extension) LineLengthExtended: Line is longer than 100 characters. Current line length is 108.
``

The second if statement in the code has 108 length.
Can you please help me in correcting the code format. I have tried different other ways like storing the ast.getLineNo() value in a local variable and reformating the code according to checkstyle but
some or the other way build fails due to errors.

**Comment by rnveach** [comment]
> Line is longer than 100 characters
> Can you please help me in correcting the code format. 

Have you tried breaking the line into 2?

**Comment by DXTkastb** [comment]
Yes, @rnveach I tried that too but didn't pay attention to the checks errors. I have now resolved them and will revert a PR as soon as possible.

**Comment by strkkk** [comment]
Fix is merged
