### ISSUE TITLE
Resolve Pitest Issues - DetectorOptions

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7981]
Child issue of https://github.com/checkstyle/checkstyle/issues/7797 ,

https://github.com/checkstyle/checkstyle/blob/f9131f9536c71d963c83aab1550b7a0371aa9ff5/.ci/pitest.sh#L51

**Comment by wilcoln** [comment]
I'm on it.

**Comment by wilcoln** [comment]
**Pitest report before**
- Link: https://wilcoln.github.io/checkstyle-reports/pit-reports/detector-before/com.puppycrawl.tools.checkstyle.checks.regexp/DetectorOptions.java.html
- Surviving mutations: on line 121 `removed conditional - replaced equality check with true → SURVIVED`

**Hardcoded mutation**
Useless, as class is not a check.

**Regression diff reports**
Useless, as class is not a check.

**Code analysis**

The `pattern` class member is not initialized and is accessed only once in the class, that is, inside the `getPattern()` method body.

We are interested in the condition 
https://github.com/checkstyle/checkstyle/blob/fab949ad62a4ec520afe4924c181a1c304533d4c/src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/DetectorOptions.java#L121

Since the pattern value is been modified inside the method body, our condition becomes false after a first call of `getPattern()` **on the same instance of DetectorOptions**.

The important thing to note here is that, every call to our method lead to the same outcome, as once the `DetectorOptions` instance is built, it's parameters doesn't change, thus, the computed value for the pattern will remain the same, over and over again. 

That's why it is, indeed, clever to check if `pattern` is null before computation (as it is done in the code), as we only have to compute it’s value once.

So, blindly removing the condition for the sake of improving pitest results is a bad idea because this will lead to lose in code efficiency.

Instead, I suggest to simply move the first computation of pattern inside the `build()` method, as it this the last method called to build a `DetectorOptions`  instance and we have insurance that by the time of the call, all other members required for pattern computation will be available.

This way we both kill the mutation and ensure that `pattern` member is computed only once.

**Pitest report after**
- Link: https://wilcoln.github.io/checkstyle-reports/pit-reports/detector-after/com.puppycrawl.tools.checkstyle.checks.regexp/DetectorOptions.java.html

Related PR is https://github.com/checkstyle/checkstyle/pull/7986

**Comment by wilcoln** [comment]
@rnveach, please review.

**Comment by rnveach** [comment]
> Not applicable, as class is not a check.

Class is used by a check. It is no different than a utility class or a private static method. They can all be atleast touched on by regression. If we have an external class used by a check, then all checks that use that class must be put through regression.

I agree with the rest of your analysis so I don't feel we need more regression.

**Comment by rnveach** [comment]
Fix was merged

**Comment by wilcoln** [comment]
> Class is used by a check. It is no different than a utility class or a private static method. They can all be atleast touched on by regression. If we have an external class used by a check, then all checks that use that class must be put through regression.

Understood
