### ISSUE TITLE
remove SuppressWarningsHolder from CheckUtil.getCheckstyleChecks

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8121]
detected at https://github.com/checkstyle/checkstyle/pull/7931#discussion_r410255047
and after this PR is merged and #7848 is closed.

we need to remove from CheckUtil.getCheckstyleChecks module SuppressWarningsHolder as it does not report any violation any more, so it is not a Check.

**Comment by wilcoln** [comment]
I'm on it.

**Comment by rnveach** [comment]
@romani What is your goal by doing this?

I don't recommend doing this regardless if it reports violations or not. This utility is used to ensure all AbstractChecks pass our regression and used to make sure we don't forget something like adding to our xdoc. Removing any class form these utilities basically will almost make the class disappear from any enforced testing.

**Comment by rnveach** [comment]
It looks like this came up from https://github.com/checkstyle/checkstyle/pull/7931/#discussion_r410701786 because the check is being tested for containing a message and it contains none by default. This utility method is used in other places and not just this one check. I think updating the test to skip the class was the right thing and to leave `CheckUtil.getCheckstyleChecks` untouched for the reasons I stated above.

There are other checks that exist in our code which do not have direct messages themselves.
https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java#L223-L232

**Comment by romani** [comment]
@rnveach , make sense, thanks a lot for details.
Lets keep skip in test.
