### ISSUE TITLE
Ability to keep mobile mode when mobie phone is vertical position

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8397]
web site in horizontal layout of mobile phone should be in mobile mode (left panel should be on top).
Here is how it looks like:
![Screenshot_20200704-151539](https://user-images.githubusercontent.com/812984/86521727-64012080-be09-11ea-80c5-8ad789975291.png)
 table content is cut:
![Screenshot_20200704-152004](https://user-images.githubusercontent.com/812984/86521791-146f2480-be0a-11ea-8391-3068625688f1.png)
code is cut:
![Screenshot_20200704-152035](https://user-images.githubusercontent.com/812984/86521792-15a05180-be0a-11ea-8b10-33b8a7bdc664.png)

Reason: I do a lot of answers from phone. Almost always I need to consult documentation and examples of behavior.
in vertical layout it good for simple doc check, but when it comes to examples and tables vertical is not enough and I try to use horizontal layout, but it switch back to normal web site rendering and left panel takes all space that I expected to reuse to see whole table or example.

My phone is 6-inch (2880 × 1440) is it like laptop screen ? :)

**Comment by romani** [comment]
@jo2 , your help is much appreciated.

**Comment by jo2** [comment]
@romani the mobile view is dependant on the viewport width and not the screen resolution. When the phone is in horizontal mode, the viewport width is higher than the trigger which is set for mobile view. The following screenshots were made with Firefox mobile device simulation, the simulated device is a Galaxy S9/S9+ with a resolution of 1440x1960 and a viewport of 360x740:

vertical:
![image](https://user-images.githubusercontent.com/7516893/86583691-fcbbab80-bf83-11ea-93f0-56d54626b90e.png)

horizontal:
![image](https://user-images.githubusercontent.com/7516893/86583729-09d89a80-bf84-11ea-8b4f-3d16cf627316.png)
 
for more information for your device you can look [here](https://deviceatlas.com/blog/viewport-resolution-diagonal-screen-size-and-dpi-most-popular-smartphones)

**Comment by romani** [comment]
> When the phone is in horizontal mode, the viewport width is higher than the trigger which is set for mobile view.

Where do we have this trigger configured in our css ?

**Comment by jo2** [comment]
Here: https://github.com/checkstyle/checkstyle/blob/9877a2866a5cda8ce856d07d2711be504bc50b83/src/site/resources/css/site.css#L123

**Comment by romani** [comment]
what could be bad if I change this to my phone screen(2880 × 1440) width? my laptop is using (1920 X 1080)
all my dimensions are bigger then 600px. How it is effective ?

**Comment by jo2** [comment]
The effective value regarding your phone and your laptop is the viewport and not the resolution. Mobile devices with a 4k display should display the mobile version of the page. although your phone has a resolution width of 1440px (in vertical mode) its viewport only has a width of around 400px or something like that (I don't now what kind of phone you have, so I can't be sure with the exact value). Your laptop has a resoution width of 1920px and I assume the viewport width si also 1920px. 

The resolution pixels are something different from css pixels due to most mobile devices having a higher pixel density. For further reading I recommend [this medium article](https://medium.com/@flik185/understanding-device-resolution-for-web-design-and-development-3bb4a5183478)  mostly the part for developers.

All in all: Your laptop shows the desktop version of the page and the css is working as you expect it to. Your smartphone has a resolution of 2880x1440 and a pixel density of about 4.0 which results in an css pixel width of 1440px / 4 = 360px. That is below the set trigger of 600px which makes your smartphone display the mobile version.

**Comment by romani** [comment]
I have Pixel 2XL.

**Comment by jo2** [comment]
According to [this](https://deviceatlas.com/blog/viewport-resolution-diagonal-screen-size-and-dpi-most-popular-smartphones#google), your device has a viewport resolution of 412x823. That means your device has a pixel ratio of something 3.5ish. If you have your phone in vertical mode you have a width of 412px which is lower than the set 600px resulting in the mobile view. If you have your phone in horizontal mode your viewport width 823px which is more than the set 600px resulting in the desktop version.

**Comment by romani** [comment]
@jo2, thanks a lot !
What could be undesirable effect if I change it to 823 ? I will make it good for me but is there any bad side effects ?

**Comment by jo2** [comment]
Some devices may react badly to it. For example the Samsung Galaxy S9+ has a width (in horizontal mode) of 846px and the iPhone XS max and XR are even larger with 896px (It is the largest in the list though). You could set it to 896 but then some smaller laptops or tablets will also receive the mobile version. For Tablets see [here](https://docs.adobe.com/content/help/en/target/using/experiences/vec/mobile-viewports.html). Sadly, there is no standard for when a device is a smartphone and should get the mobile version and when it should get the desktop.

**Comment by romani** [comment]
Fix is merged
