### ISSUE TITLE
Make getter method for sourceClass in LocalizedMessage

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/checkstyle#8602]
**Is your feature request related to a problem? Please describe.**
In GSoC project patch-filter, we will introduce two new filters, Checker filter (SuppressionPatchFilter) and TreeWalker Checks (SuppressionPatchXapthFilter), but one problem is that SuppressionPatchFilter will suppress all violations that a might pass SuppressionPatchXapthFilter(in case of context strategy, or mismatch of strategies between SuppressionPatchFilter and SuppressionPatchXapthFilter), and we find a solution that all TreeWalker checks extend AbstractCheck class and LocalizedMessage has sourceClass property. So inside SuppressionsPatchFilter we can check, if event is from AbstractCheck subclasses or not. 

But  now `sourceClass` property is private, so if we want to use this solution, we should make getter method for sourceClass in LocalizedMessage.
https://github.com/checkstyle/checkstyle/blob/6ba98dfc7c513d3b2b5bd8706197d2eb69d8ed1f/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java#L95

**Describe the solution you'd like**
Add a `getSourceClass` method in `LocalizedMessage`

**Comment by romani** [comment]
One more case where it become required https://github.com/checkstyle/checkstyle/issues/7884

**Comment by romani** [comment]
Hm,
we have 
https://github.com/checkstyle/checkstyle/blob/6ba98dfc7c513d3b2b5bd8706197d2eb69d8ed1f/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java#L353-L359

according to javadoc, it should return fully qualified class name - https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getName--

it should be enough.

**Comment by HuGanghui** [comment]
@romani ok, I will try it first.

**Comment by rnveach** [comment]
xpath is misspelled in first description.

**Comment by rnveach** [comment]
>  one problem is that SuppressionPatchFilter will suppress all violations that a might pass SuppressionPatchXapthFilter

I don't understand why this matters.

A violation is reported if all filters accept the event. (Checker#fireErrors)

All filters accept the event if no filters reject the event. (FilterSet#accept) (reject = suppress, accept returns false)

As soon as one rejects the event, none of the others are counseled because we got the 1 rejection. Obviously filter order is random and non-determinisitic.

If Patch filter suppresses a violation, why do we care what any other filter says. It says to not report the error so no matter what we don't report it. If you are looking to monitor all events, a filter isn't the way to do it.

If xpath filter suppresses a violation, does it really matter if Patch has a say or not?

Am I missing something?
