### ISSUE TITLE
Remove class Defn and move CHECKSTYLE_BUNDLE somewhere else

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#889]
Class [Defn](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Defn.java) looks obsolete. What do you think about moving `CHECKSTYLE_BUNDLE` to `Checker` as `public static final` and importing it from other classes? Any other ideas?
##

**Comment by romani** [comment]
from javadoc : "Contains constant definitions common to the package." - that contract is already broken due to latest code it is used at com.puppycrawl.tools.checkstyle.checks.TranslationCheck .

But moving to Checker or Tree walker is not a better idea , as it will introduce extra/unclear dependency between classes - http://checkstyle.sourceforge.net/dsm/index.html

But I agree that smth should be done with that class and with it usage.

**Comment by nrmancuso** [comment]
This class fits not exist any longer, we can close this issue.
