### ISSUE TITLE
Performance 10 times slower for MissingDeprecated check

### ISSUE THREAD

**Issue by stegeto22** [checkstyle/checkstyle#8914]
I'm having a performance issue with the [MissingDeprecatedCheck](https://checkstyle.sourceforge.io/config_annotation.html#MissingDeprecated) since version 8.24 (possibly because of [#4983](https://github.com/checkstyle/checkstyle/issues/4983))

Previously the check needs only some hundreds of milliseconds. Now it needs many seconds, depending on the amount of javadoc.

---------------
Previous:
`Checking 'big.java' needed 785 milliseconds.`
`Checking 'medium.java' needed 689 milliseconds.`
`Checking 'small.java' needed 607 milliseconds.`

Now:
`Checking 'big.java' needed 7448 milliseconds.`
`Checking 'medium.java' needed 2373 milliseconds.`
`Checking 'small.java' needed 1051 milliseconds.`

--------------
Here the example, which I've used for measuring the times.
[checkstylePerformance.zip](https://github.com/checkstyle/checkstyle/files/5420238/checkstylePerformance.zip)

**Comment by strkkk** [comment]
This may be related to https://github.com/checkstyle/checkstyle/issues/4983, it was included in 8.24

@stegeto22 Please change description to show difference for some file with significant degradation

**Comment by stegeto22** [comment]
@strkkk 
I've changed the headline. The description and the attached [checkstylePerformance.zip](https://github.com/checkstyle/checkstyle/files/5420238/checkstylePerformance.zip) already contain some example files and time measurements. Do you need s.th. else to reproduce it.

**Comment by romani** [comment]
this degradation of performance is expected :( . 
We do such stuff to switch to more reliable validation. So archiving more reliable validation in expense of performance, this is due to the fact that we converted Check to NOT use Regular Expression based logic but do parsing of Javadoc content by parser based on grammar (significantly more comprehensive action).

If you need for some reason old Check, you can copy it from old sources and keep in your own jar and use it.

more details on performance problem at https://github.com/checkstyle/checkstyle/issues/1064

**Comment by rnveach** [comment]
Exact reasoning at https://github.com/checkstyle/checkstyle/issues/1064#issuecomment-200387660 .

We don't have anyone with the expertise or time to help dive into and try and resolve the issue.

@romani We should keep an issue open IMO, to point users to and ask for assistance looking into and one day resolving this issue.

**Comment by romani** [comment]
@rnveach , please create issue on parsing performance.
