### ISSUE TITLE
To top button - different behavior and text on different pages

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#9001]
Open https://checkstyle.org/index.html - no button on initial screen, button text is "To Top", it appears only after 2-3 scrolls down
![image](https://user-images.githubusercontent.com/8901354/99776853-88dd0280-2b22-11eb-8de4-f63aa1744c1b.png)

Open some other page from Project Documentation section, e.g. https://checkstyle.org/ci-management.html - button is shown on initial screen without any scrolling, text is "toTop"
![image](https://user-images.githubusercontent.com/8901354/99776926-a0b48680-2b22-11eb-8b53-e75bcbb3c1d0.png)

**Comment by strkkk** [comment]
@jo2 Can you help with this issue?

**Comment by jo2** [comment]
@strkkk I'll take a look at it

**Comment by strkkk** [comment]
> Do you know, where the generation of the ci-management file happens?

@jo2 no idea, I couldn't find any mention in main repo. It looks like some external thing
@romani do you know where to find code/sources that generates Project Documentation section?

**Comment by jo2** [comment]
The reason for this issue is rather simple. The button text and behaviour are changed and added with javascript. In all files that are created manually, there is a line including the javascript file (https://github.com/checkstyle/checkstyle/blob/432bafd49ed9d801f44a04ad710cc9372538e588/src/xdocs/checks.xml#L13 for example). All files in project documentation are generated by maven using the site descriptor (src/site/site.xml). According to [the documentation](https://maven.apache.org/plugins/maven-site-plugin/examples/sitedescriptor.html#Inject_xhtml_into_.3Chead.3E) it should be possible to add javascript for generated files but i can't get `maven clean site` to run on my machine using this configuration. It fails with this error message:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.9.1:site (default-cli) on project checkstyle: failed to get report for org.apache.maven.plugins:maven-surefire-report-plugin: Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.0.2:validate (default) on project checkstyle: While parsing <path>\checkstyle\src\site\site.xml, at file:/<path>/checkstyle/src/site/site.xml, line 47,  column 12: error: cvc-complex-type.2.3: Element 'head' darf keine Zeichen [untergeordnete Elemente] haben, da der Contenttyp des Typs 'element-only' ist.
```

The last part, roughly translated: Element 'Head' cannot have any characters because the content type is of type 'Element only'.

**Comment by strkkk** [comment]
@jo2 but this button works, so it looks like script is added to page, but for some reasons it has different text and visibility. May be there is something with JS?

**Comment by strkkk** [comment]
I tried to play with it using different options on my local machine and I also failed to add this script with head tag to site.xml
Very weird

**Comment by strkkk** [comment]
FYI the reason why it is impossible to add script in head tag - old XSD. Schema upgrade will do the trick.

**Comment by jo2** [comment]
Thanks for the information! So this issue is fixed?

**Comment by strkkk** [comment]
Yes, patch is under review now - https://github.com/checkstyle/checkstyle/pull/9183

**Comment by romani** [comment]
fix is merged
