### ISSUE TITLE
no-error-pgjdbc is failing on master build

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#9176]
From wercker logs at https://github.com/checkstyle/checkstyle/pull/9165#pullrequestreview-565968475: 

```
export WERCKER_STEP_ROOT="/pipeline/script-478eddfa-c09f-4e37-abfa-4a5495adf8ad"
export WERCKER_STEP_ID="script-478eddfa-c09f-4e37-abfa-4a5495adf8ad"
export WERCKER_STEP_OWNER="wercker"
export WERCKER_STEP_NAME="script"
export WERCKER_REPORT_NUMBERS_FILE="/report/script-478eddfa-c09f-4e37-abfa-4a5495adf8ad/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/script-478eddfa-c09f-4e37-abfa-4a5495adf8ad/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/script-478eddfa-c09f-4e37-abfa-4a5495adf8ad/artifacts"
source "/pipeline/script-478eddfa-c09f-4e37-abfa-4a5495adf8ad/run.sh" < /dev/null
Command: ./.ci/wercker.sh no-error-pgjdbc
CS_version: 8.40-SNAPSHOT
Cloning into 'pgjdbc'...
fatal: reference is not a tree: f41cc39001febd824242afa5cb474fa0a52c1081

```
Full log found here:  https://app.wercker.com/checkstyle/checkstyle/runs/build/5ffd31ad237ec90008309fe4?step=5ffd334a64bf9700082de76b

This appears to be related to changes at https://github.com/checkstyle/checkstyle/commit/8381cd6a965583e6431ea4b4dd4d60979fc47138

**Comment by nmancus1** [comment]
@Abhishek-kumar09 has a PR/ issue been created with https://github.com/pgjdbc/pgjdbc/ ?   They have been very quick to respond in the past.

**Comment by Abhishek-kumar09** [comment]
Really Sorry, I had pushed new changes to my branch, due to the demand of other PR creating similar issue.
  > has a PR/ issue been created with https://github.com/pgjdbc/pgjdbc/ 
  
  I have the commits but have not created the PR against their branch, since once earlier we did the same thing created PR in the middle of the development and their ci started failing, maybe because they use released/stable checkstyle and those changes were not there.
  An example is here: https://github.com/pgjdbc/pgjdbc/pull/1961

I have a temporary work around, I am creating a PR to fix the problem with changing wercker.sh

**Comment by romani** [comment]
Fix is merged.
@Abhishek-kumar09, please share here PR to pgjdbc

**Comment by Abhishek-kumar09** [comment]
> please share here PR to pgjdbc

@romani Should I make PR now, since we have one more PR(https://github.com/checkstyle/checkstyle/pull/9079), that may change some code in pgjdbc.
