### ISSUE TITLE
update AnnotationLocationCheckTest to use unique Input file in each test method

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9437]
AnnotationLocationCheckTest.java file reuse `InputAnnotationLocationIncorrect.java` in few different test method.
Expected: each test method in Test class use it own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by romani** [comment]
@SGanguly1999 , please help to fix this issue.

**Comment by SGanguly1999** [comment]
Sure @romani

**Comment by SGanguly1999** [comment]
@romani please see whether my understanding about the issue is clear or not:

My understanding :--Input files are java files (basically code examples) which test classes use in there methods to check a particular feature is working fine or not. In this issue the input files should be separate for each method.

My doubt:-How to understand which feature the test methods are testing?
