### ISSUE TITLE
Apply all Checks over Checkstyle code

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#945]
Base on description of https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2015-Project-Ideas#project-name-practice-what-you-preach

file config/checkstyle_checks.xml contains all Check , but some of them are
commented out or suppressed by ```<property name="severity" value="ignore"/>```

Todo:
1) uncomment each of Check, provide configuration to each Check, resolve violations caused by it.
2) the most complicated cases could be suppressed by separate config file.
3) If some Check is inappropriate for our code - It might be reasonable to run some checks in mode ```<property name="severity" value="ignore"/>``` as that is good test for Exceptions.

4) It might be useful to enforce all Checks as soon as possible by wide suppression file creation and then tackle each Check violations separately.

If Check generate too much false-positives, all his unresolvable violations should be suppressed, and appropriate issue have to be created to let it be used over Checkstyle code (that should be discussed with Admins).

**Comment by mkordas** [comment]
In `config/checkstyle_checks.xml` I see just two checks ignored and one commended out. The problem is that we are missing huge number of checks in the config:
* `AbbreviationAsWordInName`
* `AbstractClassName`
* `AnnotationLocation`
* `AnonInnerLength`
* `ArrayTypeStyle`
* `AtclauseOrder`
* `AvoidEscapedUnicodeCharacters`
* `AvoidInlineConditionals`
* `AvoidNestedBlocks`
* `AvoidStaticImport`
* `BooleanExpressionComplexity`
* `ClassDataAbstractionCoupling`
* `ClassFanOutComplexity`
* `ClassTypeParameterName`
* `CovariantEquals`
* `CustomImportOrder`
* `DeclarationOrder`
* `DefaultComesLast`
* `DescendantToken`
* `DesignForExtension`
* `EmptyCatchBlock`
* `EmptyForInitializerPad`
* `EmptyLineSeparator`
* `EmptyStatement`
* `ExecutableStatementCount`
* `FallThrough`
* `FinalParameters`
* `HiddenField`
* `IllegalTokenText`
* `IllegalToken`
* `IllegalType`
* `ImportOrder`
* `InnerTypeLast`
* `InterfaceIsType`
* `InterfaceTypeParameterName`
* `JavaNCSS`
* `JavadocParagraph`
* `JavadocTagContinuationIndentation`
* `MethodTypeParameterName`
* `MissingCtor`
* `ModifiedControlVariable`
* `MultipleStringLiterals`
* `MultipleVariableDeclarations`
* `MutableException`
* `NPathComplexity`
* `NoClone`
* `NoFinalizer`
* `NoLineWrap`
* `NonEmptyAtclauseDescription`
* `OneTopLevelClass`
* `OverloadMethodsDeclarationOrder`
* `PackageDeclaration`
* `RegexpHeader`
* `RegexpMultiline`
* `RegexpSinglelineJava`
* `RequireThis`
* `ReturnCount`
* `SeparatorWrap`
* `SingleLineJavadoc`
* `StringLiteralEquality`
* `SummaryJavadoc`
* `SuperClone`
* `SuperFinalize`
* `ThrowsCount`
* `TodoComment`
* `TrailingComment`
* `UncommentedMain`
* `UniqueProperties`
* `UnnecessaryParentheses`
* `VariableDeclarationUsageDistance`
* `WriteTag`

**Comment by mkordas** [comment]
First questions:
* class `Check` is abstract, should we rename it to `AbstractCheck`?
* according to AbbreviationAsWordInName `JavaNCSSCheck` should be renamed to `JavaNcssCheck`, do we want such change?

**Comment by romani** [comment]
the main rule in usage of static analysis tool - "do not be fanatic :)"

> class Check is abstract, should we rename it to AbstractCheck?

ideally , yes , it has to be renamed. But for some historical reason that class is part of API. So rename will be serious brake on compatibility. There are tons of custom Checks that we even do not aware of. Lets keep that till we start serious API changes. For now please add that violation in suppression with appropriate comment.

> according to AbbreviationAsWordInName JavaNCSSCheck should be renamed to JavaNcssCheck, do we want such change?

Name of Check is also kind of API, that will damage all existing configs. Please add that case to suppression list as unfortunate mistake from history.


Please do not hesitate to ask me for any questionable case, but simple rule is "if clients are affected - lets suppress that case by case. But new code have to be clear from all violations without any suppressions."

**Comment by romani** [comment]
we need a UT that validate that All Checks that exists in our code are referenced at checkstyle_checks.xml

**Comment by MEZk** [comment]
@romani 
Should UT be failed If a check exists in classpath but is commented in checkstyle_checks.xml ?

**Comment by romani** [comment]
yes, in classpath should be Checks that has to at config file as uncommented and with proper severity.

**Comment by MEZk** [comment]
@romani 
I implemented the test, but we have one check which is commented out in checkstyle_checks.xml. It is IllegalCatch. So, should I mark the test with ```@Ignore``` annotation or provide ignore list as a parameter for the test and include IllegalCatch there?

**Comment by romani** [comment]
Good catch!

Please active it, all its violations are already resolved, we just forgot to activate it.

@rdiachenko , fyi .
