### ISSUE TITLE
 update example of AST for TokenTypes.LITERAL_NATIVE

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9485]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_NATIVE

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by vivek286** [comment]
I am on it

**Comment by AbhinavRajputEXE** [comment]
Hey, @pbludov @romani 
I ran the mvn clean verify command on Newley cloned repo. which I fetched before cloning it and then I ran the `mvn clean verify` command without making any changes and it is still giving me these errors :(
`[ERROR] Errors: 
[ERROR]   MainTest.testNonClosedSystemStreams:408 » InaccessibleObject Unable to make fi...
[ERROR]   AuditEventDefaultFormatterPowerTest » Runtime PowerMock internal error: Should...
[ERROR]   CheckstyleAntTaskPowerTest » ExceptionInInitializer
[ERROR]   CommonUtilPowerTest » Runtime PowerMock internal error: Should never throw exc...
[ERROR]   ConfigurationLoaderPowerTest » ExceptionInInitializer
[ERROR]   DefaultLoggerPowerTest.testNewCtor:49 » NullPointer Cannot read the array leng...
[ERROR]   HeaderCheckPowerTest » ExceptionInInitializer
[ERROR]   ImportControlLoaderPowerTest » Runtime PowerMock internal error: Should never ...
[ERROR]   JavadocPackageCheckPowerTest.testWithFileWithoutParent:53 » NullPointer Cannot...
[ERROR]   MainFrameModelPowerTest » ExceptionInInitializer
[ERROR]   MainPowerTest » ExceptionInInitializer
[ERROR]   PackageObjectFactoryPowerTest » Runtime PowerMock internal error: Should never...
[ERROR]   PropertyCacheFilePowerTest » ExceptionInInitializer
[ERROR]   RegexpOnFilenameCheckPowerTest.testWithFileWithoutParent:52 » NullPointer Cann...
[ERROR]   TreeWalkerPowerTest » ExceptionInInitializer
[INFO]
[ERROR] Tests run: 3649, Failures: 0, Errors: 15, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:40 min
[INFO] Finished at: 2021-11-15T22:29:54+05:30
[INFO] `

after trying a few things I ran `mvn clean compile` command and it changed nothing
then I thought maybe something is wrong with my IntelliJ because everything was working fine few weeks ago so I reinstalled the whole ide and still it changed nothing.
please help me, what should I do

**Comment by AbhinavRajputEXE** [comment]
So previously 15 errors were coming on the clean unedited newly cloned repo. as I explained earlier and even after making the required changes for this issue regardless of those errors it is giving me the same 15 errors on running `mvn clean verify` . can you please verify these changes?
@pbludov

**Comment by romani** [comment]
Fix is merged

**Comment by AbhinavRajputEXE** [comment]
Thank you @romani for guiding me through this PR. 😊
