### ISSUE TITLE
update MissingJavadocMethodCheckTest to use unique Input file in each test method

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9524]
MissingJavadocMethodCheckTest.java file reuse some Input files few time in few different test method.
Expected: each test method in Test class use it own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by bossever** [comment]
I'm on it.

**Comment by bossever** [comment]
I just started work on this, and found that there exist three identical tests with different names, and I couldn't understand what they meant - 
https://github.com/checkstyle/checkstyle/blob/ebef3bd59fdc2c97587a67bc59d57af6ecbb9072/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java#L96-L121

and also - 
https://github.com/checkstyle/checkstyle/blob/ebef3bd59fdc2c97587a67bc59d57af6ecbb9072/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java#L212-L223

Is it supposed to be like this? If so, what am I missing that will help me understand their use?

**Comment by romani** [comment]
it might be mistake, please remove one.

**Comment by bossever** [comment]
> it might be mistake, please remove one.

There are 3 such tests with different names, should I remove 2?

**Comment by AkMo3** [comment]
@romani I think these are intentional as same these same duplicate test are present in [avadocMethodCheckTest.java](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java) also
https://github.com/checkstyle/checkstyle/blob/34e89144aaeb9a2d41313429ab2c97cdcb71bb13/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java#L150-L209

Another instance
https://github.com/checkstyle/checkstyle/blob/34e89144aaeb9a2d41313429ab2c97cdcb71bb13/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java#L211-L235

**Comment by romani** [comment]
if tests are completely the same - it is mistake.
you can remove them and CI will fail if them was required for something.

**Comment by romani** [comment]
Diy is merged
