### ISSUE TITLE
update example of AST for TokenTypes.QUESTION

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9557]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#QUESTION

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by RuchiGitHu** [comment]
I am on it!

**Comment by RuchiGitHu** [comment]
hi @pbludov, I am unable to find html file for screenshot, please guide me as this is my first issue for checkstyle. 80% process of this issue is completed. Please let me know that how can I navigate to the respective html file.  I have already go through the good practice link..
Looking forward for your reply...

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes is updated

**Comment by romani** [comment]
merged
