### ISSUE TITLE
LeftCurlyCheck :  investigate why maxLineLength is required

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#965]
It is not clear why maxLineLength is required for that validation.
Please investiagte.
If not required - remove.
If required - extend a javadoc/xdoc.

**Comment by MEZk** [comment]
@romani
1) Why maxLineLength is required?
Answer:
maxLineLength is required only when left curl brace policy is EOL or NLOW. Lets assume that  line's number of characters (here and after line's length) is less than maxLineLength and left curly brace policy is EOL or NLOW then the left curly brace should be placed at the end of line otherwise the Check rises violation. For example:

Lets set maxLineLength to 50 and assume that we have the following code example:

````java
//line length = 41 < maxLineLength
public class InputLeftCurlyMaxLineLength
{ //violation here
    //line length = 15 < maxLineLength
    void foo()
    { //violation here
        //line length = 37 < maxLineLength
        for (int i = 0; i < 10; i++)
        { //violation here

        }
    }
}

````
Than there are 3 violation marked as ```//violation here```.

Lets assume that maxLineLength = 10. Then above code example will not rise any violations.

2) Extended javadoc/xdoc.
3) Provided [UTs](https://github.com/checkstyle/checkstyle/pull/1466/files#diff-5e045b04dda6de74c388fdc1537e4520R247) to explain the meaning of the option.

**Comment by romani** [comment]
weird, I do not understand explanation, I could understand that it works like that, but I do not understand why "violations" are reported in example. As code is less then maxLineNumber - no violations is expected.
"maxLineLength = 10" is nonsense.

That option is some shade of LineLengthCheck (both of Checks should have the same values for that option), but I do not understand why it is required. LeftCurlyCheck should check position of brace conflicting with another Check is not his problem, user can have LineLengthCheck disabled.

**Comment by MEZk** [comment]
@romani 
maxLineLength allows user set the maximum amount of characters in line for the Check, user can regulate this amount according to his needs. So if left curly brace policy is EOL this means that left curly should be at the end of line, but there might be a very long lines and if we place left curly at the end of the line it will make the line even longer, but if we do not, the Check will rise a violation. So if line's length is less than maxLineLength then the left curly brace should be placed at the end of line otherwise if line's length is greater than maxLineLength then the left curly brace can be placed on a new line.

**Comment by romani** [comment]
>if we place left curly at the end of the line it will make the line even longer

2 characters is never a root problem of long line.
Please call me to discuss that issue.

**Comment by romani** [comment]
merged.
