### ISSUE TITLE
Consider checking non-javadoc comments in javadoc checks.

### ISSUE THREAD

**Issue by isopov** [checkstyle/checkstyle#99]
Within Eclipse when you override or implement a method you can inherit the java doc for the method. Eclipse will produce the following:

````
/
* (non-Javadoc)
* @see junit.framework.TestCase#setUp()
* 
/
````

CheckStyle will flag the method as not having JavaDoc.
Hava the JavaDoc check aware of inherited java doc by being aware that inherited java doc format as presented by Eclipse and supported using the java doc generation tool.
James Tauber detailed the possible out comes of working with Eclipse and inherited java doc or trying to adhere to the CheckStyle java doc check. With the (non-javadoc), Eclipse will actually link and present the inherited java doc when viewing the override or implementation.
http://jtauber.com/blog/2004/05/11/inheriting_doc_in_javadoc_and_eclipse/

**Comment by hohwille** [comment]
This (non-Javadoc) thing is just a totally stupid default of eclipse that does not make any sense. This is not a Java standard or anything like this. As the makers of Eclipse to finally stop this nonsense.
For checkstyle you need to change your eclipse code style templates to /** {@inheritDoc} */
BTW: The proper way to do this is using @Override.
For some strange reason (legcay that does not make sense anymore) checkstyle does not honor @Override. It would be better to adopt checkstyle so it properly supports Java standards instead of supporting (non-Javadoc).

**Comment by romani** [comment]
looks like this problem is fixed awhile ago - https://bugs.eclipse.org/bugs/show_bug.cgi?id=24227

javadoc check right now are not ideal as some of them use regexp to parse javadoc. We prepared new parser for javadoc and take care about javadoc recognized comments only. Checkstyle should support only `/** {@inheritDoc} */`.

> For some strange reason (legcay that does not make sense anymore) checkstyle does not honor `@Override`

please make an exact and separate issue on this.

-----------------

I am closing the issue, as original description of problem is unclear.
