### ISSUE TITLE
Make "all" version available on maven central as well

### ISSUE THREAD

**Issue by onigoetz** [checkstyle/checkstyle#9900]
**How it works Now:**

I maintain a tool (company internal) That runs checkstyle as a pre-commit and pre-receive hook.
This hook is compiled using an internal build process that does not have access to internet.

**The problem**

For every update of Checkstyle we need to
1. Be aware there is an update
2. Download `checkstyle-all.jar` from your GitHub releases
3. Store it in our servers to retrieve during builds.

This way has some drawbacks, for example we can't automate the update using Renovate/Dependabot or other automated tooling.

**Describe the solution you'd like**

Would it be possible to upload the `checkstyle-all.jar` release on your maven repository with a classifier so it can be taken from Maven Central ?
Our Nexus mirror could then pick it up and we could automate that update.

I'm pretty sure we wouldn't be the only ones to benefit from this feature. I hope you'll consider it.

**Additional context**
N/A

**Not a feature?**
N/A

**Comment by rnveach** [comment]
I don't understand why you are not using the version that is already there in maven. Any usage in a pom will pull in the dependencies and make it virtually the same as the all jar.

**Comment by onigoetz** [comment]
Because using Maven you get many different Jars, but since it's going to be used inside a script, it's very impractical.
It's very practical to be able to run `java -jar checkstyle-all.jar`

**Comment by romani** [comment]
We can not upload to maven any jar file, it it restricted to only specific files: non uber jar, javadoc, sources zip, pom.
I would love to host uber jar in maven, but maven repo do not allow this, or I do not know how to bypass such limitation.

**Comment by rnveach** [comment]
It seems to me like this restriction is well founded.

I don't understand the exact process where you are using the all jar but want to restrict downloading from only maven, but maven is meant to house individual dependencies and have you build the full executable by combining each dependency through it's process. This naturally happens when you include checkstyle's current maven into a POM. Housing an all JAR is almost no different than my previous statement and would just bloat their own servers with redundant packages.

You may want to rethink your process.

**Comment by onigoetz** [comment]
Thanks for the input :) 

I will check our process and see how we can work with this. (If I find something I'll post the solution if somebody else needs it.)
