### ISSUE TITLE
wrecker.sh no-error-xxxx requires manual intervention to complete the build.

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#9962]
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

Running `./.ci/wercker.sh no-error-pgjdbc` on local after making some changes to checks.
 Relevant Output ([whole log](https://gist.githubusercontent.com/Vyom-Yadav/411a2e93c49f9d7ae8411b974031e542/raw/2ff075319a33f77a89010114a049ff6b303e9d46/log2.txt))
```
* What went wrong:
Execution failed for task ':benchmarks:checkstyleJmh'.
> Could not resolve all files for configuration ':benchmarks:checkstyle'.
   > Could not find com.puppycrawl.tools:checkstyle:8.43-SNAPSHOT.
     Searched in the following locations:
       - file:/home/vyom/.m2/repository/com/puppycrawl/tools/checkstyle/8.43-SNAPSHOT/maven-metadata.xml
       - file:/home/vyom/.m2/repository/com/puppycrawl/tools/checkstyle/8.43-SNAPSHOT/checkstyle-8.43-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/puppycrawl/tools/checkstyle/8.43-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/puppycrawl/tools/checkstyle/8.43-SNAPSHOT/checkstyle-8.43-SNAPSHOT.pom
     Required by:
         project :benchmarks

```
However this issue was resolved when I executed the command `mvn -e clean install -Pno-validations`. But imo this should not require manual intervention and should run with just the help of a single command.
I don't know much about shell scripting but can't there be a solution like-
```
if(!snapshot_is_present) {
RUN: mvn -e clean install -Pno-validations
}
```
for every command that uses the snapshot. Also I couldn't find any documentation about it anywhere, please point it out if it exists, if not then this should be documented imo.

**Comment by rnveach** [comment]
> `if(!snapshot_is_present) {`

This should not be the condition. Checkstyle snapshot has to be reinstalled every new PR or change in the PR. If you just look for one to be installed, you will get false readings from your runs since you will be executing old code when you are expecting your current code.

Instead, the condition needs to check if the bash script is NOT being run in CI. CI always make sure the PR checkstyle is installed outside the execution of the current regression. It is only a non-CI run where we wish for it to always be installed on every call.

**Comment by nmancus1** [comment]
Removing `mvn -e clean install -Pno-validations` from the bash script was an intentional decision at https://github.com/checkstyle/checkstyle/pull/8950. 

The commit message and PR description from  https://github.com/checkstyle/checkstyle/pull/8950 is : `make semaphore ci commands easy to run on local` . If contributors are struggling to run commands locally, then I think that we have not hit our mark. 

Also, it seems that many CI jobs now build and install install Checkstyle into the local maven repo for each case (in the respective bash script). We should make all cases consistent to make expectations clear for contributors, in any case.

The only drawback that I could see is in the case where we would do `mvn -e clean install -Pno-validations` in `prologue` to conserve resources, but I do not think that we use this method anyway. 

Additionally, if we are building Checkstyle separately in CI to fail fast if `mvn -e clean install -Pno-validations` does not succeed, we could simply run this command in a subshell and verify that it completes successfully.

**Comment by rnveach** [comment]
I'll remove approval so @romani can clarify which path we should take. All in 1 command, or a pre-command with the regression command.

**Comment by romani** [comment]
We discussed this before and I agree that it is not very obvious benefit and there is definitely inconvenience for new contributors who has no experience with maven.

check for SNAPSHOT existence is not valid, as it might exists but correspond to incorrect sources.
all such scripts are focused on execution in CI and be reusable between CIs. Convenience to run the same on local is additional feature.
Unfortunately different CI are very different by orchestration/parallelization/..... so build of chekcstyle is usually done ones and then some binaries reused many times to make CI be quicker.

This definitely conflicts with  convenience to run on local.
But after consideration of all benefits and drawbacks .... we decided to make this in favor of CI.
