### ISSUE TITLE
Travis is failing on xwiki-platform validation

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9967]
build failure in [Travis](https://travis-ci.org/github/checkstyle/checkstyle/jobs/769177295#L6970)
```
[INFO] --- maven-checkstyle-plugin:3.1.2:check (default) @ xwiki-platform-test-integration ---

[INFO] Starting audit...

[ERROR] /home/travis/build/checkstyle/checkstyle/.ci-temp/
xwiki-platform/xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-integration/
src/main/java/org/xwiki/test/integration/maven/ArtifactResolver.java:63:39: 
The String "jar" appears 2 times in the file. [MultipleStringLiterals]

[Audit done.

[INFO] There is 1 error reported by Checkstyle 8.43-SNAPSHOT with checkstyle.xml ruleset.

[ERROR] src/main/java/org/xwiki/test/integration/maven/ArtifactResolver.java:[63,39] (coding) 
MultipleStringLiterals: The String "jar" appears 2 times in the file.
```

**Comment by romani** [comment]
@tmortagne , please help to fix master build of xwiki-platform

**Comment by shashwatj07** [comment]
PR opened https://github.com/xwiki/xwiki-platform/pull/1622

**Comment by tmortagne** [comment]
@shashwatj07 beat me to it, thanks :)

**Comment by romani** [comment]
@tmortagne, should we use stable version/commit of xwiki platform ?
We do not want to be bothered by CI failures on our side if this is not enforced on xwiki side. It makes some mess to fix such problems, as it blocks PRs process.

**Comment by romani** [comment]
fix is merged, but if it happens one more time, I will enforce stable version/commit usage until CI process is enforced in xwiki on code validation.

**Comment by tmortagne** [comment]
> @tmortagne, should we use stable version/commit of xwiki platform ?
> We do not want to be bothered by CI failures on our side if this is not enforced on xwiki side. It makes some mess to fix such problems, as it blocks PRs process.

We don't go through mandatory validated pull requests merged in master if that's what you mean and indeed the master branch is definitely not rock solid currently (even if checkstyle failures tend to be rare since most devs have the tooling to spot them before committing, @vmassol was a bit too quick this time I guess). It's something we have in mind for a while, but it's not so easy to setup right now with XWiki build being very long and the project spanning across several interdependent repositories.

I guess one possibility on your side would be to get the latest tag on xwiki-commons/xwiki-rendering/xwiki-platform using something like `git describe` but it probably requires to clone the whole repository (which is a pity in the case of xwiki-platform which have quite a huge history). Of course the alternative is to arbitrary decide to get *-13.3 tags, but it might be outdated pretty quickly without some process to update it from time to time (but still much better than nothing). Now while it produce more stable builds on your side it also makes much harder to do modifications when something need to change in Checkstyle behavior (which happen from time to time) since you have to wait for a new XWiki release.

**Comment by vmassol** [comment]
> @vmassol was a bit too quick this time I guess

yeah, sorry about that and thanks for the fix!
